### ISSUE TITLE
[FranceTV] No video formats found! / Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity

### ISSUE THREAD

**Issue by djmandell** [yt-dlp/yt-dlp#10163]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Some videos on the France TV website are not downloadable (though some seem to work fine).  One broken url is: 

[https://www.france.tv/france-4/le-refuge-d-audrey/saison-1/5835561-un-nouvel-ami.html](https://www.france.tv/france-4/le-refuge-d-audrey/saison-1/5835561-un-nouvel-ami.html)

The error I receive is:

[FranceTVSite] Extracting URL: https://www.france.tv/france-4/le-refuge-d-audrey/saison-1/5835561-un-nouvel-ami.html
[FranceTVSite] 5835561-un-nouvel-ami: Downloading webpage
[FranceTV] Extracting URL: francetv:44a75f7b-bbfe-4794-9d5e-e56cf0938828#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] 44a75f7b-bbfe-4794-9d5e-e56cf0938828: Downloading desktop chrome video JSON
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity
[FranceTV] 44a75f7b-bbfe-4794-9d5e-e56cf0938828: Downloading mobile safari video JSON
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity
ERROR: [FranceTV] 44a75f7b-bbfe-4794-9d5e-e56cf0938828: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

I've upgraded to the latest nightly and the problem still exists.  There is no login required, no mention of DRM, and as previously stated I can download other content from the site without an issue.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.france.tv/france-4/le-refuge-d-audrey/saison-1/5835561-un-nouvel-ami.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.01.232725 from yt-dlp/yt-dlp-nightly-builds [db50f19d7] (zip)
[debug] Python 3.8.0 (CPython x86_64 64bit) - Linux-4.15.0-1021-aws-x86_64-with-glibc2.27 (OpenSSL 1.1.1  11 Sep 2018, glibc 2.27)
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11
[debug] Optional libraries: certifi-2018.01.18, requests-2.18.4, sqlite3-3.22.0, urllib3-1.22
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.01.232725 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.01.232725 from yt-dlp/yt-dlp-nightly-builds)
[FranceTVSite] Extracting URL: https://www.france.tv/france-4/le-refuge-d-audrey/saison-1/5835561-un-nouvel-ami.html
[FranceTVSite] 5835561-un-nouvel-ami: Downloading webpage
[FranceTV] Extracting URL: francetv:44a75f7b-bbfe-4794-9d5e-e56cf0938828#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] 44a75f7b-bbfe-4794-9d5e-e56cf0938828: Downloading desktop chrome video JSON
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity
[FranceTV] 44a75f7b-bbfe-4794-9d5e-e56cf0938828: Downloading mobile safari video JSON
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity
[debug] Extractor gave empty title. Creating a generic title
ERROR: [FranceTV] 44a75f7b-bbfe-4794-9d5e-e56cf0938828: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2825, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1104, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [FranceTV] 44a75f7b-bbfe-4794-9d5e-e56cf0938828: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Are you in region?

I also get the 422 errors. But then I open the page in my browser and look in dev tools, and I'm getting the same error. This message accompanies the 422 error response from the API, both in yt-dlp and my browser:

> Votre opérateur vous localise dans une zone pour laquelle cette vidéo n’est pas disponible (`___`)

> Your carrier locates you in an area where this video isn't available (`___`)

**Comment by djmandell** [comment]
I am in region, and can confirm that I can watch the video through the browser from the same IP, with no login necessary

**Comment by bashonly** [comment]
> Can you also check if the video plays in your browser with DRM disabled?

^ this 

https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056

**Comment by djmandell** [comment]
Sorry, I missed that the first time.  After following the steps outlined in #4062 I can confirm that the video doesn't play with Widevine turned off, so this is a DRM issue.    This is the first time I've encountered a DRM-encumbered video on the site, so the thought didn't occur to me.   

I'm not sure if it's ok for me to close the issue myself, but it seems that there's nothing more to do.   Thanks for your time and help.

**Comment by bashonly** [comment]
All good, we'll keep this open until #10165 is merged

**Comment by frcab** [comment]
Many non DRM protected videos cannot be downloaded from the France TV since a few days, although they play well in the browser with widevine plugin disabled. For instance:
https://www.france.tv/france-3/la-doc-et-le-veto/la-doc-et-le-veto-saison-2/6039237-plume-noire.html
Below is the complete debug output:

[debug] Command-line config: ['-vU', 'https://www.france.tv/france-3/la-doc-et-le-veto/la-doc-et-le-veto-saison-2/6039237-plume-noire.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.06.11.231018 from yt-dlp/yt-dlp-master-builds [add96eb9f] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-105-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe 4.4.3
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2020.06.20, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.06.11.231018 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.06.11.231018 from yt-dlp/yt-dlp-master-builds)
[FranceTVSite] Extracting URL: https://www.france.tv/france-3/la-doc-et-le-veto/la-doc-et-le-veto-saison-2/6039237-plume-noire.html
[FranceTVSite] 6039237-plume-noire: Downloading webpage
[FranceTV] Extracting URL: francetv:99b814cc-0da1-4ae7-9dd2-e1689113b605#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] 99b814cc-0da1-4ae7-9dd2-e1689113b605: Downloading desktop chrome video JSON
[FranceTV] 99b814cc-0da1-4ae7-9dd2-e1689113b605: Downloading mobile safari video JSON
[FranceTV] 99b814cc-0da1-4ae7-9dd2-e1689113b605: Downloading MPD manifest
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
[FranceTV] 99b814cc-0da1-4ae7-9dd2-e1689113b605: Downloading m3u8 information
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
[FranceTV] 99b814cc-0da1-4ae7-9dd2-e1689113b605: Checking for geo-restriction
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: res, tbr, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [FranceTV] 99b814cc-0da1-4ae7-9dd2-e1689113b605: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1604, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1760, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1819, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2954, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [FranceTV] 99b814cc-0da1-4ae7-9dd2-e1689113b605: Requested format is not available. Use --list-formats for a list of available formats

**Comment by FXAkamatsu** [comment]
hi!
Same on my side since yeterday:

"D:\Apps\yt-dlp.exe" --no-check-certificate  --list-formats "https://www.france.tv/france-5/c-ce-soir/saison-4/6038949-dissolution-la-grande-clarification-ideologique.html" | clip
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
WARNING: Only images are available for download. use --list-formats to see them

**Comment by bashonly** [comment]
@frcab @FXAkamatsu separate issue tracked in #10175
