### ISSUE TITLE
Best quality

### ISSUE THREAD

**Issue by Sonicpromo** [yt-dlp/yt-dlp#10226]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Can somebody please help me out with the quality selection?
I had a script form yt-dl but it feels like too much has changed since then and I see different ways to download the best quality now so I am confused (-x -S etc)
So, what is the best way to download best quality now?
Do I understand that these are the most up-to-date sorting options/preferences?

vcodec: Video Codec (av01 > vp9.2 > vp9 > h265 > h264 > vp8 > h263 > theora > other)
acodec: Audio Codec (flac/alac > wav/aiff > opus > vorbis > aac > mp4a > mp3 > ac4 > eac3 > ac3 > dts > other)

So in theory, "bv,ba,res:2160" should prefer AV1 and Opus and if these are absent, fallback to the rest of the available options?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
By default yt-dlp will use the best quality (if ffmpeg is installed). Moreover, yt-dlp has quite an advanced format sorting algorithm (`hasvid,ie_pref,lang,quality,res,fps,hdr:12,vcodec:vp9.2,channels,acodec,size,br,asr,proto,ext,hasaud,source,id`). From what I've heard youtube-dl's algorithm wasn't as advanced, so I don't think passing your own format selector is necessary. Technically you could pass `-S hasvid,ie_pref,lang,quality,res,fps,hdr:12,vcodec` to prioritise av01 over vp9.2 videos, which are slightly better quality if you have av1 codecs installed (Windows users can download them from https://apps.microsoft.com/detail/9mvzqvxjbq9v)

> I had a script form yt-dl but it feels like too much has changed since then

Side note: I'd recommend reading https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#differences-in-default-behavior if you've previously used youtube-dl. Feel free to also read https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#new-features if you want to make the most out of yt-dlp

> vcodec: Video Codec (av01 > vp9.2 > vp9 > h265 > h264 > vp8 > h263 > theora > other)

vp9.2 is preferred over av01 by default, even though `-S vcodec` prefers av01




> bv,ba,res:2160

I'm pretty sure that's not a valid syntax. The direct translation of that command would be `-f bv,ba -S res:2160`. Notably, `-f bv,ba` will ignore pre-merged formats, and also prevent the video and audio being merged. If you just want the former, although I don't know why you would, use `-f bv+ba` instead. If you just want the latter, use `-f bv*,ba/b` or `--keep-video`. Otherwise just omit that part entirely

> -x -S etc

`-x` is equivalent to `--extract-audio`. I don't think it's one of the commands you're looking for

**Comment by Sonicpromo** [comment]
Thanks for your input!
I will investigate that.
From what I remember I used -x recently to download music playlist and extract audio, probably that's why I left it in my notes. Personally I never seen flac or wav on YT, why it is even an option is beyond my understanding =)

**Comment by Sonicpromo** [comment]
Why close an issue that hasn't been fully resolved...especially since it wasn't even a request smh

**Comment by bashonly** [comment]
What is unresolved? You didn't ask a question in the comment before the issue was closed. Ask a specific question and I'll answer it to the best of my ability.

**Comment by Sonicpromo** [comment]
> What is unresolved? You didn't ask a question in the comment before the issue was closed. Ask a specific question and I'll answer it to the best of my ability.

Please, how do I add sponsorblock into equation that way, so the information from the server is received (either data or ping) and for yt-dlp to not attempt to download until that happens? I use --sponsorblock-remove sponsor only

**Comment by bashonly** [comment]
> Please, how do I add sponsorblock into equation that way, so the information from the server is received (either data or ping) and for yt-dlp to not attempt to download until that happens?

see https://github.com/yt-dlp/yt-dlp/issues/9953#issuecomment-2206764967

**Comment by Sonicpromo** [comment]
It does look unnecessary over-complicated. Is there a chance it will be implemented in a better way as a part of the yt-dlp? Kinda surprised this is not a feature by default. What if I use batch file for example? Doesn't make much sense for a single file, since you can always manually restart it and see the results right away but not in case with the mass download

**Comment by Sonicpromo** [comment]
> > Please, how do I add sponsorblock into equation that way, so the information from the server is received (either data or ping) and for yt-dlp to not attempt to download until that happens?
> 
> see [#9953 (comment)](https://github.com/yt-dlp/yt-dlp/issues/9953#issuecomment-2206764967)

It does look unnecessary over-complicated. Is there a chance it will be implemented in a better way as a part of the yt-dlp? Kinda surprised this is not a feature by default. What if I use batch file for example? Doesn't make much sense for a single file, since you can always manually restart it and see the results right away but not in case with the mass download

**Comment by bashonly** [comment]
> What if I use batch file for example?

Updated the linked comment with an example workaround

> It does look unnecessary over-complicated. 

It's complicated because we're trying make yt-dlp do something that it doesn't truly support yet. Hence the term "workaround."

> Is there a chance it will be implemented in a better way as a part of the yt-dlp? 

Yes, that's why the feature request issue is still open.

**Comment by Sonicpromo** [comment]
> > What if I use batch file for example?
> 
> I've updated the linked comment with another example workaround for this.
> 
> > It does look unnecessary over-complicated.
> 
> It's complicated because we're trying make yt-dlp do something that it doesn't truly support yet. Hence the term "workaround."
> 
> > Is there a chance it will be implemented in a better way as a part of the yt-dlp?
> 
> Yes, that's why the feature request issue is still open.

Thank you!
Can't wait
