### ISSUE TITLE
Question: How to extract BOTH  video file (WITH audio file merged in) AND the same audio as a separate file too

### ISSUE THREAD

**Issue by marcello-pietrobon** [yt-dlp/yt-dlp#10474]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, sorry for asking because probably the answer is on the readme, but after reading the readme I don't seem to find the answer.

The question is:
I use --format 'bestvideo+bestaudio' and this gives me the video with the audio merged into the video file

I would like to **extract BOTH such video (with the audio merged in as I'm already able to have) AND the same audio as a separate file too in one single call** to yt-dlp. How can I do that?

Currently in the examples I can only see examples where have video-only AND audio-only.

I hope I explained myself clearly. Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by marcello-pietrobon** [comment]
Thank you
<br />

> How about using this option:
> 
> ```
> -k, --keep-video                Keep the intermediate video file on disk
>                                 after post-processing


I think I probably would need a similar option like: **--keep-audio**
which doesn't exist.

<br />
<br />

> On the other hand, I haven't yet found an option to download only the intermediate files and keep yt-dlp from merging at all.


maybe the option for you is this one (I haven't tried it):

```
# Download the best video-only format and the best audio-only format without merging them
# For this case, an output template should be used since
# by default, bestvideo and bestaudio will have the same file name.
$ yt-dlp -f "bv,ba" -o "%(title)s.f%(format_id)s.%(ext)s"

```

Best,
M

**Comment by clusterized** [comment]
Either you use the aforementioned `-k` (and have to delete the video file manually) or `bv+ba,ba` (and have the audio downloading twice).
But maybe there's a better third option...

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/issues/2916#issuecomment-1063359892

**Comment by barsnick** [comment]
> I think I probably would need a similar option like: **--keep-audio**
> which doesn't exist.

`-k` does preserve both video and audio.

> `$ yt-dlp -f "bv,ba" -o "%(title)s.f%(format_id)s.%(ext)s"`

I'm a long-time user, but didn't realize a comma `,` instead of a plus `+` was possible! It still doesn't work (for a reason), but that's not this thead's topic. (yt-dlp tries to create both files with the same name, unless I modify the output template.)

**Comment by Lieutenant-L-T-Smash** [comment]
The simplest solution is the one @clusterized gave. I'll repeat it, with expanded keywords:

` --format 'bestvideo+bestaudio,bestaudio'`

That should be all that's needed to achieve the desired result.

**Comment by Lieutenant-L-T-Smash** [comment]
The solution in that comment is:

> You could do `-x -k --exec "del %(requested_formats.:.filepath)#q"`
> 
> (On UNIX, change `del` to `rm`)

I feel the need to give an explanation, because I wanted to understand what was happening here, but it's quite non-trivial, unless you're intimately familiar with how yt-dlp handles metadata about its available or requested streams. While it's possible to grasp by carefully reading the documentation, I don't think it should just be given without some explanation. When I first saw it I wondered if I was expected to substitute "requested_formats" or "filepath" myself, among other things.

Here's how it works:

The syntax %(something) is syntax used within a yt-dlp command to access information from the data-dictionary yt-dlp builds when accessing a stream. It's based on Python string-formatting syntax. The data-dictionary contains things like the video ID, the title, *all* available formats, etc.

Within that data-dictionary, "requested_formats" is an array of sub-dictionaries each containing information about the requested format(s), including things like height, fps, language, url, etc.

The first dot is used to access that array, then the lone colon is Python array splicing notation. It's typically used to isolate a sub-array or substring (like using some_string[2:5] to retrieve the characters from position 2 to 5). When the colon is used alone, it simply returns the entire array. (Question: why doesn't "%(requested_formats.filepath)" work?)

The second dot is used to access an element from within the sub-dictionary, in this case the filepath that is generated by yt-dlp for the download of that format.

Finally the #q is an extension of Python string-formatting postfix notation. The "q" means quoted string, the hash is to split the list into individual quoted strings.

On UNIX/Linux, not only is it necessary to replace "del" with "rm", but the double-quotes should be replaced with single-quotes, because with double-quotes the regular brackets within will be incorrectly interpreted by the shell.

**Comment by bashonly** [comment]
> On UNIX/Linux, not only is it necessary to replace "del" with "rm", but the double-quotes should be replaced with single-quotes, because with double-quotes the regular brackets within will be incorrectly interpreted by the shell.

@Lieutenant-L-T-Smash No, no manual replacement is necessary. This is properly handled by `shlex.join` (used in `yt_dlp.utils.shell_quote`).

```py
>>> from yt_dlp.utils import shell_quote
>>> print(shell_quote(['text', 'text with spaces', '$variable', '"quotes"']))
text 'text with spaces' '$variable' '"quotes"'
```
