### ISSUE TITLE
The --cookies-from-browser command results in `WARNING: failed to decrypt cookie because UTF-8 decoding failed. Possibly the key is wrong?`

### ISSUE THREAD

**Issue by NylaTheWolf** [yt-dlp/yt-dlp#1073]
## Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

**Side Note:** The `WARNING: failed to decrypt cookie because UTF-8 decoding failed. Possibly the key is wrong?` message pops up SEVERAL times. I only put the first two lines with that message and put [...] in place of all the other ones.

```
Admins-MacBook-Pro:~ Victoria$ yt-dlp --print "%(playlist_index)s %(original_url)s %(title)s - %(uploader)s [%(duration_string)s]" --flat-playlist "https://www.youtube.com/playlist?list=WL" --cookies-from-browser chrome:Default --verbose
[debug] Command-line config: ['--print', '%(playlist_index)s %(original_url)s %(title)s - %(uploader)s [%(duration_string)s]', '--flat-playlist', 'https://www.youtube.com/playlist?list=WL', '--cookies-from-browser', 'chrome:Default', '--verbose']
[Cookies] Extracting cookies from chrome
[debug] extracting from: "/Users/Victoria/Library/Application Support/Google/Chrome/Default/Cookies"
WARNING: failed to decrypt cookie because UTF-8 decoding failed. Possibly the key is wrong?
WARNING: failed to decrypt cookie because UTF-8 decoding failed. Possibly the key is wrong?
[...]
[Cookies] Extracted 4753 cookies from chrome (1261 could not be decrypted)
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 
[debug] Python version 3.9.6 (CPython 64bit) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=WL
[youtube:tab] WL: Downloading webpage
ERROR: [youtube:tab] WL: YouTube said: The playlist does not exist.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4187, in _real_extract
    info_dict = self.__real_extract(url, smuggled_data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4255, in __real_extract
    webpage, data = self._extract_webpage(url, item_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4171, in _extract_webpage
    self._extract_and_report_alerts(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 738, in _extract_and_report_alerts
    return self._report_alerts(self._extract_alerts(data), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 735, in _report_alerts
    raise ExtractorError('YouTube said: %s' % errors[-1][1], expected=expected)
yt_dlp.utils.ExtractorError: YouTube said: The playlist does not exist.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4187, in _real_extract
    info_dict = self.__real_extract(url, smuggled_data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4255, in __real_extract
    webpage, data = self._extract_webpage(url, item_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4171, in _extract_webpage
    self._extract_and_report_alerts(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 738, in _extract_and_report_alerts
    return self._report_alerts(self._extract_alerts(data), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 735, in _report_alerts
    raise ExtractorError('YouTube said: %s' % errors[-1][1], expected=expected)
yt_dlp.utils.ExtractorError: YouTube said: The playlist does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 600, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube:tab] WL: YouTube said: The playlist does not exist.

```

## Description

I'm using yt-dlp on my Mac this time around. I wanted to try out the new --cookies-from-browser command, but I kept getting that error for both my Watch Later playlist and another privated playlist. Yt-dlp has been downloaded through Python 3.9.6. I have pip 21.2.4.
```
$ pip --version
pip 21.2.4 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)
```
I've checked if Default is the name of my profile. Looking at the folder, I see the profile picture I use for it, so I must've gotten the right path, at least.

I know I could just extract my cookies, but like I said, I wanted to see how the new command would work. Besides, I thought it might be good to at least report this issue.

Thanks in advance!

**Comment by Filippilny** [comment]
+1, have the same issue

**Comment by pukkandan** [comment]
There are some small changes to the decryption code in the new release. It probably is not going to help your issue, but can you retry anyway? just so that we are all on the same page

@Filippilny are you also using chrome on mac?

@mbway, could u have a look

**Comment by Filippilny** [comment]
`filip@Filip-Mac-mini YouTube % yt-dlp -o '%(playlist_title)s/%(title)s.%(ext)s' -f 'bestvideo+bestaudio' "https://www.youtube.com/playlist?list=WL" --yes-playlist --all-subs --embed-subs --embed-thumbnail --cookies-from-browser chrome --download-archive archive.log --verbose
[debug] Command-line config: ['-o', '%(playlist_title)s/%(title)s.%(ext)s', '-f', 'bestvideo+bestaudio', 'https://www.youtube.com/playlist?list=WL', '--yes-playlist', '--all-subs', '--embed-subs', '--embed-thumbnail', '--cookies-from-browser', 'chrome', '--download-archive', 'archive.log', '--verbose']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/filip/Library/Application Support/Google/Chrome/Default/Cookies"
WARNING: failed to decrypt cookie because UTF-8 decoding failed. Possibly the key is wrong?
[Cookies] Extracted 4244 cookies from chrome (1330 could not be decrypted)
[debug] Loading archive file 'archive.log'

[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.25 (zip)
[debug] Python version 3.9.4 (CPython 64bit) - macOS-11.5.2-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=WL
[youtube:tab] WL: Downloading webpage
ERROR: [youtube:tab] WL: Unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4214, in _real_extract
    info_dict = self.__real_extract(url, smuggled_data)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4282, in __real_extract
    webpage, data = self._extract_webpage(url, item_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4194, in _extract_webpage
    data = self.extract_yt_initial_data(item_id, webpage)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 584, in extract_yt_initial_data
    self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1149, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4214, in _real_extract
    info_dict = self.__real_extract(url, smuggled_data)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4282, in __real_extract
    webpage, data = self._extract_webpage(url, item_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4194, in _extract_webpage
    data = self.extract_yt_initial_data(item_id, webpage)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 584, in extract_yt_initial_data
    self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1149, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1227, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1252, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 601, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube:tab] WL: Unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.`

**Comment by Filippilny** [comment]
@pukkandan yep, I'm using chrome. Also tried with the new 09.25. version, still erroring

**Comment by mbway** [comment]
can you try with this release? https://github.com/yt-dlp/yt-dlp/releases/tag/2021.07.21
just so I know whether something has broken since then or something else, because it was working on MacOS and Chrome when it was first released

**Comment by mbway** [comment]
I set up another MacOS VM and I was able to reproduce this issue with a completely fresh installation and the error still occurs with the original release.
The fix seems quite simple (I was worried that chrome changed something about it's cookie storage). It looks like when using the `find-generic-password` method of obtaining the password I forgot to strip the newline from the returned data. When I was testing before I probably had keyring installed so it used that. I will post a pull request soon

**Comment by Filippilny** [comment]
I compiled the yt-dlp binary from source, with manually changed cookies.py with the changes to reflect the commit, and it worked! Awesome job!

```
filip@Filip-Mac-mini YouTube % /Users/filip/Downloads/yt-dlp-master/yt-dlp -o '%(playlist_title)s/%(title)s.%(ext)s' -f 'bestvideo+bestaudio' "https://www.youtube.com/playlist?list=WL" --yes-playlist --all-subs --embed-subs --embed-thumbnail --cookies-from-browser chrome --download-archive archive.log --verbose
[debug] Command-line config: ['-o', '%(playlist_title)s/%(title)s.%(ext)s', '-f', 'bestvideo+bestaudio', 'https://www.youtube.com/playlist?list=WL', '--yes-playlist', '--all-subs', '--embed-subs', '--embed-thumbnail', '--cookies-from-browser', 'chrome', '--download-archive', 'archive.log', '--verbose']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/filip/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password
[Cookies] Extracted 5578 cookies from chrome
[debug] Loading archive file 'archive.log'

[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.25 (zip)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.9.4 (CPython 64bit) - macOS-11.5.2-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=WL
[youtube:tab] WL: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=WL
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] WL: Downloading API JSON with unavailable videos
[download] Downloading playlist: Watch later
[youtube:tab] WL: Downloading thumbnail  ...
[youtube:tab] WL: Writing thumbnail to: Watch later/Watch later.jpg
[youtube:tab] playlist Watch later: Downloading 48 videos
[download] Downloading video 1 of 48

```

**Comment by NylaTheWolf** [comment]
> I set up another MacOS VM and I was able to reproduce this issue with a completely fresh installation and the error still occurs with the original release.
> The fix seems quite simple (I was worried that chrome changed something about it's cookie storage). It looks like when using the `find-generic-password` method of obtaining the password I forgot to strip the newline from the returned data. When I was testing before I probably had keyring installed so it used that. I will post a pull request soon

Thank you so much! I'm not quite familiar with building from source so I'll try it out next release!

**Comment by pukkandan** [comment]
If you have pip, you can just do `pip3 install --upgrade git+https://github.com/yt-dlp/yt-dlp`

**Comment by jvschiavo** [comment]
I'm having the same error on Debian 11 and yt-dlp 2021.12.01:

```
$ yt-dlp --cookies-from-browser chrome -F https://www.youtube.com/watch?v=dQw4w9WgXcQ
[Cookies] Extracting cookies from chrome
WARNING: failed to decrypt cookie (AES-CBC) because UTF-8 decoding failed. Possibly the key is wrong?
[Cookies] Extracted 110 cookies from chrome (34 could not be decrypted)
```
Any idea how can I solve this?

**Comment by mbway** [comment]
on linux the keys come from a different source so technically this is a separate issue, although the symptom is the same.
What desktop environment are you using? Can you run with --verbose. I can't remember if the extra information is useful but it should be a start.

**Comment by jvschiavo** [comment]
> on linux the keys come from a different source so technically this is a separate issue, although the symptom is the same. What desktop environment are you using? Can you run with --verbose. I can't remember if the extra information is useful but it should be a start.

I'm using Cinnamon. It doesn't look like it has anything useful with verbose:

```
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-F', '--verbose', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/home/user/.config/google-chrome/Default/Cookies"
WARNING: failed to decrypt cookie (AES-CBC) because UTF-8 decoding failed. Possibly the key is wrong?
[Cookies] Extracted 197 cookies from chrome (62 could not be decrypted)
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0, rtmpdump 2.4
[debug] Optional libraries: keyring, sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Available formats for dQw4w9WgXcQ:
```

**Comment by mbway** [comment]
this does highlight a flaw which is that `cookies._get_linux_keyring_password` just defers to the `keyring` library to decide where to read the key from, but it doesn't guarantee that chrome is storing the cookies in the same place. For gnome obviously the keys are in the gnome keyring, for kde it's obviously the kwallet, but for anything else it's not so clear. May have to read the chromium source again to see how they decide.
And whatever keyring yt-dlp chooses should probably be logged as well when `--verbose` is passed

**Comment by mattalexx** [comment]
> For gnome obviously the keys are in the gnome keyring, for kde it's obviously the kwallet

Not necessarily. Chrome's secrets backend can be configured with flags.

**Comment by mbway** [comment]
true, but users don't typically specify a different keyring, and if they did then they would also know to tell yt-dlp to use that keyring. I was referring to what the defaults would be for those DEs

**Comment by xwzy** [comment]
I have encountered the following issue, has anyone else come across a similar problem?

```
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip)
```

```
yt-dlp --cookies-from-browser chrome --cookies cookies.txt
Extracting cookies from chrome
[Cookies] Loading cookie      0/   474WARNING: failed to decrypt cookie (AES-CBC) because UTF-8 decoding failed. Possibly the key is wrong?
Extracted 0 cookies from chrome (474 could not be decrypted)

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

**Comment by xwzy** [comment]
```
yt-dlp --cookies-from-browser chrome https://www.bilibili.com/video/BV1ut4y1M7q5/ 
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1ut4y1M7q5/
[BiliBili] 1ut4y1M7q5: Downloading webpage
Extracting cookies from chrome
[Cookies] Loading cookie      0/   474WARNING: failed to decrypt cookie (AES-CBC) because UTF-8 decoding failed. Possibly the key is wrong?
```

**Comment by mbway** [comment]
most likely these failures are related to the discussion happening here https://github.com/yt-dlp/yt-dlp/issues/6564
