### ISSUE TITLE
Why does yt-dlp get 403 errors but JD2 doesn't?

### ISSUE THREAD

**Issue by MrSmite** [yt-dlp/yt-dlp#10762]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Genuinely curious, when I use yt-dlp to download a playlist, I get 2 or 3 videos before running into a wall of 403 "log in to prove you're not a bot" errors. If I switch over to JDownloader 2, I can get the entire list, albeit at a throttled speed.

Is there something different about how JD2 makes the connection? I don't know much about it but it just seems to work, even though I am not providing login information for either application. I do prefer yt-dlp though because I like to automate it using BAT scripts.

### Provide verbose output that clearly demonstrates the problem

- [] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
This is just a question, not a bug report. no verbose output to provide
```

**Comment by xpalidotious** [comment]
Are you using `--flat-playlist` when downloading playlists with yt-dlp?

If not, then yt-dlp will effectively try to open every video in the playlist.

**Comment by MrSmite** [comment]
Interesting, no I'm not. When I read the definition of that switch, I thought "extract" was referring to listing the playlist on the screen or to a file.

**Comment by Pamilg9** [comment]
https://github.com/iv-org/documentation/pull/581
PR coming from Invidious to avoid YT block.

**Comment by seproDev** [comment]
I can not confirm. Both yt-dlp and JDownloader 2 get hit with the same "Sign in to confirm you're not a bot" message:
![image](https://github.com/user-attachments/assets/61d4e7c1-6979-4387-b9f3-0bc32349205b)

It would have been helpful if you actually provided a verbose log. 
> This is just a question, not a bug report. no verbose output to provide

We ask for a verbose log (even on questions) for a reason. You might not see value in providing a verbose log, but it does provide a lot of value to us by knowing what version you are running, in what environment you are running yt-dlp, what requests were being made, what error exactly happened...

Please share a verbose log of the error happening.

Especially the
> wall of 403 

is strange, since that almost sounds like you are using an outdated yt-dlp version and get hit by the poToken 403s. Either way, impossible to know without a log.
