### ISSUE TITLE
YouTube: Extractor selects worse quality on specific video

### ISSUE THREAD

**Issue by ValiumBear** [yt-dlp/yt-dlp#10834]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt-dlp selects worse video quality on specific YouTube video, perhaps because it's age restricted. In this case 137 is much better but not selected.

URL: `https://www.youtube.com/watch?v=WCwhGCEsU8Q`
![4c47939fe8](https://github.com/user-attachments/assets/b9e7624f-73ca-441e-ba9e-dfb4e976f396)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
`[debug] Command-line config: ['--verbose', 'WCwhGCEsU8Q', '-s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds [6f9e65374] (pip)
[debug] Python 3.11.7 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg git-2024-08-19-507c2a5-ffmpeg-windows-build-helpers (fdk,setts), ffprobe git-2022-10-25-9bed814-ffmpeg-windows-build-helpers, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-1.26.19, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[youtube] Extracting URL: WCwhGCEsU8Q
[youtube] WCwhGCEsU8Q: Downloading webpage
[youtube] WCwhGCEsU8Q: Downloading ios player API JSON
[youtube] WCwhGCEsU8Q: This video is age-restricted; some formats may be missing without authentication. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[youtube] WCwhGCEsU8Q: Downloading tv embedded player API JSON
[youtube] WCwhGCEsU8Q: Downloading web creator player API JSON
[debug] [youtube] Extracting signature function js_a87a9450_108
[debug] Loading youtube-sigfuncs.js_a87a9450_108 from cache
[debug] Loading youtube-nsig.a87a9450 from cache
[debug] [youtube] Decrypted nsig glAAC6_Aond9E-5M => 3iGZRl6JW4ZbLQ
[debug] Loading youtube-nsig.a87a9450 from cache
[debug] [youtube] Decrypted nsig Qx0dBKPN6hj41m-U => jLEPtJGV-ccgig
[debug] [youtube] Extracting signature function js_a87a9450_104
[debug] Loading youtube-sigfuncs.js_a87a9450_104 from cache
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] WCwhGCEsU8Q: Downloading 1 format(s): 248+251`
```

**Comment by seproDev** [comment]
There is no way to know for yt-dlp what video will actually "look better", as such various metrics are used to make a guess on what video will be higher quality.

This is the default sort order yt-dlp uses:
```
lang,quality,res,fps,hdr:12,vcodec:vp9.2,channels,acodec,size,br,asr,proto,ext,hasaud,source,id
```

So `res` has higher priority than `fps`, than `vcodec`, than `size` and so on.
In effect, this means that if multiple formats all have the same resolution, yt-dlp will next see if one of them has a higher frame rate, then it will compare the codec, and only later the actual size. This is done since a 128 kbps mp3 file would sound much worse than a 100 kbps opus file even though the mp3 file is larger.
yt-dlp has a preference for more modern, more efficient codecs. For the video, vp9 is rated higher than AVC, since it is generally considered more efficient.
With YouTube in particular, this can depend on video by video and even scene by scene basis.

Now taking a look at this particular example, since it is very low-quality source footage, both format 137 and 248 look very similar to me. At less than half the filesize vp9 seems like the better choice to me.
Either way, there is no silver bullet to determine the video quality in advance. If you really want to get the highest quality, you will need to download compare for yourself.

**Comment by seproDev** [comment]
I guess you would want something like `-S "res,source,fps,vcodec:-avc"`, but take a look at the readme and see what combination of format sorting and format selection options fits your needs https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#sorting-formats
