### ISSUE TITLE
default format varies

### ISSUE THREAD

**Issue by playgithub** [yt-dlp/yt-dlp#10851]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

#### Env

```
$ yt-dlp --version
2024.08.06
```

#### Example

download_list.txt
```
https://www.youtube.com/watch?v=aaaaaaaaaaa
https://www.youtube.com/watch?v=bbbbbbbbbbb
```

```sh
yt-dlp --batch-file download_list.txt
```

Because downloading fails sometimes,
a loop is used, it loops until all the videos are downloaded.

#### Problem
The first video has been downloaded successfully, say `a.mkv`.
Error occurs when downloading the second video, so the loop will execute the command as below again
```sh
yt-dlp --batch-file download_list.txt
```
Then it's going to download `a.webm` instead of `a.mkv`,
so the same video is downloaded twice in different foramts.
It's not as expected.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
share a verbose log demonstrating the issue

**Comment by seproDev** [comment]
> so the same video is downloaded twice in different foramts.
> It's not as expected.

This is expected. Video titles change, and different formats become available or get removed. To only download every video once, use `--download-archive`

**Comment by playgithub** [comment]
`--download-archive` might not always work, because the download might interrupt before completion.

**Comment by playgithub** [comment]
I'm downloading with a proxy, which is distributed,
i.e. the proxy will connect youtube with variable IP,
e.g. the proxy is initially in USA, then it fails, after reconnection, it is in Germany, and so on.
Would this be the cause?

**Comment by seproDev** [comment]
I don't quite understand. If the download didn't succeed, then the video shouldn't be skipped.

Is your proxy rotating the IP address during download, or are you re-extracting the video yourself?
If the proxy is changing IP during download, you might run in to problems where download links are bound to a certain IP and after changing IP address the download can no longer finish.
If you are retrying yourself/have built some retry logic, you should imo. deal with this kind of aborted download scenario yourself.
I think in 99% of cases it will be fine and the title/available formats will not have changed in between the first and the second extraction. Thus, the download is continued. If the formats did change, what would you want yt-dlp to do? Download a format different from what is specified because an aborted download is still around?
Imo. if you really want such a feature, you should use the python api and keep track of the formats downloaded before yourself.
