### ISSUE TITLE
Use HTML tag data for metadata?

### ISSUE THREAD

**Issue by theDanielJLewis** [yt-dlp/yt-dlp#10879]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Since yt-dlp sometimes loads the HTML of the URL anyway, is there any way to make it pull in information from the HTML to use? For example, pulling in `<meta property="og:title" content="GET THIS TITLE" />`, or all the instances of `<meta property="article:tag" content="TAG HERE" />`, or something from any other unique or repeated HTML tag in the HTML.

I've read through the docs, especially about metadata, and it _seems_ like this isn't already possible. But maybe I'm wrong.

This could really help a ton with organizing videos. For example, a YouTube video could automatically be tagged with the channel it's from. This would be especially helpful if downloading multiple videos from a YouTube playlist. The channel name or tags could be added to the filename, as well.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
This is already done, depending on how the extractor for a particular site works.

There are utility routines for extracting OpenGraph metadata (as in one example above), JSON+LD metadata, various types of hydration JSON, and general `<meta ...>` attributes from HTML. Sometimes the extractor author may not have noticed or cared about some potentially extractable metadata in the HTML page, or the page format may have changed, or the item might not have been reliably available. An apparently available metadata item may be missing for any of these reasons.

Similar considerations apply to extraction from downloaded API JSON, except that the extraction has to traverse the JSON rather than searching the HTML. 

If you think that there is some metadata available for a site that fits into the project's metadata schema (ie, would be a documented value in a video's info-json) but that is not being extracted, you could raise an issue for that site.

Do you think YT videos are not currently tagged with the owning channel, where applicable? They should be.

**Comment by theDanielJLewis** [comment]
I was just using YouTube as an example, but I was thinking of a way that I could customize what text is extracted no matter what extractor is being used, simply by telling it the HTML tag(s) and option attributes to pull from.

For example, maybe I want the Vimeo extractor to pull something from `<div id="unique-div">`, or the generic extractor to get the title from the page's `<h1>` tag instead of something else.

**Comment by absidue** [comment]
Probably easier for you to just modify the code base yourself and run a custom version of yt-dlp for yourself, as there is likely no way to implement something like this generically that works across all extractors, considering that some don't download any HTML pages and exclusively use APIs.

**Comment by dirkf** [comment]
PR #10653 would add support for traversing page HTML à la JS `document.querySelector()` and so conceivably there could be some parameter syntax to specify custom extraction from HTML using that. But issues like those identified by [@absidue](https://github.com/yt-dlp/yt-dlp/issues/10879#issuecomment-2322801492) make such an idea impractical as far as I can see.

Again:
>If you think that there is some metadata available for a site that fits into the project's metadata schema (ie, would be a documented value in a video's info-json) but that is not being extracted, you could raise an issue for that site.

Or even a PR!
