### ISSUE TITLE
[Site Request] video.sibnet.ru

### ISSUE THREAD

**Issue by mradalbert** [yt-dlp/yt-dlp#1094]
## Checklist
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://video.sibnet.ru/popular/video4402606-Motorka_vs_boevoy_kater/
- Single video: https://video.sibnet.ru/popular/video4030653-Konfeta__kak_proizvedenie_iskusstva/

**Comment by KebabLord** [comment]
sibnet is actually supported by  ytdl's generic downloader since 2019 (also works on yt_dlp)
it's just yt_dlp can't retrieve metadata such as resolution, thumbnail etc.

**Comment by gamer191** [comment]
@KebabLord do you want yt-dlp to add support for extracting that data? Otherwise, we might be able to close this issue (I haven't looked into the site yet). 


I should note that the duplicate contained an invalid log, and the user had manually disabled GenericIE (or used a program that does that). Whilst there's definitely good reasons to disable GenericIE, I don't think it's a usecase we can support

**Comment by KebabLord** [comment]
@gamer191 sibnet works excellent with ytdlp, apparently the metadata includes the thumbnail too. Wouldn't be bad if info_json had the resolution,duration etc.

But site provides only one video (720p max) and you can't choose an alternative resolution. Which makes the metadata not much useful. Also one can easily scrape other data himself.

On last few years, there were times ytdl generic failed on sibnet. But adding video.sibnet.net referrer always solved the problem. There is no need for official subnet support (as long as generic downloader keeps working just like last 5 years).

I think you can safely close this issue.

**Comment by pukkandan** [comment]
We'll wait a few days to close in case OP want to chime in

**Comment by dirkf** [comment]
Confirming https://github.com/yt-dlp/yt-dlp/issues/1094#issuecomment-1804995009:
https://github.com/ytdl-org/youtube-dl/issues/31652

The VK extractor module in both yt-dl and yt-dlp has special processing for Sibnet embeds -- I suppose these are particularly present rather than other embed URLs that could be extracted generically from the page.
