### ISSUE TITLE
Ey yo , What is this big ass slash ⧸ ,makes my work so tough

### ISSUE THREAD

**Issue by good1uck** [yt-dlp/yt-dlp#11046]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

【CS2】Counter Strike 2 Soundtrack - 10 Second Countdown / Bomb Countdown.mkv
【CS2】Counter Strike 2 Soundtrack - 10 Second Countdown ⧸ Bomb Countdown.mkv
https://www.youtube.com/watch?v=7YmX7PZqxvY&ab_channel=Yamsman
The original video's title has a small ass slash / , But after downloaded by yt-dlp it becomes big ass slash ⧸
Why??
Because Size doesn't matter?
It matters! 
Damn, i get the video's title from the original video,and i set it as a variable in my RPA softwore(For automatic stuffs' sake). But the automatic process can't move on because of the unexpected big ASS slash ⧸.
It shouldn't be here right?Since we have a small ass slash in the original video.
Please give me a solution

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by october262** [comment]
the only other option i could find is with either --restrict-filenames or --compat-options filename-sanitization
more info here - https://github.com/yt-dlp/yt-dlp/issues/5341

**Comment by dirkf** [comment]
Allowing `/` when rendering the `title` output template field would lead to unexpected directory creation under the control of the site from which videos are being fetched, when `/` is a directory separator in the target filesystem (and not just in the expected target directory if a title includes `../`). 

You need to tell that to the RPA. Perhaps you could have it use the video ID as a key instead. If you want an external process to know the filename created for a video, pass that from the program rather than trying to reproduce its logic, or use a fixed output template.

**Comment by absidue** [comment]
Because the normal slash is not allowed in filenames, so yt-dlp replaces it with a unicode slash so that you still know there was a slash there, the alternative would have been for yt-dlp to remove it entirely.

**Comment by kclauhk** [comment]
The big slash is there because you CANNOT use small slash in filename.
The small slash is denoted to be a directory separator. You can't create any file with a small slash in its filename.
If you can edit your RPA softwore, you may add a line/command to replace the small slash in the variable by the big one, so that the variable match with the actual filename.

**Comment by good1uck** [comment]
> The big slash is there because you CANNOT use small slash in filename. The small slash is denoted to be a directory separator. You can't create any file with a small slash in its filename. If you can edit your RPA softwore, you may add a line/command to replace the small slash in the variable by the big one, so that the variable match with the actual filename.

Yeah Cool Explaination.
I do some replacement work in my RPA now, it works.
