### ISSUE TITLE
Why do I need to update to nightly to request a new site?

### ISSUE THREAD

**Issue by madorian** [yt-dlp/yt-dlp#11451]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The checklist here even asks me to get nightly, just to ask a question and a warning that I'll be shot if not. 

You don't find this a little misplaced?

You also have a supported site file, which the site I'm requesting, filmarkivet.no is not in. I need to still download nightly?

This procedure to follow is unclear, I mean, are the other files which tracks sites in development? If not, then there should be no reason to download nightly. There should also be no reason, whatsoever, to download nightly, to just ask a question. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by madorian** [comment]
This was just closed, without answering the question?

**Comment by seproDev** [comment]
The reason is that often times issues are already fixed or sites already added in newer builds, but people are running old to very old versions and complain that stuff isn't working. Due to the nature of yt-dlp we recommend everyone to use the nightly builds.

If you want to participate in the issue tracker you should install the latest nightly version. And no the suppoerted sites list is not a suplement as it only gets updated on released, and not all sites are listed there (for example due to being handled by the generic extractor).

**Comment by seproDev** [comment]
False positive in virus total. Calling yt-dlp without any arguments makes no web requests.
