### ISSUE TITLE
Metadata embedding being very slow

### ISSUE THREAD

**Issue by kenbaird13** [yt-dlp/yt-dlp#11847]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is it normal for --embed-metadata to take multiple minutes? I have tried it with just that option, but it always takes a long time. I did check CPU usage, but it's very minimal, so that most likely isn't the issue.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
If the video has a large filesize, this is to be expected, since ffmpeg needs to read and write the entire video to disk again.

**Comment by kenbaird13** [comment]
Ahh, okay. So it's an unavoidable consequence of the program's workflow. Alright then, is there a way to convert multiple videos in a playlist in parallel?

**Comment by bashonly** [comment]
No, and you would probably run into an I/O bottleneck if you attempted that anyways

**Comment by kenbaird13** [comment]
I was thinking that it could download and convert at the same time. Anyway, thanks for the help, I guess I'll just wait.

**Comment by QuickHare** [comment]
Just in case it sparks an idea in some people:

For videos which are less than half the available RAM, you can set up a RAM drive and use `--paths "temp:/ramdrive/path/"` to store the temporary files. This is much faster, and can also save on disk writes on solid state drives.

For Linux devices, the tmpfs filesystem can be used to place a RAM drive anywhere you wish. You can also add a line to the /etc/fstab to have the drive mounted (empty) on each restart. When the files are deleted, the memory is freed for other programs again.

For Windows, there are a few programs that can create a RAM drive, but they aren't as flexible. The main issue is that they will use up memory and not release unused space to the system due to how memory is allocated in Windows.

I'll let you search the internet for further help on this if it sounds like something you want to look into, but I thought I'd share in case it gives someone a thought.
