### ISSUE TITLE
add a way to specify a custom error handler

### ISSUE THREAD

**Issue by modernNeo** [yt-dlp/yt-dlp#11912]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

wondering if the org is in favor of adding a way for users to be able to specify custom logic for how to handle an error?

something similar to what I ended up doing here: https://github.com/modernNeo/yt-dlp/commit/701b2786f225caf1336eff31220afe0026fac238

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Why is registering a logger not sufficient?

**Comment by modernNeo** [comment]
different aims, don't you think? registering a custom logger is just about customizing just how the logging prints out what yd-dlp determines needs to be printed out. 

but if someone wants to log something else entirely [or do custom actions that don't even involve logging], registering a custom logger isn't the ideal way to approach that.

**Comment by pukkandan** [comment]
You didn't say what *you* want to do with it

**Comment by modernNeo** [comment]
why does it matter what *I* want to do with it? it's a feature that would be useful to anyone, not just me.

**Comment by Grub4K** [comment]
In the yt-dlp codebase, the logger does the error handling (see `YoutubeDL.trouble`). You should just create a logger which utilizes `error` and implements its own error logic there. To mimic previous behavior you would have to reimplement the logging methods.

Doing that is tedious, which is why output rework offered `Logger.make_derived` where you could override and/or decorate logger methods to add specific behavior.

Note that you will not be able to ignore errors and continue execution as if they never happened; the error has already been raised up the callchain so you will only be able to handle it based on that

**Comment by modernNeo** [comment]
> In the yt-dlp codebase, the logger does the error handling (see YoutubeDL.trouble)

Why is that? those are 2 separate functionalities.

**Comment by modernNeo** [comment]
> You should just create a logger which utilizes error and implements its own error logic there. To mimic previous behavior you would have to reimplement the logging methods.

problem with that is that in `_handle_extraction_exceptions`, the library logs more than just the error message with some exception, the traceback also gets logged and I don't see how its possible to suppress every line of the traceback for a specific exception without suppressing all exception given that all the custom logger would know about an exception [or `record` at that point] is just it's `levelno` which is the same for all logs for all exceptions.

**Comment by Grub4K** [comment]
The yt-dlp logger is not a `logging.Logger`. You might be confusing the two concepts. This has been inherited from YoutubeDL about 15 years ago and was not really modified since. Output refactor can probably change that.

To answer your question, no, please look at `YoutubeDL.trouble`. You can see how it handles traceback, and change the behavior to your liking.

**Comment by modernNeo** [comment]
so you are saying I should override the implementation of `YoutubeDL.trouble`? How do I do that, the only option I see to customize yt-dlp's logger is providing `logger` to the `yt_dlp.YoutubeDL` constructor and that claims that the logger is `a logging.Logger instance.` which is contrary to what you just said.

**Comment by Grub4K** [comment]
Disregard `help(YoutubeDL)` and use <https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#adding-logger-and-progress-hook> as a reference instead. The documentation string is incorrect.

The easiest way to modify the function to your desires is to subclass `YoutubeDL` so that you can decide what happens inside `trouble`, including changing error message/traceback and more. Without more information I can't give a better answer than that.

**Comment by modernNeo** [comment]
so, what you suggested as an interesting solution,

doing

```python
class CustomDL(yt_dlp.YoutubeDL):

    def trouble(self, message=None, tb=None, is_error=True):
        pass

```

does seem to offer a way to customize how an error is handled in one way.

I would say though, imo it's not a perfect solution cause instead of being able to customize how different kind of errors are handled based on Exception type, I have to instead do string comparison which is much more brittle.

**Comment by Grub4K** [comment]
Not quite. `sys.exc_info()` could potentially be used if called from an `except` block, which depends on your usecase. Else, yes, you will have to be doing string comparisons, which makes sense, because there might not be an exception at play at all.

like for example, imagine something like this:
```py
if value is None:
    self.trouble("value cannot be None")
```
There no exception is at play, but `trouble` is still called.

**Comment by modernNeo** [comment]
thanks alot @Grub4K , think I managed to find a solution that works for me. for other devs who also may need help figuring out how to customize the error handler

```python
class CustomDL(yt_dlp.YoutubeDL):

    def trouble(self, message=None, tb=None, is_error=True):
        if sys.exc_info()[0]:
            exception = sys.exc_info()[1]
            # logic for customizing exception handling
            return
        super().trouble(message=message, tb=tb, is_error=is_error)
```
