### ISSUE TITLE
Twitch stream recording just stopped!

### ISSUE THREAD

**Issue by gregtorn** [yt-dlp/yt-dlp#1407]
### Checklist

- [ ] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Had this problem with yt-dl so thought trying yt-dlp. But it still here. 
Was recording a live Twitch stream, 5h all good and then it just stopped recording. No crash no error just stopped.
Im recording on ssd, fresh ffmpeg, no internet problems, have simple  script to loop if something happens. Stream was for 6h. What may be the problem?
![изображение](https://user-images.githubusercontent.com/59104074/138607372-e2d44bef-1d7a-43ba-8c91-01fe204eee86.png)

**Comment by akihap** [comment]
I have the exact same problem and it does not related with the length of the video because the download stop between 10 min and two hours randomly. And i am forced to restart the download, The weird thing is that I did not have this problem the first time I tried it on several stream a week ago and now each times i tried to download a stream i have this problem.
