### ISSUE TITLE
Support downloading byterange manifests with aria2c

### ISSUE THREAD

**Issue by Golumpa** [yt-dlp/yt-dlp#1507]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Support external downloaders such as aria2c to be able to download concatenating requests from m3u8 streams. An example of one is listed below where the audio is separated from the several video streams.

This would allow these m3u8 streams to be downloaded much faster than the default built-in downloader.

https://gist.github.com/Golumpa/78038929ac5bafb3478bf3b9a0f40596

**Comment by nyuszika7h** [comment]
It's already supposed to be supported, but as an alternative you could try `-N 16` with the native downloader.

**Comment by pukkandan** [comment]
The given manifest uses byterange which aria2c does not support. Otherwise, fragmented downloads through aria2c is already supported

**Comment by pukkandan** [comment]
OP's actual issue is that some funimation videos cant be downloaded with aria2c since it is a byterange based manifest. This is expected behavior since aria2c doesnt allow us to specify the byteranges.

However, in funimation's case in specific, the server allows requests without byterange and so support for this can technically be added in the future for specific extractors that we know works with arbitrary byteranges

**Comment by pukkandan** [comment]
> However, in funimation's case in specific, the server allows requests without byterange and so support for this can technically be added in the future for specific extractors that we know works with arbitrary byteranges

This can be tracked in https://github.com/yt-dlp/yt-dlp/issues/1507
