### ISSUE TITLE
Use authinfo.gpg instead of netrc for authentication

### ISSUE THREAD

**Issue by johnhamelink** [yt-dlp/yt-dlp#1706]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Currently, there doesn't seem to be a way to use a gpg-encrypted `~/.authinfo.gpg` file instead of an unencrypted `~/.netrc` file. I use an `authinfo.gpg` file as it's a common way of providing credentials in Emacs. Encryption is obviously preferable over plain-text files for account credentials. I understand that including GPG encryption directly could be considered feature creep, so I'd suggest providing a flag provides the credentials via command output, similar to how `isync` does it. Here's an example of how I use this feature in `isync`'s config:

```
PassCmd "gpg --decrypt ~/.authinfo.gpg 2> /dev/null | grep outlook.office365.com | grep domain.com | sed 's/.*password \\([^ ]\\+\\).*/\\1/'"
```

Perhaps the netrc file could be provided like so:

```
--netrc-cmd "gpg --decrypt ~/.authinfo.gpg 2> /dev/null"
```

The rest of the netrc functionality would work as usual: the `netrc-cmd` flag would expect a decrypted netrc file as the return value.

When trying to use the `~/authinfo.gpg` file directly as-is, a predictable error is shown as the file cannot be parsed:

```
[debug] Command-line config: ['-Uv', 'https://twitch.tv/redacted']
[debug] User config file: /home/john/.config/yt-dlp/config
[debug] User config: ['--netrc', '--netrc-location', '~/.authinfo.gpg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.15.2-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
ERROR: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "/home/john/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "/home/john/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    self.initialize()
  File "/home/john/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 501, in initialize
    self._real_initialize()
  File "/home/john/.local/lib/python3.9/site-packages/yt_dlp/extractor/twitch.py", line 58, in _real_initialize
    self._login()
  File "/home/john/.local/lib/python3.9/site-packages/yt_dlp/extractor/twitch.py", line 61, in _login
    username, password = self._get_login_info()
  File "/home/john/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1219, in _get_login_info
    username, password = self._get_netrc_login_info(netrc_machine)
  File "/home/john/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1191, in _get_netrc_login_info
    info = netrc.netrc(file=netrc_file).authenticators(netrc_machine)
  File "/usr/lib/python3.9/netrc.py", line 30, in __init__
    self._parse(file, fp, default_netrc)
  File "/usr/lib/python3.9/netrc.py", line 39, in _parse
    toplevel = tt = lexer.get_token()
  File "/usr/lib/python3.9/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.9/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
```

**Comment by uberRegenbogen** [comment]
Depending upon your shell
`--netrc-location <(gpg --decrypt ~/.authinfo.gpg 2>/dev/null)`
might serve you.

**Comment by johnhamelink** [comment]
@uberRegenbogen if I'm not mistaken, I can't use a syntax like that in `$XDG_CONFIG_HOME/yt-dlp/config` unfortunately.

**Comment by tejing1** [comment]
Shouldn't there be an option which specifies a command to run to get credentials from its output? It's flexible enough to cover almost any secret storage mechanism without yt-dlp explicitly supporting them all. It also has the advantage of already being a quite common way to configure credentials like this in linux environments due to the prevalence of `pass` and CLIs for various other password managers.

I would suggest 2 new options:
- `--passcmd "<shell command>"` which would normally be supplied together with `--username`.
  The command would be run, and it would be expected to print out the password, followed by a newline. yt-dlp captures this output and uses it as the password. This would be most useful in direct invocation or when yt-dlp is being called from another program. I would make it an error to supply both this and `--password`.
- `--credscmd "<shell command>"` which would normally be used alone.
  The command would be run, after substituting `self._NETRC_MACHINE` for a `%s` or similar in the command, and it would be expected to print out a JSON object on output containing `username` and `password` keys, and possibly others, such as 2FA credentials, on a per-extractor basis. This would be most useful as a permanent configuration option to, by default, get credentials from a specific place, and so should be overridden by `--username`, `--password`, and `--passcmd`. Using JSON here allows for the inclusion of other kinds of credentials as needed, and avoids a potential long tail of encoding-related bugs, without much of a burden on whoever's writing the script, given most every scripting language has easy JSON support (even the shell does, given the existence of tools like `jo` and `jq`).
