### ISSUE TITLE
YouTube Live downloads continue after stream ends

### ISSUE THREAD

**Issue by aphedges** [yt-dlp/yt-dlp#1735]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I sometimes experience issues when downloading YouTube livestreams that do not leave a public archive. For example, I attempted to download <https://www.youtube.com/watch?v=PdLjOMSkcbs> as it was broadcasting. I have found that some livestreams save without issues, but with others, `yt-dlp` never stops downloading. It will repeatedly make queries to YouTube until the program (`ffmpeg`, `python`, or `bash`) is manually killed, which usually results in an improperly ended download.

I used the command `yt-dlp --verbose --write-pages https://www.youtube.com/watch?v=PdLjOMSkcbs |& tee stream_debug_output.txt` in my download attempt. The verbose log is over 17k lines long and close to 10 MB, so I have attached it here instead of putting the complete log in the section below: [stream_debug_output.txt](https://github.com/yt-dlp/yt-dlp/files/7575784/stream_debug_output.txt). The dump files are in [dump_files.zip](https://github.com/yt-dlp/yt-dlp/files/7575791/dump_files.zip). This was run on 2021-11-17, in case that matters.

One thing I've noticed from looking at the log output is the value of lines containing `EXT-X-PROGRAM-DATE-TIME`. The value includes a time that increases throughout the download. When the stream ends, this value stops changing. In this output file, the last value is `Skip ('#EXT-X-PROGRAM-DATE-TIME:2021-11-18T02:11:48.008+00:00')`, which first appears on line 16049. I don't know how relevant this is, but it's something I've noticed multiple times.

I needed to check "I've checked that all provided URLs are alive and playable in a browser" to submit even though it is a lie. This issue seems to specifically be with livestreams that no longer have a live URL.

### Verbose log

```shell
[debug] Command-line config: ['--verbose', '--write-pages', 'https://www.youtube.com/watch?v=PdLjOMSkcbs']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err cp1252 (No ANSI), pref cp1252
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
<see previous section for full file>
```

**Comment by elderlabs** [comment]
iirc this issue originates in `ffmpeg`. It happens when a stream hangs, but `ffmpeg` hasn't received an expected exit code, rather, that's my assumption from experience. The best means of correcting this is to programmatically kill the spawned `ffmpeg` subprocess once a criteria is met, like a variable remaining static for a set number of cycles. As I interface with `ffmpeg` directly, I don't have anything to offer as a fix in code, though this should be a good starting point.

**Comment by DirkDort** [comment]
aphedges,

I made the observation, that these seemingly never ending downloads, which indeed happen with many if not most live streams, will stop around 45 minutes after the show ended and leave a playable video file.

I can live with that, and I assume that this is a security measure by FFMPEG to make sure that a live stream is not simply paused. I mostly download concerts by amateur music bands, who sometimes just pause their streams during stage breaks, and these breaks can easily take 15 minutes or longer.

There must be an option on YouTube to quit a live stream for good, so that YT-DLP sometimes stops immediately, but not all live stream providers are experienced professionals.

In case you experience downloads that do indeed never stop, not even after an hour or two, you can still use the --no-part option and quit the DOS-Window with CTRL_C instead of just closing it. CTRL-C sometimes still requires that one has to wait 15 minutes, before YT-DLP respectively FFMPEG reacts, but it mostly leaves a playable video file, sadly not always.

BTW, the continued requests by FFMPEG don't use any noticeable computing power and they do not download any new data, so lately I simply wait till YT-DLP stops by itself.

I'm not an expert for YouTube and I only use YT-DLP for my private pleasure, without advanced options or background knowledge, so I can only hope that my observations and assumptions are helpful.

Stay safe!

**Comment by pukkandan** [comment]
> In case you experience downloads that do indeed never stop, not even after an hour or two, you can still use the --no-part option and quit the DOS-Window with CTRL_C instead of just closing it. CTRL-C sometimes still requires that one has to wait 15 minutes, before YT-DLP respectively FFMPEG reacts, but it mostly leaves a playable video file, sadly not always.

You do not need to use `--no-part`, and it will always leave a playable file assuming you press Ctrl+C **only once**. If you press it multiple times, ffmpeg panics and you may not always end up with a valid mp4. However, the file is still playable since yt-dlp automatically enables `--hls-use-mpegts` for livestreams. If you don't want to take any risks, I recommend adding the option manually anyway

**Comment by aphedges** [comment]
@elderlabs, `ffmpeg` will need to be killed in a less destructive way than my current attempts. Task Manager does not result in it ending properly.

@DirkDort, I've even tried waiting overnight, and `yt-dlp` does not naturally end on these streams.

@pukkandan, I'll need to try it again when I can find an applicable stream to download. If I recall correctly, I tried pressing `^C` once, and it did nothing, and even multiple `^C`'s did not exit `yt-dlp`. I needed to use the Task Manager to kill it. `^C` works when stopping in the middle of a stream, but after the stream ends, `yt-dlp` seems to get stuck in some sort of unresponsive state.

I wish it were possible to reproduce it easily, but given that I don't have a streaming setup to produce the exact conditions I see this happen under, I don't know how to debug it besides waiting for another applicable stream from one of the YouTubers I watch to occur.
