### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by 2ShedsJackson** [yt-dlp/yt-dlp#183]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Shouldn't yt-dlp use keep-alive when downloading subtitles and thumbnails? Downloading a hundred of YouTube's automatically-generated captions takes a while. I assumed the program would reuse a session when downloading multiple videos from the same site. The number of Retries doesn't seem to apply to subtitles, thumbnails, web page downloads, JSON requests.

Also, shouldn't YoutubeDL.py be renamed?

**Comment by pukkandan** [comment]
> Also, shouldn't YoutubeDL.py be renamed?

No

> The number of Retries doesn't seem to apply to subtitles, thumbnails, web page downloads, JSON requests.

Correct. For webpage downloads and JSON requests, the extractor can use `extractor_retries` if there is a known error. Currently, this is only used by youtube.

> Shouldn't yt-dlp use keep-alive when downloading subtitles and thumbnails? Downloading a hundred of YouTube's automatically-generated captions takes a while. I assumed the program would reuse a session when downloading multiple videos from the same site. 

Sounds like a good idea, but I have no idea how feasible this is to implement

**Comment by 2ShedsJackson** [comment]
> No

I was under the impression that yt-dlp wasn't called youtube-dlp partly to distance itself from the recent takedown of youtube-dl.

> Correct. For webpage downloads and JSON requests, the extractor can use `extractor_retries` if there is a known error. Currently, this is only used by youtube.

> Sounds like a good idea, but Idk how feasible this is to implement

Well, consider it an unofficial feature request or maybe I'll get around to to working on it later. Sometimes, downloading captions from YouTube results in a couple of files not being downloaded due to HTTP errors on YouTube's end.

**Comment by pukkandan** [comment]
Supporting retries for subs should be trivial. I'll look into it

> I was under the impression that yt-dlp wasn't called youtube-dlp partly to distance itself from the recent takedown of youtube-dl.
No. There was no particular reason for it. This project was originally forked from [blackjack4494/yt-dlc](https://github.com/blackjack4494/yt-dlc) and when I was asked to rename it for better identifiability, I just changed it to `yt-dlp`. I honestly didnt put much thought into it

**Comment by tsukumijima** [comment]
It's just a personal idea, but unless you have a specific reason to name it yt-dlp, I'd like to rename yt-dlp to youtube-dlp.
I think it's easier to understand at a glance that the name "youtube-dlp" is a fork of youtube-dl.
The name "yt-dlp" cannot be understood as a fork of youtube-dl without recognizing that "yt-dl" is an abbreviation for youtube-dl.
Also, when you line up with youtube-dl / youtube-dlc / yt-dlp, there is no sense of unity.
I initially thought the name of this project was youtube-dlp and "yt-dlp" was just an abbreviation to avoid deletion. I got an error when I ran `pip install youtube-dlp`, so for the first time I noticed that "yt-dlp" was the name of the project and was also registered as "yt-dlp" on my PyPi. In this way, it would be confusing if the project name is "yt-dlp".
Also, I think this is a matter of personal aesthetics, but I think youtube-dlp is more beautiful than yt-dlp.
I know it's hard to change the project name, but I'd like to ask if possible.
(Since Google Translate is used, the sentence may be unnatural)

**Comment by pukkandan** [comment]
> It's just a personal idea, but unless you have a specific reason to name it yt-dlp, I'd like to rename yt-dlp to youtube-dlp.

Now that `yt-dlp` has been set as the project name everywhere, I am not open to changing it anymore

**Comment by tsukumijima** [comment]
Is that so ... the features are perfect, so that's the only regrettable.

**Comment by 2ShedsJackson** [comment]
yt-dlp and its predecessors can download media from sites other than YouTube so it's strange for any of the programs to be named after YouTube.
