### ISSUE TITLE
Best compatible audio

### ISSUE THREAD

**Issue by mirdoraghi** [yt-dlp/yt-dlp#2040]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I want download videos in mp4 format with best audio. but sometimes I get an error. Can some one explain to me what is this error and what should I do?

Requested formats are incompatible for merge and will be merged into mkv.

`yt-dlp -f "{formatId}+ba" url`

I selected formatId in formats list where ext is mp4.

**Comment by pukkandan** [comment]
That is not an error! It is just saying that the formats you selected is being merged into `mkv` because they are not compatible to be merged into mp4/webm (as far as yt-dlp knows).

However, the detction of compatible formats is not very good atm. See #1482. For now, if you are sure the formats can go into mp4, you can use `--merge mp4` to force it

**Comment by mirdoraghi** [comment]
@pukkandan How to find mp4 formats compatible with best audio of video ?

**Comment by pukkandan** [comment]
The current code checks compatibility only by extension. So mp4+m4a=>mp4, webm+webm=>webm, anything else to mkv
