### ISSUE TITLE
Video URL written in comment, is displayed in MPC as information

### ISSUE THREAD

**Issue by Feathered-Serpent** [yt-dlp/yt-dlp#2199]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi everyone,

I'm not sure how many of you use MPC for playing videos. Though it is possible to show video information at the bottom of the window, like this:
![Synposis](https://user-images.githubusercontent.com/72162369/147859005-65dafc08-de62-42e6-a956-ea74e0e03b3b.png)

Now you already see the problem (lower part of the image is MediaInfo): the URL is the comment, which is displayed in MPC as the description. The Synopsis, which is the description of the video, is not to be seen. Can/Should this be changed? I mean the URL is in the PURL tag anyway. I guess MPC takes a certain order to display as description. I haven't found a way to change which tag is displayed in MPC if anyone knows one.

I have other videos which have the Youtube details written in the Comment tag, not as Synapsis, thus I think it is something that changed at some point.

**Comment by pukkandan** [comment]
From: https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior


* Some metadata are embedded into different fields when using `--add-metadata` as compared to youtube-dl. Most notably, `comment` field contains the `webpage_url` and `synopsis` contains the `description`. You can [use `--parse-metadata`](https://github.com/yt-dlp/yt-dlp#modifying-metadata) to modify this to your liking or use `--compat-options embed-metadata` to revert this

This change was made because not all formats support `purl` and it is important to always preserve the URL somewhere imo. According to specs, `comment` is supposed to be the "short" description and `synopsis` is the "long" description. Perhaps you could ask mpc devs to display synopsis also in the UI if present. Or, you could revert this behavior in yt-dlp as mentioned above

**Comment by Feathered-Serpent** [comment]
How about the official URL tag as specified in the Matroska documentation?

https://matroska.org/technical/tagging.html

**Comment by pukkandan** [comment]
Do you mean this? 

> URL | UTF-8 | URL corresponding to the tag it’s included in

It is a nested tag, not a global one

Besides, like I said, the issue is that purl isn't supported by **all** formats. mkv supports any arbitrary fields. So if you only use mkv, you can modify the metadata as you wish. But yt-dlp's defaults should account for mp4/webm/m4a/mp3 etc too

**Comment by NanaMizukiAnother7** [comment]
Seems to be the same as #941 to me.
