### ISSUE TITLE
[Site Request] https://whowatch.tv/

### ISSUE THREAD

**Issue by Ronam22** [yt-dlp/yt-dlp#223]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.04.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single live: https://whowatch.tv/viewer/20955774 (might be offline by the time checked)
- https://whowatch.tv/ <- main page able to grab anyone online at the time to check

## Description

Japanese livestream website.

**Comment by pukkandan** [comment]
For devs:

The m3u8 URL can be obtained from `https://api.whowatch.tv/lives/<id>/play` and all metadata from `https://api.whowatch.tv/lives/<id>`

**Comment by nao20010128nao** [comment]
I already have Whowatch extractor here: https://github.com/nao20010128nao/ytdl-patched/blob/master/youtube_dl/extractor/whowatch.py ~~No proxies, of course~~

But I have to consider something related to porting:
- for RTMP formats, it uses `ffmpeg` instead of `rtmpdump`, because `rtmpdump` will not work for Whowatch livestreams. Is it acceptable to substitute `m3u8` for that?
- for formats which only contain Video and Audio, it must be merged while downloading. Current youtube-dl architecture doesn't aware merging streams for live streams, it has workaround at `FFmpegFD` to download both streams at once. Should I merge that too?
  - (I'm re-investigating Whowatch, this may be lifted from consideration)

**Comment by pukkandan** [comment]
> for RTMP formats, it uses ffmpeg "protocol" instead of rtmp (which calls rtmpdump), because rtmpdump will not work for Whowatch livestreams. Is it acceptable to substitute m3u8 for that?

No, using a new protocol is the right way (similar to `m3u8` and `m3u8_native`). Just name it something more descriptive like `rtmp_ffmpeg`. Do you know why rtmp can't download it?

> it has workaround at FFmpegFD to download both streams at once

I am interested in this even if not needed for this website. Can you point me to the relevent commits?

**Comment by nao20010128nao** [comment]
@pukkandan 

> No, using a new protocol is the right way (similar to `m3u8` and `m3u8_native`). Just name it something more descriptive like `rtmp_ffmpeg`. Do you know why rtmp can't download it?

idk, but I'm sure `rtmpdump` don't work. (tested yesterday)

> I am interested in this even if not needed for this website. Can you point me to the relevent commits?

This one is you're looking for: https://github.com/nao20010128nao/ytdl-patched/commit/0ad2a011547e7cbdf93736bee14f348089cb2e46#diff-d68509c4574bff5a486e17ef94fc9f488a935f8e00896ccb4e0a095d46aa11e6

**Comment by pukkandan** [comment]
> This one is you're looking for: nao20010128nao/ytdl-patched@0ad2a01

That is simple enough. I am more interested how you are doing the format selection to pass both URLs to the downloader simultaneously

**Comment by nao20010128nao** [comment]
> That is simple enough. I am more interested how you are doing the format selection to pass both URLs to the downloader simultaneously

There is no format selected involved; I only added `extra_urls` key for downloader.

**Comment by pukkandan** [comment]
hm.. This discussion is getting off-topic. We can discuss on discord
