### ISSUE TITLE
[Discussion] Consider switching away from Unlicense

### ISSUE THREAD

**Issue by MrRawes** [yt-dlp/yt-dlp#2345]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

i know this will sound outlandish but i have multiple reasons for the change
https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense
https://web.archive.org/web/20170301020915/https://lists.opensource.org/pipermail/license-review/2012-January/001386.html

So what to change it to, i am restricting it to [Public-domain-equivalent licenses](https://en.wikipedia.org/wiki/Public-domain-equivalent_license) in order to not add anymore restrictions and for code reuse

this is a list the flaws in these public-domain-like licenses.

[WTFPL](http://www.wtfpl.net/about/)
1. [not effective in lots of countries](https://www.gnu.org/licenses/license-list.html#informal)
2. does not have a express patent grant

[CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode)
express denial of patent grant

[0BSD](https://spdx.org/licenses/0BSD.html)
1. some argument about the inclusion of and/or
https://www.gnu.org/licenses/license-list.en.html#ISC
https://marc.info/?l=openbsd-misc&m=120618313520730&w=2
2. does not have a express patent grant

[MIT-0](https://github.com/aws/mit-0)
the only problem is that it does not have a express patent grant though [there is some argument for patent grant](https://opensource.com/article/18/3/patent-grant-mit-license)

so based on those choice's i would choose MIT-0
if we were choosing reguler licenses i would choose [BSD+Patent](https://spdx.org/licenses/BSD-2-Clause-Patent.html)

**Comment by Mennaruuk** [comment]
Thank you for this post. I’ve been pondering over this for a while, and I’m happy someone finally brought this topic to light. Not a lawyer, but here are my $0.02:

I agree that the Unlicense is problematic. In general, it’s recommended to use CC0 over the Unlicense. But of course, CC0 wasn’t really made with software in mind.

Respectfully, I disagree with the recommendation of the MIT license. Don’t be deceived by its popularity. It’s excessively permissive, so permissive that it cheapens the hard work of contributors. Sharing changes isn’t a requirement, so a project like yt-dlp doesn’t attract as many changes back, and it becomes essentially a one-way road. Another issue: patents. The MIT license as it stands doesn’t explicitly prohibit patent trolling. In theory, anyone can patent yt-dlp then weaponize that patent to sue the contributors to or users of yt-dlp and accuse them of patent infringement. There exist arguments contradicting this, but they’re interpretations and merely speculative, and I’m not sure they’re worth the trouble of using this license.

My recommendation is the Apache license, version 2. It’s basically the MIT license but so much better. It has an express grant of patent rights from contributors. It requires sharing changes. It isn’t copyleft, so software currently proprietary can incorporate yt-dlp without the headache of open-sourcing everything. My only pet peeve is changes aren’t required to be made available upstream, but that’s the consequence of a permissive license. (If anyone wants yt-dlp to use a copyleft license, my recommendations are the Mozilla Public License 2.0 or the stronger AGPLv3.)

For more information, please take a look at Janis Lesinskis’ blog [The MIT licence is community hostile](https://www.lesinskis.com/MIT-licence-community-hostile.html).

**Comment by pukkandan** [comment]
I was waiting to see what happens with youtube-dl before further discussing this. Since it is now back (https://github.com/ytdl-org/youtube-dl/issues/30568), I am closing this. yt-dlp will continue using whatever license youtube-dl does

**Comment by nyuszika7h** [comment]
Technically switching to a different public domain-like license should still allow full cross-compatibility between the two projcts. But I don't understand what's so wrong with the 
Unlicense. People claim it's illegal/unenforceable in Germany - the public domain declaration may very well be, but that's precisely why it contains a fallback clause.

**Comment by MrRawes** [comment]
> Technically switching to a different public domain-like license should still allow full cross-compatibility between the two projects. But I don't understand what's so wrong with the Unlicense. People claim it's illegal/unenforceable in Germany - the public domain declaration may very well be, but that's precisely why it contains a fallback clause.

the fallback MAY also be problematic

**Comment by fstirlitz** [comment]
> yt-dlp will continue using whatever license youtube-dl does

Last I heard, the new maintainer @dirkf [wasn’t particularly happy with the Unlicense either](https://github.com/ytdl-org/youtube-dl/pull/30184#issuecomment-959769140), so if that’s your main concern, this is not necessarily set in stone either…

**Comment by dirkf** [comment]
No, but that sort of decision would have to rest with @rg3, and we would have to be sure that the existing code could be validly re-licensed, etc.

Looking at https://choosealicense.com/appendix/: 

| Characteristic | Desired? |          Description                  |
|----------------|----------|---------------------------------------|
| Commercial use | yes | The licensed material and derivatives may be used for commercial purposes.|
| Distribution | yes |    The licensed material may be distributed. |
| Modification | yes  | The licensed material may be modified. |
| Patent use yes/no | needs thought   |   This license provides an express grant of patent rights from contributors/explicitly states that it does NOT grant any rights in the patents of contributors. |
| Private use | yes |    The licensed material may be used and modified in private. |
| Disclose source | my preference |  Source code must be made available when the licensed material is distributed. |
| License and copyright notice always/source | prefer always |     A copy of the license and copyright notice must be included with the licensed material/must be included with the licensed material in source form, but is not required for binaries. |
| Network use is distribution | my preference |     Users who interact with the licensed material via network are given the right to receive a copy of the source code. |
| Same license always/existing files/except as library| prefer library |    Modifications/Modifications of existing files/Modifications except code that calls the work as a library must be released under the same license when distributing the licensed material. In some cases a similar or related license may be used. |
| State changes | my preference |     Changes made to the licensed material must be documented. |
| Liability | yes  |   This license includes a limitation of liability. |
| Trademark use | probably good |     This license explicitly states that it does NOT grant trademark rights, even though licenses without such a statement probably do not grant any implicit trademark rights. |
| Warranty | yes |    This license explicitly states that it does NOT provide any warranty. |

**Comment by nyuszika7h** [comment]
Isn't the whole point of the Unlicense that you don't have to ask anyone's permission to relicense the code? You can ask if you want to be nice, but it shouldn't be necessary.

**Comment by dirkf** [comment]
You'd think so. IANAL.

**Comment by MrRawes** [comment]
(IANAL this is my own interpretation)
the issue with GPL is linking incompatible licensed software through --exec may be ilegal, so if your going with gpl go with [LGPL-2.1-or-later](https://spdx.org/licenses/LGPL-2.1-or-later.html) or GPL with [exeption](https://spdx.org/licenses/Classpath-exception-2.0.html)

**Comment by nyuszika7h** [comment]
Or just use MPLv2.

**Comment by MrRawes** [comment]
this my sound quite radical, choosing from permissive licenses i would choose [[Blue Oak Model License 1.0.0](https://spdx.org/licenses/BlueOak-1.0.0.html)](https://spdx.org/licenses/BlueOak-1.0.0.html) or [BSD-2-Clause Plus Patent License](https://spdx.org/licenses/BSD-2-Clause-Patent.html)

**Comment by rg3** [comment]
> No, but that sort of decision would have to rest with @rg3

Hehe, I don't want to be the one taking that kind of decision.

> Isn't the whole point of licenses like the Unlicense that you don't have to ask anyone's permission to relicense the code? You can ask if you want to be nice, but it shouldn't be necessary.

IANAL, but that's my interpretation as well. Since the whole project is licensed under the Unlicense, it should be possible to redistribute it as GPLv3 without issues, for example.

> Some relevant points of discussion: [ytdl-org/youtube-dl#10581 (comment)](https://github.com/ytdl-org/youtube-dl/issues/10581#issuecomment-249298606), #348

Thanks for the context, I was not aware of the code copied from CPython. It was after my tenure as the maintainer.

Just to give you a bit more info, when youtube-dl was created I started using the MIT license but later moved to indicating the code was released to the public domain, claiming no copyright. However, given that's legally an issue (many countries simply do not allow that), after I was no longer the maintainer we discussed if we should relicense the code under some other license with the same goals, and the copyright holders agreed on releasing the code using the Unlicense. At the moment Unlicense was proposed I was not as aware as I am now of the different licenses to release code to the public domain, I was basically aware of the differences between, say, BSD or MIT and the GPL, and knew the latter pretty well.

Some time after that I read that the Unlicense can also be a bit problematic. For example, the GNU project [recommends using CC0](https://www.gnu.org/licenses/license-list.en.html#Unlicense) if your desired goal is giving maximum permissions to everyone and it was also considered a poor license when [reviewed in the OSI mailing list](https://web.archive.org/web/20170301020915/https://lists.opensource.org/pipermail/license-review/2012-January/001386.html). These days, when I want to release a piece of software to the public domain, I use [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) as some people with more legal background than myself recommend.

From the POV of youtube-dl, and perhaps yt-dlp, there's a balance to strike regarding its license. For example, on a few occasions in the past we've wanted to solve issues with the program by using or incorporating pieces of code from other projects, and the desire to keep youtube-dl's license means we cannot simply do that without relicensing the project. So, as consumers of other code, we'd definitely benefit from using GPLv2, GPLv2+ or GPLv3 because that would allow us to use code almost from anywhere.

But at the same time, youtube-dl is consumed by many other projects. AFAIK, if they just call the command line tool when present, there's no embedded youtube-dl code in the program and legally it wouldn't be a derivative work, so in that case youtube-dl's license is irrelevant. If, however, they use youtube-dl as a module or runtime dependency, that would have consequences. I'm not aware of how many projects fall in that area.

Personally, I think the best licenses depending on the case are:

* CC0 for when you want your code released to the public domain.
* MIT or Apache 2.0 if you don't mind proprietary forks of your code and prefer a permissive license. Apache 2.0 is much longer but essentially gives the same rights as MIT while including patent protection clauses and is considered legally safe by many companies due to this, when large companies collaborate in the same project.
* GPLv2, GPLv2+ and GPLv3 if you want the viral aspects of the license and keeping derived works free software. I prefer GPLv3 if possible due to the patent clauses, but sometimes GPLv2+ can be a good option if you want to use code from other projects.

My two cents: choosing a license outside that set needs a very good reason, IMHO. The licenses above are well-known to everyone and cover most use cases.

**Comment by nyuszika7h** [comment]
One possible benefit of MPLv2 over GPL is that it's file-level, so you can keep copyleft while avoiding issues with the GPL possibly infecting the whole code of someone who wants to embed youtube-dl/yt-dlp, they'd only have to keep modifications to projects taken from yt-dl(p) open source.

But as for the other more niche permissive licenses mentioned, yeah, I don't really see much benefit of using those over something established like MIT or Apache 2.0.

**Comment by pukkandan** [comment]
If we were to go copyleft, LGPL is a much better alternative than GPL for youtube-dl imo

**Comment by rg3** [comment]
> If we were to go copyleft, LGPL is a much better alternative than GPL imo

Ah, forgot to include the LGPL licenses in the mix. Yes, those make a lot of sense for many cases as well IMHO. Same for the AGPL if you don't like to see your code turned into a proprietary service.

**Comment by gamer191** [comment]
> the GNU project [recommends using CC0](https://www.gnu.org/licenses/license-list.en.html#Unlicense) if your desired goal is giving maximum permissions to everyone

The do in their entry about the Unlicense, but they have a [separate entry](https://www.gnu.org/licenses/license-list.html#CC0) about the CC0 license which recommends against it for software

**Comment by dirkf** [comment]
The recommendations are not impartial. As usual, when GNU documentation says 'compatible with the GNU GPL', the actual meaning is 'subordinate to ...'.

**Comment by BOplaid** [comment]
While it is true that yt-dlp commonly merged yt-dl changes back in its earlier days from what I've seen, that's almost never the case anymore as far as I can tell.
I think this should be reconsidered honestly

**Comment by gamer191** [comment]
In my opinion the biggest issue with relicensing is that it breaks expectations and could cause other projects to accidentally commit license violations

For example, if a program is bundling yt-dlp, we don't want them to suddenly be violating copyright law if they automatically update it without noticing the license change

**Comment by BOplaid** [comment]
> In my opinion the biggest issue with relicensing is that it breaks expectations and could cause other projects to accidentally commit license violations
> 
> For example, if a program is bundling yt-dlp, we don't want them to suddenly be violating copyright law if they automatically update it without noticing the license change

While I personally like GPL and co. I believe a public domain license is best for this project (IANAL btw). And we already know the Unlicense is not the best, so I think a better public domain license would be good. And AFAIK that wouldn't get bundlers into trouble, would it?
