### ISSUE TITLE
[YouTube] Record restricted livestream

### ISSUE THREAD

**Issue by BiRooT** [yt-dlp/yt-dlp#2367]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello,

I'm member of a youtube channel and I want to record private stream of this channel restricted to members.
I know how to extract cookies, and I use yt-dlp to extract some restricted members only videos of this channel.

Problem is, when this channel start a livestream, I don't know URL of this private livestream, this cannot be accessible via permalink "https://www.youtube.com/channel/<channel_ID>/live"
I think this kind of stream appear in community tab of this channel.

Do you know a way to automatically retrieve this url and start recording ? (Script to monitor this community tab and start record for exemple) ? 

Thanks for your help.

**Comment by krichbanana** [comment]
By "private" and "restricted", I assume you mean members-only?

As far as I know from my limited understanding, there is not a "way" to get any upcoming or live members-only livestreams via a simple link. That is something YouTube would have to implement in order for yt-dlp to support it. You would have to repeatedly check every couple minutes for new videos on the channel.

You can choose to download only new videos by using a download archive to exclude already-seen videos. To set this up, add all the videos you don't want to download:
```
yt-dlp --cookies <your_cookies.txt> --simulate --flat-playlist --force-write-archive --download-archive all_videos.txt <channel_url>/videos
yt-dlp --cookies <your_cookies.txt> --simulate --flat-playlist --force-write-archive --download-archive all_videos.txt <channel_url>/community
yt-dlp --cookies <your_cookies.txt> --simulate --flat-playlist --force-write-archive --download-archive all_videos.txt <channel_url>/membership
```

Then you can periodically call yt-dlp on either the community or membership tab to download the latest videos. Using the membership tab should be faster, but the community tab is less likely to be broken by changes from YouTube. The membership tab has the benefit of including *only* membership videos and posts.

This command will download all videos on the /membership tab that is not in the download archive (which should be none), and will try to download the first upcoming livestream no less than every 15 seconds if it is not yet live:
```
yt-dlp --cookies <your_cookies.txt> --download-archive all_videos.txt --wait-for-video 15 <channel_url>/membership
```

Call this every couple minutes or so using a script in order to catch newly available streams.

**Comment by BiRooT** [comment]
Yep members-only ;)
Good idea ! I will work on this to automate this.
Thanks for your help :)
