### ISSUE TITLE
Don't trim underscores from `uploader`, `playlist_id`

### ISSUE THREAD

**Issue by AlttiRi** [yt-dlp/yt-dlp#2761]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How to don't trim underscores (`_`), dashes (`-`) from `uploader`, `playlist_id`, ...?

I don't like that, because it removes the valid path characters and it makes not possible to recreate the correct download URL from the file name. 

For example: [https://www.tiktok.com/@calmnature_](https://www.tiktok.com/@calmnature_)
- `playlist_id` is `calmnature_` 
- `uploader` is `calmnature_`.

But I get `calmnature` in filenames instead of `calmnature_`.

https://www.tiktok.com/@calmnature is not the same user as [https://www.tiktok.com/@calmnature_](https://www.tiktok.com/@calmnature_).
https://www.tiktok.com/@nature_tik_tok is not the same user as [https://www.tiktok.com/@\_nature_tik_tok\_](https://www.tiktok.com/@_nature_tik_tok_).
[https://www.tiktok.com/@nature_is_beautiful](https://www.tiktok.com/@nature_is_beautifu), [[_]](https://www.tiktok.com/@nature_is_beautiful_), [[__]](https://www.tiktok.com/@nature_is_beautiful__), [[___]](https://www.tiktok.com/@nature_is_beautiful___).

---

My  `yt` alias in `.bashrc`:
```bash
alias yt='yt-dlp --write-thumbnail --write-description \
-o "[%(webpage_url_domain)s] %(user,uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(id)s—%(fulltitle|)s.%(ext)s" \
-o "pl_thumbnail:[%(webpage_url_domain)s][thumbnail] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(playlist_id,id)s—%(fulltitle|)s.%(ext)s"'
```

The result filename:
- [tiktok.com] calmnature—2022.01.06—7050225950084156677—What a beautiful view, amazing. #relaxing #relaxingvideo #nature #beautifulnature #hiking #walking.mp4

The expected filename:
- [tiktok.com] **calmnature_**—2022.01.06—7050225950084156677—What a beautiful view, amazing. #relaxing #relaxingvideo #nature #beautifulnature #hiking #walking.mp4

### Verbose log

```shell
[debug] Command-line config: ['--write-thumbnail', '--write-description', '-o', '[%(webpage_url_domain)s] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(id)s—%(fulltitle|)s.%(ext)s', '-o', 'pl_thumbnail:[%(webpage_url_domain)s][thumbnail] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(playlist_id,id)s—%(fulltitle|)s.%(ext)s', 'https://www.tiktok.com/@calmnature_/video/7050225950084156677', '-vU']
...
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
```

**Comment by AlttiRi** [comment]
I think if some keys are used as a ID in URLs, they should not be modified.

At least add a modified for that behaviour.

**Comment by AlttiRi** [comment]
It looks that removing the leading and tailing `_`, `-` is a "sanitization".
For me, it's too much.

Maybe it makes sense at least to add `--soft-sanitization` flag?
Trim only space characters and replace only not allowed by file system characters.

**Comment by pukkandan** [comment]
This is caused due to the sanitization of filenames trying to be overly smart and trying to fix for "common patterns". I have considered dropping all these additional rules, but never did for compatibility reasons.

@dirkf What do you think about this? Would you consider simplifying the filename sanitization of youtube-dl to only sanitize invalid filenames (I can make PR)? If you are willing to makes the change too, I can do this without worrying about adding another compatibility option

---

In the mean time, as a workaround, use `some_id` as the "first" field name in each section. yt-dlp sees the `_id` and decides to not apply additional rules on that field. Eg: `%(x_id,title)s` (instead of `%(title)s`), `%(x_id,user,uploader,creator,playlist_title)s` etc

**Comment by dirkf** [comment]
These considerations come to mind:
* do we have a problem of users actually relying on the existing behaviour (I suppose this would become apparent soon enough :-()?
* if not, can the entire filename sanitisation process be reworked to include something like https://github.com/ytdl-org/youtube-dl/pull/29989?

Otherwise I don't see why anything more than `--restrict-filenames` is needed.

**Comment by dirkf** [comment]
Possibly, but both seem to be part of the same steaming heap.

**Comment by pukkandan** [comment]
True, but shortening filepath is not a trivial to implement and I don't see the need to necessarily address the 2 issues together
