### ISSUE TITLE
Allow --no-part to work for fragmented downloads

### ISSUE THREAD

**Issue by MrSmite** [yt-dlp/yt-dlp#2783]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

In my format selection I look for [vcodec=vp9] and sometimes I get a "regular" download and other times I get a fragmented download. My commandline includes **_--no-part_** to force the download to write directly to the output file.

The problem is the fragmented download doesn't respect this **_--no-part_** option and creates a **_ytdl_** file and then a sequentially numbered **_frag_** file for each fragment it downloads. Because I don't keep fragments, it is downladed, merged and deleted immediately before the next fragment file is created.

My request is for **_--no-part_** to work with fragmented downloads and write fragments directly to the output file instead of to a separate file and then merging them.

**Comment by MrSmite** [comment]
> PS: we need to write fragment files anyway when using `-N` since holding multiple fragments in memory is a bad idea

Thanks for that. I hadn't considered the possibility of losing a fragment which would be much harder to resume than a sequential download.

**Comment by reallyuniquename** [comment]
@pukkandan
As of now, is there any yt-dlp option to mitigate this? 

It takes twice as much writes to disk to download fragmented video. First it writes a fragment, then appends it to the output file. So if I download a 10GB YouTube video I have to write 20GB of data (plus another 10GB to merge the formats). This trashes the drive.

Generally I'd do `--downloader dash:ffmpeg` because ffmpeg uses a single file but then I don't get the whole benefit of speed / `sig` calculation.

**Comment by pukkandan** [comment]
> As of now, is there any yt-dlp option to mitigate this?

No
