### ISSUE TITLE
How to dl twitch livestream from the start?

### ISSUE THREAD

**Issue by shadowzoom** [yt-dlp/yt-dlp#3062]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How to dl twitch livestream from the start? Sadlt yt-dlp twitchurlvideo --live-from-start doesn't working
I want to download in real time twitch video stream from beggining. How i can do that?

**Comment by pukkandan** [comment]
As explained in the readme, --live-from-start is only supported for youtube. You can't currently download twitch livestreams from start using yt-dlp

**Comment by KaMyKaSii** [comment]
> As explained in the readme, --live-from-start is only supported for youtube. yt-dlp can't currently download twitch livestreams from start

And why isn't twitch support added? If the VOD of the live in progress is available then wouldn't it be possible to add the functionality to the yt-dlp to continue downloading while the m3u8 of the VOD is being modified with new segments?

**Comment by KaMyKaSii** [comment]
> 

I didn't understand what you meant. Could you explain? My point is that if the streamer has VOD storage enabled, by entering the page "twitch.tv/STREAMER/videos" it is possible to get the partial VOD of the stream in progress.  Wouldn't it be possible to get yt-dlp to start downloading this partial VOD and keep updating the playlist for new segments until the stream actually ends? For example delimiting a 1 minute timeout.

**Comment by KaMyKaSii** [comment]
> @KaMyKaSii
> 
> > If the VOD of the live in progress is available
> 
> Sadly, that's simply not the case on Twitch. The VOD is only ever available **after** a stream over there.

I didn't understand what you meant. Could you explain? My point is that if the streamer has VOD storage enabled, by entering the page "twitch.tv/STREAMER/videos" it is possible to get the partial VOD of the stream in progress. Wouldn't it be possible to get yt-dlp to start downloading this partial VOD and keep updating the playlist for new segments until the stream actually ends? For example delimiting a 1 minute timeout.

**Comment by kescherCode** [comment]
@KaMyKaSii I just tried doing this with several channels, and haven't been successful anywhere - it just shows the current state. It does not start further back than what's broadcasted.

**Comment by KaMyKaSii** [comment]
> @KaMyKaSii I just tried doing this with several channels, and haven't been successful anywhere - it just shows the current state. It does not start further back than what's broadcasted.

There are some possibilities. Maybe all the channels you tried played copyrighted content in the ongoing stream and that caused Twitch to automatically unpublish the VOD according to the [new plataform rules](https://www.dexerto.com/entertainment/twitch-just-made-big-changes-to-its-dmca-ban-process-to-help-streamers-1794948). Or they played copyrighted content on some previous stream and after that the VOD was unpublished and the "Auto Publish VODs" option was turned off and the streamer simply gave up on turning the option back on. [Here](https://youtu.be/Ba01PJdxxYg) is a video showing that partial VODs of the ongoing stream exist, and as I recall they have been there since when I started using Twitch in 2019. I apologize for the app error in playing the partial VOD, but I assure you that at the end of the partial VOD the streamer was making the same move he just made on the ongoing stream.
