### ISSUE TITLE
Disable thumbnails conversion

### ISSUE THREAD

**Issue by FraYoshi** [yt-dlp/yt-dlp#3209]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When embedding thumbnails using `--embed-thumbnail`, they get automatically converted to `.png`
People like me would like to keep them in the original format. (i.e. `webp`), which is compatible with the `.mkv` container when inserted as attachment.

actual output
```
[ThumbnailsConvertor] Converting thumbnail "/path/to/thumbnail.webp" to png
[EmbedThumbnail] ffmpeg: Adding thumbnail to "/path/to/video.mkv"
```

expected output
```
[EmbedThumbnail] ffmpeg: Adding thumbnail to "/path/to/thumbnail.mkv"
```

**Comment by nicolaasjan** [comment]
I would rather not have them as `webp`, because I always save videos as `mp4`.
So I think this should be an option instead of the default.

**Comment by pukkandan** [comment]
@nicolaasjan We can detect the file format and use webp only if it is mkv

**Comment by tripleo1** [comment]
* `--thumbnail-format=webp` ??
* `--(no-)convert-thumbnail` ??

**Comment by pukkandan** [comment]
No option is needed

> We can detect the file format and use webp only if it is mkv

**Comment by tripleo1** [comment]
Fair enough.

**Comment by eladkarako** [comment]
maybe a straight webm would supports a webp as a thumbnail  
(it would make sense). 

but non of the players and decoders I've checked can actually use webp as cover image or generate a thumbnail for the os from it.

as far as I can remember <a href="https://developers.google.com/speed/webp/docs/dwebp"><code>dwebp</code></a> can decompress a webp to png without actually hurting the quality too much (or at all..) maybe it can be used instead of ffmpeg.

for the sake of compatibility it seems like the default might be better kept png.

( matroska explicitly specify only jpg/png for mkv container.
https://www.matroska.org/technical/attachments.html )

**Comment by tealkami** [comment]
Can you please reconsider the `--no-convert-thumbnails` option ?

right now FFMPEG did convert JPEG (`161 KB (165 783 bytes)`) to PNG (`2,12 MB (2 229 202 bytes)`) , just because the thumbnails was not `*.jpg`, but `*.image` file...

Video : `https://www.tiktok.com/@thewarpzone/video/7352220996742499630`
`YT-dlp 2024.03.10` + [ffmpeg-N-114515-gfa110c32b5-win64-gpl](https://github.com/yt-dlp/FFmpeg-Builds/releases/tag/autobuild-2024-03-29-14-10) will pick `*.image` which is JPEG (`[info] Downloading video thumbnail 2 ...`), 
then if it goes into MP4, it will convert it to PNG, and if it goes into MKV, it will merge the `*.image`

If I use `nightly@2024.03.30.232704` + same FFMPEG as above , it will download WEBP (`[info] Downloading video thumbnail origin_cover ...`)
as default non-JPG/PNG converted into MP4, MKV just merge it

`YT-dlp 2024.03.10` 
MKV - `18,4 MB (19 328 171 bytes)` - JPEG `*.image`
MP4 - `20,4 MB (21 462 003 bytes)` - PNG

`nightly@2024.03.30.232704`
MKV - `18,2 MB (19 177 856 bytes)` - WEBP
MP4 - `18,6 MB (19 535 713 bytes)` - PNG

**the Point :**
Yes, it is "fixed" in nightly, but do you think everyone should use nightly builds ? why then there are Stable releases ?
I like to use the stable version, and not bloat my files for no good reason

other reasons I did write here : https://github.com/yt-dlp/yt-dlp/issues/3816#issuecomment-1995442696

**Comment by pukkandan** [comment]
> **the Point :** Yes, it is "fixed" in nightly, but do you think everyone should use nightly builds ? why then there are Stable releases ? 

All fixes first come to nightly and will be available in next stable. That is the whole point.

**Comment by tealkami** [comment]
Hi, I would like to continue here the [_issue_](https://github.com/yt-dlp/yt-dlp/issues/3816#issuecomment-2028664408), even with new ticket people mostly reference older tickets anyway. 
Second: Yesterday (when I did write this comment https://github.com/yt-dlp/yt-dlp/issues/3209#issuecomment-2028650082 ) I had/have personal issues (distress/stress) that I couldn't even think straight, but now I know what I want to state/explain._(I even knew that I am missing point when I was finishing that comment, but my mind was in dark place/couldn't concentrate properly, I did send it anyway because I spend lot of time testing and probably wouldn't send it later)_

and I know about the combination of `--write-thumbnail` `--embed-thumbnail`, which is not the point.

-----

### The proper point :
> 
> > `--no-convert-thumbnails` could act as .. "if it is not compatible, no merge, keep the thumbnail file"
> 
> This is a reasonable request, but is not what this original issue was about (though related). Please feel free to open a new issue for further discussion

For me yt-dlp is a software which should ONLY download what I want , and converting is something secondary as an option to nice have, that is the thing I don't like. If i want edit/convert a file I will use Handbrake/Avidemux/Gimp/Paint/other
 
It is like you have video player, and everytime without you knowing it would convert subtitles or whole video/audio, you have expectation that it will only read the file, not edit/change/remove it. That's why it made me unease, when I find out it does convert thumbnail without you knowing, and you can't turn it off neither, from my point of view that should be an opt-in, not opt-out feature. 
I understand exactly why the auto converstion exist, but nowhere in readme file is written that it does convert thumbnails as default for non-MKV containers, and I did find about it only because of TikTok error...

If your point of view is **opt-out**, I would rather have a option as `--no-convert-thumbnails` which would do `this doesn't work, so no thumbnail at all, and after finishing it would inform me that thumbnails were not included`
or something like `--no-convert-thumbnails-keep` would act like "if it is not compatible, no merge, keep the thumbnail file externally"

**Comment by pukkandan** [comment]
As I said in the other issue:

> This is a reasonable feature request, but is not what this original issue was about (though related). Please feel free to open a new issue for further discussion
