### ISSUE TITLE
[Feature/Question] Supply A URL For Date After

### ISSUE THREAD

**Issue by seniorm0ment** [yt-dlp/yt-dlp#321]
Is it possible to supply a URL for date after feature?
For example, if I want to say "download everything uploaded after this video, including this video" and can just provide the URL?
If not, could this be introduced? It would be a lot easier than figuring out dates, and will work better on sites that only provide generalized dates "10 months ago" (which could mean multiple videos).

**Comment by pukkandan** [comment]
You can get the upload date using `yt-dlp --print upload_date URL`. Then use `--date-after` with that date

> and will work better on sites that only provide generalized dates "10 months ago" (which could mean multiple videos).

No, it won't, since we have no way of knowing if the playlist is sorted by date

---

If you know that the playlist is sorted by date, add the video URL to `archivefile` using `yt-dlp --download-archive archivefile --force-write-archive -s URL`. Then use `--download-archive archivefile --break-on-existing` when downloading the playlist. You may also need to use `--playlist-reverse` depending on whether the sorting is ascending/descending

Another way to do the same (if you dont wanna use archive) is to just use `--match-filter "id!=VIDEO_ID" --break-on-reject`

**Comment by pukkandan** [comment]
hey @seniorm0ment does any of these methods solve your issue?

**Comment by seniorm0ment** [comment]
sorry i havent had a chance to look  at it yet

**Comment by pukkandan** [comment]
I'm closing this for now. If you find a use case where none of the above solutions work, then it can be reopened
