### ISSUE TITLE
Can the *.info.json for playlists include the IDs of the videos in the playlist?

### ISSUE THREAD

**Issue by danielyli** [yt-dlp/yt-dlp#3433]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The `*.info.json` file of playlists don’t seem to have the video IDs themselves:

```json
{
  "thumbnails": [...],
  "tags": [],
  "view_count": 79,
  "modified_date": "20220414",
  "playlist_count": 3,
  "id": "OLAK5uy_lE9iXQC55uIiizZdXDV5scSju-e-AfZwM",
  "title": "Beethoven: Piano Sonata No. 14 in C-Sharp Minor, Op. 27, No. 2 \"Moonlight\"",
  "description": "",
  "_type": "playlist",
  "webpage_url": "https://www.youtube.com/playlist?list=OLAK5uy_lE9iXQC55uIiizZdXDV5scSju-e-AfZwM",
  "webpage_url_basename": "playlist",
  "webpage_url_domain": "youtube.com",
  "extractor": "youtube:tab",
  "extractor_key": "YoutubeTab",
  "epoch": 1649979413
}
```

Would it be possible to add a new key, `_videos`, to the output? For example:

```json
"_videos": [
  {
    "id": "KjgSyYhuw3E",
    "url": "https://www.youtube.com/watch?v=KjgSyYhuw3E"
  },
  {
    "id": "JcZdns6OPHE",
    "url": "https://www.youtube.com/watch?v=JcZdns6OPHE"
  },
  {
    "id": "Hj6eVjRqs",
    "url": "https://www.youtube.com/watch?v=C-Hj6eVjRqs"
  }
]
```

**Comment by pukkandan** [comment]
--no-clean-info-json

**Comment by danielyli** [comment]
Thanks. That works. However, I’m wondering why the video list is considered private data:

```
       --clean-info-json
              Remove some private fields such as filenames from the infojson.
              Note that it could still contain some personal information
              (default)

       --no-clean-info-json
              Write all fields to the infojson
```

It’s not intuitive that the videos of a playlist are considered “private fields”. Also, I can imagine use cases where the user would want the playlist’s infojson to have the list of videos but not actual private fields.

**Comment by pukkandan** [comment]
The word private is used here in the programming sense (roughly speaking, fields that third-parties shouldn't depend on), not in the sense that the fields leak private information of the user. Perhaps this documentation can be improved, but I don't know how else to describe these fields other than "private"

It can be argued that the `entries` should be considered private fields or not. But there are a few reasons why I decided to do so:
1. The json can get very large for large playlists
2. This info is redundant since you are probably also writing video infojson
3. When using `--playlist-end`, `--download-archive` and similar options that blocks yt-dlp from extracting all items of a playlist, the `entries` field don't accurately mirror all the videos in the playlist
4. If you `--load-info-json` a playlist, you expect yt-dlp to try and download the current state of the playlist. If `entries` was not considered as a private field, only the videos listed in it can be downloaded (You can force this behavior currently using `--no-clean-info-json`)
