### ISSUE TITLE
Understanding the default value of -S in the context of audio

### ISSUE THREAD

**Issue by emphoeller** [yt-dlp/yt-dlp#3818]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have read some issues about having yt-dlp automatically select the “best” video format (#458, #1232, #2432, #2469), but I couldn’t find similar information on audio formats. In the default value of `-S`, `lang,quality,res,fps,hdr:12,codec:vp9.2,size,br,asr,proto,ext,hasaud,source,id`, the first entry that is relevant for audio-only formats (ignoring `lang` and `quality`) seems to be `codec:vp9.2`, which I’m guessing is equivalent to `vcodec:vp9.2,acodec` (the documentation does not touch on this special case). So the audio codec is more important than the bitrate (`br`) or the audio sampling rate (`asr`), which I thought to be the most important metrics for audio files. But even the file size is considered before them.

I understand that better codecs can compress equal-quality audio better and thus yield lower bitrates and file sizes (at least [I have read such for videos](https://github.com/yt-dlp/yt-dlp/issues/1232#issuecomment-939635345)). Still, for videos, the resolution is listed *before* the codec; and the same goes for the framerate (the equivalent of the sampling rate). Additionally, the audio files of the highest quality might not even be offered in the codec that yt-dlp considers best.

So then what am I missing? Why is the default value the way it is?

**Comment by pukkandan** [comment]
> which I’m guessing is equivalent to vcodec:vp9.2,acodec

Correct

> So the audio codec is more important than the bitrate (`br`) or the audio sampling rate (`asr`),

Yes

> But even the file size is considered before them.

You mean "after"?

> Still, for videos, the resolution is listed before the codec;

There is obv no equivalent of resolution for audio. If we know some audio is better than others we instead set the `quality` accordingly (eg: youtube)

> and the same goes for the framerate (the equivalent of the sampling rate).

While they are similar in a technical sense, I believe the samplerate is not nearly as important as framerate as a measure of quality. If you think otherwise, we can discuss (not that I remember ever seeing a service offer audio in different sample rates)

> Additionally, the audio files of the highest quality might not even be offered in the codec that yt-dlp considers best.

How does that matter?

**Comment by emphoeller** [comment]
> > But even the file size is considered before them [bitrate and audio sampling rate].
> 
> You mean "after"?

Does `size,br,asr` not mean “size before bitrate before audio sampling rate”?

> > Additionally, the audio files of the highest quality might not even be offered in the codec that yt-dlp considers best.
> 
> How does that matter?

What I’m saying is that yt-dlp might neglect the best audio files because the platform uses a codec for them that yt-dlp considers worse.

> If we know some audio is better than others we instead set the `quality` accordingly (eg: youtube)

However, formats with worse audio can be assigned a higher quality if they have good video. Because of this, for YouTube, the file with the best audio is still downloaded *only because* yt-dlp always tries to download the best audio-only file – and on YouTube, the best audio is in audio-only files. I can see this fall apart in cases where the best audio is in a file with sub-optimal video. (For those cases, it might be necessary to split `quality` into `video_quality` and `audio_quality` and specify separate sorting priorities for `bestvideo` and `bestaudio`.) Is this only not accounted for because there are no known sites to do this?

(Also, what’s up with yt-dlp reporting audio bitrates of 0 for certain formats with audio, e.g. format 22 of `ZBgJJPZjg2k`? Should I open an issue for that?)

**Comment by pukkandan** [comment]
I was talking about comparing audio against audio. Merged formats cannot be reliably compared against audio-only formats. See https://github.com/yt-dlp/yt-dlp/issues/979#issuecomment-919629354

> > > But even the file size is considered before them [bitrate and audio sampling rate].
> > 
> > 
> > You mean "after"?
> 
> Does `size,br,asr` not mean “size before bitrate before audio sampling rate”?

You are right, I misunderstood. As I mentioned, I haven't actually seen any website that serves audio in multiple asr, but ig it makes sense to move it's priority atleast above size

**Comment by emphoeller** [comment]
> Merged formats cannot be reliably compared against audio-only formats.

Too bad I guess. Thanks for all the answers!

**Comment by chrizilla** [comment]
> > _Still, for videos, the resolution is listed before the codec;_
> 
> _There is obv no equivalent of resolution for audio._

The nearest equivalent to video resolution is audio sample rate.


> > _and the same goes for the framerate (the equivalent of the sampling rate)._

Video framerate and audio sampling rate are not equivalents but [false friends](https://en.wikipedia.org/wiki/False_friend).

 
> _While they are similar in a technical sense,_

They are similar only in a linguistic sense, not in a technical sense. The video framerate affects the smoothness of the video motion, i.e. the visual trick of perceiving motion in a series of still images. Since video is composed of images and audio is not composed of any equivalent of still images, it is obvious that there is no and cannot be an audio equivalent for the video framerate.

As said above, the video resolution could be considered the nearest comparison.


> _I believe the samplerate is not nearly as important as framerate as a measure of quality. If you think otherwise, we can discuss_ 

It's the other way round. The video framerate affects the quality of the appearance of the video motion, but it's not trivial to say how the framerate affects the quality of a video still image. This depends heavily on the codec, the settings, the source material, etc. On the other hand the audio sample rate heavily affects the audio quality. Have you ever listened to music with a low sample rate ?

**Comment by pukkandan** [comment]
Do you have any real example where sorting by asr would be better than the current defaults?

**Comment by chrizilla** [comment]
> Do you have any real example where sorting by asr would be better than the current defaults? If not, further discussion seem pointless tbh.

I was not advocating for a specific change in the sort order. I just wanted to help, because some basics got mixed up.

I find it difficult to say whether asr or size/br (they are related) is more important, since a low value for either one degrades quality. It's like for a JPG file: low resolution or small file size both degrade the image quality. It's a bit like comparing apples to oranges.

**Comment by pukkandan** [comment]
> I find it difficult to say whether asr or size/br (they are related) is more important, since a low value for either one degrades quality. It's like for a JPG file: low resolution or small file size both degrade the image quality. It's a bit like comparing apples to oranges or asking if the lung or the heart is more important to the human body ...

Such is the difficulty of setting a default sort order. Hence why I always ask for practical examples. Our objective is to get a default that works in most cases, and don't really care much about the technical details.

**Comment by chrizilla** [comment]
Ok then let's just leave it at that, as [your thoughts on video quality](https://github.com/yt-dlp/yt-dlp/issues/1232#issuecomment-939635345) equally apply to audio quality.
