### ISSUE TITLE
why is vp9 higher in format sorting then h265

### ISSUE THREAD

**Issue by MrRawes** [yt-dlp/yt-dlp#3913]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

the fornat sorting field vcodec sorts av01 > vp9.2 > vp9 > h265 > h264 > vp8 > h263 > theora > other
~~why is vp9 sorted higher them h265 despite h265 being more compression efficient then vp9~~

**Comment by pukkandan** [comment]
Do you know any service that offers both these formats? Otherwise this discussion is pointless

**Comment by Ashish0804** [comment]
Hotstar offers both afair.
But still this discussion is useless. 
It is like saying why is the company that makes iPhone called Apple and not orange when everyone in my village loves Oranges.

It is widely accepted for most content vp9 is "better" than h265.
Do not use random no name shitclick sites for info.
They want to sell u their own product and proly didn't pay devs enough to improve their vp9 encoder so that is y the article.
