### ISSUE TITLE
Format selection: Can I specify different filters for "normal" and "vertical" videos?

### ISSUE THREAD

**Issue by Markus-N** [yt-dlp/yt-dlp#4117]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

I'm using yt-dlp 2022.05.18 on Arch Linux.

I'd like to download a youtube playlist that has some vertical videos in between. I also like to restrict the disk space used, so I'd like to use `-f "bestvideo[height<=720]+bestaudio/best"` for normal, but `-f "bestvideo[width<=720]+bestaudio/best"` for vertical videos. Kind of `shorter_edge<=720`.  
Most of the vertical videos in that playlist appear to be 720x1280, and I'd like to avoid having them downloaded in only 406x720.

I've looked at the README (especially the FORMAT SELECTION section), but I have to admit that I'm confused about all those options. Can this `shorter_edge<=720` be achieved somehow with the currently available options? 

### Verbose log

```shell
n/a
```

**Comment by pukkandan** [comment]
Not quite, but `-f "(bv[height<=720][width>720]/bv[width<=720])+ba/b"` should do what you want

**Comment by dirkf** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/30737

**Comment by Markus-N** [comment]
> There is no built-in mechanism to filter by "shorter side", but `-f "(bv[height<=720][width>720]/bv[width<=720])+ba/b"` should do what you want

Yes, it worked. thank you very much. Maybe this is worth to be added to the examples.

**Comment by pukkandan** [comment]
The examples need a rewrite anyway. A lot of it was written with someone coming from youtube-dl in mind, and so emphasizes the different way of doing selection for yt-dlp, rather than being newbie friendly. I am working on completely rewriting the format selection code. I'll rewrite the examples when that is done - and will keep this in mind when I do (or maybe I can add an `aspect_ratio` selector instead as suggested in https://github.com/ytdl-org/youtube-dl/issues/30737)
