### ISSUE TITLE
[Site Request] [YouTube] Save Livechat on running Livestreams

### ISSUE THREAD

**Issue by Lytexx** [yt-dlp/yt-dlp#413]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.06.09**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I mainly use yt-dlp for Livestreams that are known to be privated after they end
so having the option to save the Livechat while the stream is still live would be amazing

also if possible having the option to start saving the chat on scheduled Livestreams would be nice too but that's not necessary

**Comment by pukkandan** [comment]
I doubt this is possible with the current implementation. @siikamiika should know more

**Comment by siikamiika** [comment]
Real time live chat uses a different endpoint (`get_live_chat` instead of `get_live_chat_replay`) but otherwise the format is quite similar. I might have some time to look into this during the weekend or next week

**Comment by siikamiika** [comment]
Ok so now I have this https://github.com/siikamiika/yt-dlc/commit/bc76a019cbc23853e38024d851479bf1c7259fac

Some context for the timestamp/offset parser from my other project https://github.com/siikamiika/youtube-live-archive/blob/2e3187c9a19c95e2fdbc908018f7b431e4d3a05c/public/js/video/live-chat/YoutubeLiveChatParser.js (also, it would be nice to get the live video start timestamp somewhere instead of using `time.time()` but I didn't find a way yet.)

Anyway I encountered a problem. yt-dlp will attempt to download the entire live chat before starting to download the video itself. This would require some threading to be supported properly, but you can also work around it as a user by starting two instances. What should we do about it? @pukkandan

**Comment by pukkandan** [comment]
> This would require some threading to be supported properly, but you can also work around it as a user by starting two instances.

Multiple instances is the only way right now since multi-threaded downloads would require significant changes to the core program. While I am not against adding such a feature in the future, it definitely is not within the scope of this issue

**Comment by siikamiika** [comment]
Alright, I guess that simplifies my part. I'll create a PR
