### ISSUE TITLE
Are lazy extractors worth it?

### ISSUE THREAD

**Issue by fstirlitz** [yt-dlp/yt-dlp#4190]
<details> <summary> Checklist </summary>

### Checklist

- I'm asking a question and **not** reporting a bug or requesting a feature
- I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

</details>

I have been running yt-dlp under Python 3.10 (Debian testing) for some time, sometimes applying local hotfixes. Some of the fixes require updating the URL-matching regex, and those have to be additionally propagated to the lazy extractor stub class. But an easier option is to simply delete the `lazy_extractors.py` file. I have noticed virtually zero slowdown due to this, despite this being a relatively old laptop (from 2010); most extraction latency seems to come from HTTP requests made after the URL is already matched. I wonder if this is because of performance improvements that 3.10 brought.

I wonder how viable it would be to just remove them; I imagine they are something of a maintenance burden and they complicate the codebase considerably. Are they worth the trouble? Have we got any data on how much speed is gained by enabling lazy extractors under different OSes and Python versions?

(Variables we might need to control for: kernel/distro, file system where the program is stored, Python version, amount of RAM, SSD vs HDD, cold start vs populated disk or bytecode caches.)

If there are some slowdowns noticeable only under older Python versions, perhaps we can remove lazy extractors anyway. This is another way we could nudge people to upgrade; even if we *support* older versions, we don’t necessarily have to *tune* for them.

**Comment by gamer191** [comment]
I'm pretty sure that the lazy_extractors.py file is auto generated, because I can't find it anywhere in the git repo, and I can find a file named [lazy_extractors.py](https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/make_lazy_extractors.py). I don't know anything about it though, so I could be wrong.

It's also mentioned in the [.gitignore file](https://github.com/yt-dlp/yt-dlp/blob/master/.gitignore#L114)

**Comment by pukkandan** [comment]
> I have been running yt-dlp under Python 3.10 (Debian testing) for some time, sometimes applying local hotfixes. Some of the fixes require updating the URL-matching regex, and those have to be additionally propagated to the lazy extractor stub class. But an easier option is to simply delete the lazy_extractors.py file.

If you plan on modifying the extractors, it makes sense not to have lazy extraction. Are you installing with PIP and them applying hotfixes? Why not just run from source in that case? (which doesn't have lazy-extractors enabled)

> I wonder how viable it would be to just remove them; I imagine they are something of a maintenance burden and they complicate the codebase considerably. Are they worth the trouble? Have we got any data on how much speed is gained by enabling lazy extractors under different OSes and Python versions?

Not really. The entire implementation of the feature is in `make_lazy_extractors` and `lazy_load_template`. Except for [this one tiny caveat](https://github.com/yt-dlp/yt-dlp/blob/c043c246251da815c99f8c779194fcdef9ef7a58/yt_dlp/extractor/common.py#L431-L433), the rest of the code doesn't have to do anything. The current implementation using metaclasses is also quite stable. So there really is no maintenance overhead - and I don't see any point in removing it even if the the benefits are now minimal

> Have we got any data on how much speed is gained by enabling lazy extractors under different OSes and Python versions?

When I last worked on the feature, I had noticed significant improvement in startup time (I don't think Ive tested on 3.10). Even so, under many use-cases, it won't factor much into the total time taken because, as you said, the download times far outweigh it. But it would make a difference when `--simulate` is in effect

**Comment by pukkandan** [comment]
btw, You can force-disable lazy extraction by setting the environment variable `YTDLP_NO_LAZY_EXTRACTORS=1` (yes, this is undocumented)

**Comment by pukkandan** [comment]
Timings (best of 5 with pycache) on Windows 11 Py 10.4, running `yt-dlp.cmd`

Command|Lazy|Time
---|---|---
`yt-dlp`|✔️|0.5 s
`yt-dlp`|❌|0.8 s
`yt-dlp -s test:youtube`|✔️|2.1 s
`yt-dlp -s test:youtube`|❌|2.8 s

**Comment by Ashish0804** [comment]
No

**Comment by Ashish0804** [comment]
> Timings (best of 5 with pycache) on Windows 11 Py 10.4, running `yt-dlp.cmd`
> 
> Command	Lazy	Time
> `yt-dlp`	✔️	0.5 s
> `yt-dlp`	❌	0.8 s
> `yt-dlp -s test:youtube`	✔️	2.1 s
> `yt-dlp -s test:youtube`	❌	2.8 s

What is the exact parameters and command u ran for this??

for me
time yt-dlp = 0.2 s
time yt-dlp -s test:youtube = 1.38 s

this dlp was installed using homebrew. Python 3.9.12. 

Any "noticeable" improvement will come from a faster ssd rather than some cool haxor code tricks, hence my previous answer, "NO".

**Comment by pukkandan** [comment]
Those are the exact commands I ran. My measurements are on an HDD

**Comment by pukkandan** [comment]
Though, I'd think the % improvement would be higher on an SSD

> time yt-dlp = 0.2 s
time yt-dlp -s test:youtube = 1.38 s

And without lazy extractors?

PS: I only posted the timings just because. It was not meant to try and justify lazy extractors. If we were discussing the addition of a new feature, profiling makes sense. But I've already explained in https://github.com/yt-dlp/yt-dlp/issues/4190#issuecomment-1166488205 why there is no point in removing the feature even for minimal benefit

**Comment by Ashish0804** [comment]
>And without lazy extractors?

I have no idea how to test this or if lazy extractors are enabled by default or not.

**Comment by veganomy** [comment]
I apologise for waking a dead issue but... Does lazy extract improve "play in mpv" startup times ? The one where mpv uses yt-dlp to play stuff from web ?

I believe NewPipe can initial load way faster, almost like 3-4 seconds. Thinking it's possible for yt-dlp too.

**Comment by bashonly** [comment]
> I apologise for waking a dead issue but... Does lazy extract improve "play in mpv" startup times ? The one where mpv uses yt-dlp to play stuff from web ?

mpv just runs yt-dlp as a subprocess under the hood, so if lazy extractors improve yt-dlp startup time for you, then they will improve mpv w/URL startup time too.

> I believe NewPipe can initial load way faster, almost like 3-4 seconds. Thinking it's possible for yt-dlp too.

Apples to oranges. NewPIpe is written in a different language with a strong focus on YouTube (and support for only 4 other sites).

**Comment by veganomy** [comment]
Tq bashonly. I don't see documentation on how to enable it, other than rebuilding binaries with `devscripts/make_lazy_extractors.py`.

Are there any other ways to speed up ? Asking LLMs suggest doing : 
```
ytdl-raw-options=no-check-certificate=,no-playlist=,force-ipv4=,extractor-args="youtube:player_skip=webpage,configs,js;player_client=ios"
```

**Comment by bashonly** [comment]
> Tq bashonly. I don't see documentation on how to enable it, other than rebuilding binaries with `devscripts/make_lazy_extractors.py`.

If you're using one of the official binaries (from [here](https://github.com/yt-dlp/yt-dlp/releases)) or the official PyPI package (e.g. you installed with `pip`, `pipx`, `uv`, etc), then lazy extractors are already generated, included and enabled by default.

> Are there any other ways to speed up ? Asking LLMs suggest doing : 
> ```
> ytdl-raw-options=no-check-certificate=,no-playlist=,force-ipv4=,extractor-> args="youtube:player_skip=webpage,configs,js;player_client=ios"
> ```

The LLM's suggestion is a good way to completely break yt-dlp's Youtube support. Do not do what the chatbot says. The chatbots are typically very, very stupid when it comes to yt-dlp matters. There's not really much you can do, TBH.

**Comment by veganomy** [comment]
You're right. Skipping SSL verification is a bad idea. `no-playlist` & `force-ipv4` didn't improve anything. `ios` client seems to be a hit and miss. The only thing that reducing initialisation a tad bit, is skipping js & webpage.
