### ISSUE TITLE
[Question] How to download a Youtube Playlist concurrently 

### ISSUE THREAD

**Issue by kk-Chiron** [yt-dlp/yt-dlp#425]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Basically the title. 
How can I download a YouTube playlist concurrently/multithreaded? I've tried a lot around, but it's always doing single downloads which is kinda wasted for people with a greater bandwidth. 

Is there a way to archive this? (preferably with something like aria2c)

**Comment by pukkandan** [comment]
Not possible

**Comment by radiohazard-dev** [comment]
This is more of a shell question than one about yt-dlp. Luckily, there's lots of ways to run commands in parallel in lots of shells.

In Linux, you can use `xargs` to run a command on a line-separated stream of input. In conjunction with `--get-id`, you can write something like this:
```bash
yt-dlp --get-id "$PLAYLIST_URL" \
  | xargs -I '{}' -P 5 yt-dlp 'https://youtube.com/watch?v={}'
```
which will download five videos at a time in parallel. 

In Powershell, running parallel tasks becomes a bit more complicated, but I ran into this same problem this morning and made [this function](https://gist.github.com/radiohazard-dev/5cbefc57ab4ca8d6b7bcde77cd3e0d6e) for using Powershell Jobs to do the same thing (heads up: uses aria2c due to an oversight of mine.) 
Hope that answers your question. 😄

**Comment by pukkandan** [comment]
ah, ofc there are various ways to do it with wrappers and scripts. I was only thinking of doing it natively

**Comment by expenses** [comment]
I personally think it makes a lot of sense to have the ability to run multiple video downloads concurrently inside yt-dlp. This way http connections can be reused from the connection pool. There's already an option for concurrent downloads within a DASH stream:

```
    -N, --concurrent-fragments N    Number of fragments of a dash/hlsnative
                                    video that should be downloaded concurrently
```

**Comment by bashonly** [comment]
@expenses see #1918
