### ISSUE TITLE
Not Catching Subtitles

### ISSUE THREAD

**Issue by nochlab1** [yt-dlp/yt-dlp#512]
I am trying to download subtitles for a video and using --list-subs  it tells me no subtitles available when there is,
if i open the master m3u8 files i see the subtitle links and i can even download them but here its not finding them

"[generic] master: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
WARNING: [generic] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
master has no subtitles"

**Comment by fstirlitz** [comment]
> Be sure to call yt-dlp with the --verbose flag and **include its complete output**.

**Comment by pukkandan** [comment]
From the very little info you have provided, we can only assume that the issue will be fixed by #515 and will hence be closed with it

### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

If the issue persists after next release, create a new issue using the correct template with all necessary information including the entire `--verbose` output

**Comment by nochlab1** [comment]
Sorry for not being more specific but the issue was fixed by #515 thanks so much
