### ISSUE TITLE
thisav extractor error

### ISSUE THREAD

**Issue by VgGuw** [yt-dlp/yt-dlp#5288]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

The thisav.com extractor doesn't work. It would be nice if you can download videos from an account link as well if possible. Thank you.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.thisav.com/video/630770/4riley-reid.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.15.65-051565-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [ThisAV] Extracting URL: https://www.thisav.com/video/630770/4riley-reid.html
[ThisAV] 630770: Downloading webpage
[ThisAV] 630770: Downloading MPD manifest
ERROR: 630770: An extractor error has occurred. (caused by KeyError('sourceURL')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/a/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/home/a/.local/lib/python3.8/site-packages/yt_dlp/extractor/thisav.py", line 46, in _real_extract
    entries = self._parse_html5_media_entries(url, webpage, video_id)
  File "/home/a/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 3288, in _parse_html5_media_entries
    is_plain_url, formats = _media_formats(src, media_type, f)
  File "/home/a/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 3241, in _media_formats
    formats = self._extract_mpd_formats(
  File "/home/a/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 2713, in _extract_mpd_formats
    fmts, subs = self._extract_mpd_formats_and_subtitles(*args, **kwargs)
  File "/home/a/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 2736, in _extract_mpd_formats_and_subtitles
    return self._parse_mpd_formats_and_subtitles(
  File "/home/a/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 2922, in _parse_mpd_formats_and_subtitles
    representation_ms_info = extract_multisegment_info(representation, adaption_set_ms_info)
  File "/home/a/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 2806, in extract_multisegment_info
    extract_Initialization(segment_list)
  File "/home/a/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 2801, in extract_Initialization
    ms_info['initialization_url'] = initialization.attrib['sourceURL']
KeyError: 'sourceURL'
```

**Comment by dirkf** [comment]
The MPD (https://vs37.thisav.com/dash/Nq6MsRYyWmPQLa1MLjq18g,1666237784/630770_high.mpd in my test) has a `BaseURL` but no URLs in the multi-segment data, either in `Initialization` or in the `SegmentURL`s: these contain ranges only:
```xml
 <Period duration="PT0H34M17.200S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="25" par="16:9" lang="und">
   <ContentComponent id="1" contentType="video" />
   <ContentComponent id="2" contentType="audio" />
   <Representation id="1" mimeType="video/mp4" codecs="avc3.64001F,mp4a.40.2" width="1280" height="720" frameRate="25" sar="1:1" startWithSAP="0" bandwidth="1339129">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>630770_high_dashinit.mp4</BaseURL>
    <SegmentList timescale="1000" duration="3000">
     <Initialization range="0-1399"/>
      <SegmentURL mediaRange="1400-936554" indexRange="1400-1443"/>
      <SegmentURL mediaRange="936555-1652529" indexRange="936555-936598"/>
      ...
```
In yt-dl, making the URL fields in the above multi-segment data optional fixes the problem, by causing the `BaseURL` (https://vs37.thisav.com/dash/9qPf4J4XSyMsY62smDXeEw,1666240377/630770_high_dashinit.mp4) to be used directly. Since we want the whole video, this is fine. For an application that wanted to navigate to a particular part of the video, the multi-segement range data would be useful.

Incidentally, NSFW.

**Comment by longsack** [comment]
Any chance of his issue being fixed in the future, or is the site still supported?

yt-dlp -vU "https://thisav.com/en/oreco-484"
[debug] Command-line config: ['-vU', 'https://thisav.com/en/oreco-484']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip)
[debug] Python 3.8.2 (CPython x86_64 64bit) - Linux-4.19.0-24-amd64-x86_64-with-glibc2.28 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.28)
[debug] exe versions: ffmpeg 4.1.11-0, ffprobe 4.1.11-0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.27.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
yt-dlp is up to date (stable@2023.10.07)
[generic] Extracting URL: https://thisav.com/en/oreco-484
[generic] oreco-484: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] oreco-484: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://thisav.com/en/oreco-484
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 2575, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://thisav.com/en/oreco-484

**Comment by bashonly** [comment]
MPD `sourceURL` issue will be tracked in #8269

@longsack it appears that the site's URL format has changed and the URL you are passing is no longer matched by yt-dlp's extractor for this site. This extractor will need fixes beyond the MPD issue. It will be fixed whenever a dev is willing/able to work on it

**Comment by longsack** [comment]
Bashonly I understand... sorry if I went about asking the question the wrong way or in the wrong format.

**Comment by dirkf** [comment]
There is an upstream solution, subject to QA: https://github.com/ytdl-org/youtube-dl/issues/32595#issuecomment-1761209532

**Comment by bashonly** [comment]
Piracy site
