### ISSUE TITLE
Cookies from Browser (Firefox MacOS)

### ISSUE THREAD

**Issue by artcs** [yt-dlp/yt-dlp#550]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

The `--cookies-from-browser` option does not work as expected on Firefox for MacOS (checked with FF90 and FF78ESR on MacOS 10.13/10.9). The output always contains `[Cookies] Extracted 0 cookies from firefox`.
It seems, that `cookies.sqlite` dosen't contain any cookies. Also checked with sqlite3 on command line; table `moz_cookies` exists but there are no entries at all. The file is touched once at FF startup and gets no further updates. Is there any Firefox setting I have to enable to write out cookies to `cookies.sqlite`? Exporting cookies with the cookies.txt extension shows a lot of cookies though.

**Comment by pukkandan** [comment]
Give the full verbose output. 

Not everything is a question. If something isnt working as it should, you should be opening a bug report and using the appropriate template

@mbway should know more

**Comment by artcs** [comment]
Example verbose output:
```
$ yt-dlp --verbose --cookies-from-browser firefox https://www.youtube.com/watch?v=NIhgNHSti3M
[debug] Command-line config: ['--verbose', '--cookies-from-browser', 'firefox', 'https://www.youtube.com/watch?v=NIhgNHSti3M']
[Cookies] Extracting cookies from firefox
[debug] extracting from: "/Users/artcs/Library/Application Support/Firefox/Profiles/ajrhol2v.default/cookies.sqlite"
[Cookies] Extracted 0 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 
[debug] Python version 3.9.6 (CPython 64bit) - macOS-10.13.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=NIhgNHSti3M
[youtube] NIhgNHSti3M: Downloading webpage
...
```
I placed this as a question, because it seems to be an issue with Firefox not updating `cookies.sqlite`, not a yt-dlp bug...

**Comment by pukkandan** [comment]
> I placed this as a question, because it seems to be an issue with Firefox not updating cookies.sqlite, not a yt-dlp bug...

Gotcha. In either case, the verbose will be helpfull in debugging. Can you confirm that `ajrhol2v.default` is in fact the correct profile that you are using in the browser?

I do not have access to a Mac, so will have to wait for @mbway to test and get back on this

**Comment by artcs** [comment]
Yes, the profile is correct.

**Comment by mbway** [comment]
I don't know what's going on here. I don't have a mac but I used [this](https://github.com/foxlet/macOS-Simple-KVM) to set up an OSX Catalina VM and I just installed the latest firefox (90.0.2) in this fresh VM, went to a few websites then examined `~/Library/Application Support/Firefox/Profiles/<randomhash>.default-release/cookies.sqlite` and the cookies were present.

If you run
```
find "~/Library/Application Support/Firefox" -name '*cookies*' -print -exec sqlite3 {} 'SELECT COUNT(*) FROM moz_cookies' \;
```
what is the output? and do any of those files contain your cookies? It could be that yt-dlp is just choosing the wrong database for some reason.

I would also suggest using a tool like dtrace while using firefox to see what files are written to as cookies are created, but it seems like [it's a nightmare to get working](https://poweruser.blog/using-dtrace-with-sip-enabled-3826a352e64b) although it would be very useful if you want to give it a go. If you do I think the command would be something like: `dtruss -t open /Applications/Firefox.app/Contents/MacOS/firefox-bin` (and `openat` might be the type you want rather than `open`)

**Comment by artcs** [comment]
Thank you for having a look.

```
$ find "/Users/artcs/Library/Application Support/Firefox" -name '*cookies*' -print -exec sqlite3 {} 'SELECT COUNT(*) FROM moz_cookies' \;
/Users/artcs/Library/Application Support/Firefox/Profiles/ajrhol2v.default/cookies.sqlite
Error: database is locked
/Users/artcs/Library/Application Support/Firefox/Profiles/ajrhol2v.default/cookies.sqlite-wal
Error: no such table: moz_cookies
/Users/artcs/Library/Application Support/Firefox/Profiles/c92yp2ly.ffESR/cookies.sqlite
0
/Users/artcs/Library/Application Support/Firefox/Profiles/dgpdsxvl.ff57/cookies.sqlite
0
```

If I copy the databasefile so it is not locked, there are still zero cookies stored in it. I also checked all files in `~/Library/Caches/Firefox` to no avail. This is with FF90.0.2 as well as FF 78.12.0ESR. UserContext Containers are disabled.
dtrace/dtruss requires me to reboot into recovery mode and disable sip, that's beyond my scope…
Maybe someone else can reproduce this and help out there.
Or someone with more Firefox knowledge has an idea, what's going on.

I tried on three different Macs, strange that it's working in your VM. If it is working for others with a real Mac, feel free to close this issue. Just wanted to let you know.

**Comment by mbway** [comment]
- if the database is locked then can you close firefox and try again. it probably won't make a difference but it might not have flushed the writes to the disk?
- I found out that if you go `help > more troubleshooting information` in firefox you can see your profile directory to make absolutely sure that it is the `ajrhol2v.default` directory
- does the cookie extraction work for any chromium-based browsers on your machine? both use sqlite databases (with different schemas) so that might help indicate if something is wrong there
- are you sure you haven't configured firefox to clear cookies on exit, or are using an extension which might be clearing cookies or doing something strange?

I downloaded the firefox source code and had a look around to double check. The only non-test mentions of `moz_cookies` is in `netwerk/cookie/CookiePersistentStorage.cpp`. Unlike chromium, the cookie storage mechanism seems to be the same on all platforms. So the cookies aren't being stored in some special Mac-only place. It has to be in a `cookies.sqlite` file somewhere.

**Comment by artcs** [comment]
- It is working well on chromium and safari
- Profile is correct, the database is locked while FF is running, as expected
- There is no `cookies.sqlite` file outside the Profiles folder (checked with `sudo find / -name '*cookies.sqlite*'`)
- I have indeed configured FF to clear cookies on exit. If I turn it off, only persistent cookies are written to `cookies.sqlite` and this only when I quit FF. Session cookies never appear in the database. The file is only changed on quit and never get's touched while FF is running. With chromium all cookies (including session cookies) are found correctly while chromium is running.

**Comment by mbway** [comment]
That isn't something I considered, but makes sense. For youtube which is the only website I considered while developing this feature, the only required cookies are those which authenticate you, which persist between sessions.

It would be perfectly valid for firefox to only keep session/non-persistent cookies in memory and never let them touch the disk. This is probably more secure than what chromium does to be honest.

this sounds like the behaviour will be the same on all platforms so I might be able to verify this using `strace` on linux. It's possible that non-persistent cookies are written somewhere like `~/.cache` but probably not. At least chromium seems to suit your needs

**Comment by artcs** [comment]
To be honest, I never really needed this functionality, just made some tests and wondered about the issue. I think if you ever need session cookies or any authentification cookies from a current browsing session, you can simply use the `cookies.txt` extension to export them and use via the `--cookies` option.
Maybe this could be reflected in the FAQ somehow, if someone else wonders about this.
I think there is nothing to be done for yt-dlp, so I'm closing this here.
Thank you for clarification.

**Comment by pukkandan** [comment]
afaik, there are no extractors that use session cookies

**Comment by mbway** [comment]
I've done some experiments (on Linux) because I was curious:
- I concur that firefox only updates persistent cookies when exiting, and session cookies are never stored in cookies.sqlite regardless of the 'restore previous session' option
- strace was not that informative, there is nothing like `session_data.sqlite` which can easily be identified as holding the session data. I could look in the source code but since these cookies are not that important I won't bother.
- when 'restore previous session' is checked the data must be stored in some form because session cookies do persist between sessions
    - using strace I think it's only writing to `~/.mozilla/firefox` and `~/.cache/mozilla/firefox`
    
Grepping for a presistent cookie value in `~/.mozilla/firefox` will print:
```
grep: cookies.sqlite: binary file matches
grep: cookies.sqlite-wal: binary file matches
```
but grepping for a session cookie value in the profile dir or cache dir prints nothing, so the data is not stored as plain-text

**Comment by jxu** [comment]
Well I hope the cookies.txt extension doesn't break because Firefox likes to change things like extensions and UI for no reason
