### ISSUE TITLE
How can I download multiple playlists at the same time. Saving the archive file in each uploader's folder.

### ISSUE THREAD

**Issue by JediMaster25** [yt-dlp/yt-dlp#5614]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I can download a playlist saving the download archive to the uploader's folder with this command. But I can't save multiple at the same time with it because they would use the same temporary archive file.
```
yt-dlp --write-info-json --download-archive temp_archive.txt -o "%(uploader|Anon)s/%(title)s-[%(id)s].%(ext)s" --exec after_video:'cat temp_archive.txt >> "%(uploader|Anon)s/archive.txt"; printf "" > temp_archive.txt' "URL" &
```

How can I download multiple playlists at the same time?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
since with your original command you aren't using `--download-archive` to check if a video has already been downloaded, it is probably simpler to ditch that arg altogether and roll your own like this:

```sh
yt-dlp --write-info-json -o "%(uploader|Anon)s/%(title)s-[%(id)s].%(ext)s" \
  --exec after_video:'echo "%(extractor)s %(id)s" >> "%(uploader|Anon)s/archive.txt"' "URL"

**Comment by JediMaster25** [comment]
I do want to check the archive. Otherwise there is no point in saving it. So the original command wasn't working as I expected, I need to find another way of doing it.

**Comment by JediMaster25** [comment]
The issue isn't solved.

**Comment by Grub4K** [comment]
The problem with your solution is that at no point is the moved download archive getting checked. You are only checking the archive entries in the temp archive. That is why bashonly suggested ignoring the `--download-archive` flag alltogether. You could accomplish this from within the Python integration of `yt_dlp` though only as a hacky workaround. The download archive in there can be a custom set-like object, which you could repopulate on the fly.

It is currently not possible to know ahead of time which download archive will be needed. The download archive always has to be loaded before extraction, but that also means you cannot know which archive should be used since there is no metadata at this point. That will mean extraction will always have to take place to support a templated archive file path.

Is this your request, to allow templating for archive files? If so then I would argue that it is off-scope.

**Comment by JediMaster25** [comment]
Well if it's out of scope, as in there is no way this will ever be possible using yt-dlp no matter how many people want it, then I agree that it should be closed.

**Comment by pukkandan** [comment]
@JediMaster25 Your question was asking how to make **your** code do what u want, and does not belong in the issue tracker in the first place. But even so, it has already been answered. If it turns out the question itself is wrong, that is not our problem to solve.

If your objective was to make a feature request instead, you should have looked for duplicates - #953.

Alternately, if you are looking for workarounds, you'll have to write your own script to do this - either by (1) doing an extraction pass first, and then a second pass feeding yt-dlp the correct archive file, OR (2) By using embedded `YoutubeDL` (e.g. using a custom `match_filter`)

---

@Grub4K It is possible to implement a feature to resolve archive filename after extraction. This will be less efficient than using single file, but I wouldn't say it is out of scope.
