### ISSUE TITLE
Missing the ability to handle nested m3u8 for subtitle files?

### ISSUE THREAD

**Issue by DontNuts** [yt-dlp/yt-dlp#5956]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am not sure if it's a bug or by design, so here is a question...

When I tried to download an m3u8 with subtitle file, I figured that the downloaded subtitle file (with extension of  .unknown_video) is another m3u8 which points to the real subtitle file link...

So the question is: Can yt-dlp handle nested m3u8 links for subtitle files?

If you want the original m3u8 link, I can give you privately.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
yt-dlp cannot handle subtitle manifests, only video/master ones. It's not clear from OP whether you passed a subtitle m3u8 or master. If you want me to check, you can send the link


Contact: discord (pukkandan#4207) / reddit (/u/pukkandan) / email (pukkandan.ytdlp@gmail.com)

**Comment by pukkandan** [comment]
The issue is that the subtitle URL looks like `https://m.anyplex.com:443/api_v2/getm3u8.jsp;jsessionid=UNKNOWN?...`. So yt-dlp is unable to identify it as an m3u8 file. https://github.com/yt-dlp/yt-dlp/blob/506e6205a45b78c91f3d83813dcb8e0ed4bf0932/yt_dlp/extractor/common.py#L2033

Only solution I can think of is to send a HEADRequest and check the `Content-Type` similar to GenericIE https://github.com/yt-dlp/yt-dlp/blob/506e6205a45b78c91f3d83813dcb8e0ed4bf0932/yt_dlp/extractor/generic.py#L2404-L2412
