### ISSUE TITLE
Where can I find syntax documentation about flags mentioned in the paragraphs in README (e.g. ytsearch)?

### ISSUE THREAD

**Issue by life5ign** [yt-dlp/yt-dlp#6035]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I see paragraphs like this, with lots of great features, but they don't appear in the main usage syntax documentation, and I need to rely on random websites plus trial and error to learn their usage:

> Supports Clips, Stories (ytstories:<channel UCID>), Search (including filters)*, YouTube Music Search, Channel-specific search, Search prefixes (ytsearch:, ytsearchdate:)*, Mixes, YouTube Music Albums/Channels (https://github.com/yt-dlp/yt-dlp/issues/723), and Feeds (:ytfav, :ytwatchlater, :ytsubs, :ythistory, :ytrec, :ytnotif)

e.g., how *do* I do a channel specific search?  How do I search using filters?  Can ytsearch patterns be regexes?

It would be great to have this in the README or Wiki, or at least one example for each, in the examples section.

Thanks, great work,

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
<CMD STARTED> 2023-01-14T12:58:26-07:00
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.0 (CPython x86_64 64bit) - Linux-5.19.0-76051900-generic-x86_64-with-glibc2.35 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
<CMD FINISHED> 2023-01-14T12:58:27-07:00
```

**Comment by pukkandan** [comment]
Just use the search URLs you get from browser. E.g.

```
https://music.youtube.com/search?q=free+music#songs                      # Youtube music
https://www.youtube.com/@AsapSCIENCE/search?query=relativity             # Search in channel
https://www.youtube.com/results?search_query=yt-dlp&sp=EgIYAg%253D%253D  # Search with filters
```

Make sure to add a `--playlist-end` so that you don't end up with thousands of search results

> Can ytsearch patterns be regexes?

No. `ytsearch:XXX` just shorthand for <https://www.youtube.com/results?search_query=XXX&sp=EgIQAQ%3D%3D> and really only exists for backward compat

As for other prefixes, search for `prefix` and `keyword` in the [list of supported sites](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md)

**Comment by life5ign** [comment]
Great, thanks; that's really helpful.  

So the idea of just using the URL from search results, while it's really obvious, did't even occur to me.  (I did know about the channel or videos for a channel URL usage, based on Output Format Examples.)

Would you all be open to me adding adding some clarification about this, and a supporting example or two of this sort, to the documentation (README)?  I'd like to make sure I understand some things, though, if I contribute. 

To that end, the meaning of the syntax `youtube:search:date` in this line, from supported sites, I still don't understand:

> `youtube:​search:date: YouTube search, newest videos first; "ytsearchdate:" prefix`

Is `youtube:search:date` just a purely symbolic representation of the fact that searches by date are possible for youtube on `yt-dlp`, and that to use it, you need to use the `ytsearchdate:` prefix?  Does this imply that no URL should be used?

Are all the prefixes mentioned in the supported sites just shorthand for searching on the site, and using the resulting URL, or just the `*search:` prefixes?

Actually, I think the concept of "prefixes" [vs. URLS] could really use some clarification, and maybe its own section,  in the docs.  I've been using this for several years, and I'm a programmer, and I still don't understand when and where to use them.   It should answer

- what are prefixes?
- what general effect do they have?
- do they replace the use of a URL, and/or can they be used in conjunction with them, etc?
- where can you find a list of prefixes for your site?
- how to you use them, syntactically, in a command? 
- Where can I find examples of using prefixes?

What about a heading in https://github.com/yt-dlp/yt-dlp#usage-and-options ?  e.g. a "_Specifying URLS and using prefixes"_ section, which answers the above questions, and incorporates the examples and explanations you provided?

I can see how this is pretty clear to the developers, but imho it's not clear to the users, who need more usage information to take advantage of this feature.

**Comment by pukkandan** [comment]
> To that end, the meaning of the syntax `youtube:search:date` in this line, from supported sites, I still don't understand:
> 
> > `youtube:​search:date: YouTube search, newest videos first; "ytsearchdate:" prefix`

`youtube:​search:date` = Extractor name
`YouTube search, newest videos first` = Extractor description
`"ytsearchdate:" prefix` = you can use `ytsearchdate:xxx` to use this extractor - i.e. to search youtube videos by date

> Actually, I think the concept of "prefixes" [vs. URLS] could really use some clarification, and maybe its own section, in the docs. I've been using this for several years, and I'm a programmer, and I still don't understand when and where to use them. It should answer

I do agree that the prefixes are not very well documented. The only mention in the readme is https://github.com/yt-dlp/yt-dlp/blob/87ebab0615b1bf9b14b478b055e7059d630b4833/README.md#L353-L354

I'll try explaining them:

Aside from normal URLs (`https://...` etc), yt-dlp defines some pseudo-URLs internally of the forms `prefix:xxx`, `:keyword` (E.g. `:ythistory`) or just direct youtube video/playlist IDs (E.g. `BaW_jenozKc`, `WL`). Most of these are for internal use (E.g. `anvato:`), is undocumented, and should not be relied on by users. But some are exposed for public use in supportedsites.md. This is for few reasons:
1. In past, youtube-dl did not have support for search URLs, feeds etc, so prefixes/keywords were implemented to handle them. We continue to support them since users may be reliant on them.
2. They are just more convenient than using the full URL. I am generally reluctant to add new prefixes for just this reason, but sometimes, finding the URL is difficult enough for users that this is warranted (E.g. `ytstories:`)
3. Sometimes, there's just no URL. E.g. `amazonminitv:season:`, `nicosearchdate:`, `trovovod:`

Another part of it that is not well documented is that **search** prefixes (but not others) can optionally provide the number of results that should be returned. E.g. `ytsearch:x` (1 result), `ytsearch10:x` (10), `ytsearchall:x` (all results, equivalent to passing URL). Again, this is a redundant feature and exists only because it was necessary in a time before lazy `--playlist-items` handling.

---


> So the idea of just using the URL from search results, while it's really obvious, didn't even occur to me

This, I wouldn't know what to do about. ytdl/p supports many different types of URLs from a multitude of sites. It is impossible to list them all (not to even consider generic extraction) other than mentioning the extractor in supported sites. If you look for "youtube"/"search" in the list, you'll quickly find:

> **youtube:search_url**: YouTube search URLs with sorting and filter support

---

Hope that answers everything. Feel free to follow up if I mised anything or you need further clarification.

And yes, improvements to documentation are welcome

**Comment by TheSamDickey** [comment]
Oh man this is so powerful!  Thank you for taking the time to explain this here.  This really should be documented somewhere

**Comment by alien999999999** [comment]
how would I search for 10 items and then later 10 more (that are different from the ones searched before of course)?
