### ISSUE TITLE
The afreecatv website has just stopped working. 

### ISSUE THREAD

**Issue by RiverChu0** [yt-dlp/yt-dlp#6133]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

korean

### Provide a description that is worded well enough to be understood

The afreecatv website has just stopped working. The following prompt appears:
```
ERROR: [afreecatv] 81669846: Unable to extract station; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/afreecatv.py", line 232, in _real_extract
    station_id = self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# /usr/local/bin/yt-dlp --cookies afreecatv.txt https://vod.afreecatv.com/player/81669846 --concat-playlist never --no-check-certificate -vU

[debug] Command-line config: ['--cookies', 'afreecatv.txt', 'https://vod.afreecatv.com/player/81669846', '--concat-playlist', 'never', '--no-check-certificate', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.8.13 (CPython x86_64 64bit) - Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-glibc2.17 (OpenSSL 1.1.1q  5 Jul 2022, glibc 2.17)
[debug] exe versions: ffmpeg 5.0 (setts), rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[afreecatv] Extracting URL: https://vod.afreecatv.com/player/81669846
[afreecatv] 81669846: Downloading webpage
ERROR: [afreecatv] 81669846: Unable to extract station; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/afreecatv.py", line 232, in _real_extract
    station_id = self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment]
You could try adding `--force-generic` to your command as a workaround for now, but it would most likely result in the "restricted" version of the video being downloaded.

**Comment by RiverChu0** [comment]
> ```shell
> https://vod.afreecatv.com/player/81669846
> ```

Thank you for your reply. I tried it and it `--force-generic` can be downloaded. However, no restricted content can be downloaded. I am waiting for repair. Thank you for your work.

**Comment by RiverChu0** [comment]
@bashonly Thank you for your reply. I tried it and it --force-generic can be downloaded. However, no restricted content can be downloaded. I am waiting for repair. Thank you for your work.

**Comment by NastyxNas** [comment]
Hi I also tried the workaround provided, it is working somewhat but the download speed is VERY slow

**Comment by Ecdldaiiere** [comment]
> Hi I also tried the workaround provided, it is working somewhat but the download speed is VERY slow

Until this gets fixed, I found a method that works with good download speed. Download the latest version of ffmpeg, then use the command: 

ffmpeg -headers "Referer: https://vod.afreecatv.com/player/XXXXXXXX" -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" -i example.m3u8 -c copy output.mp4

Copy and paste your own User-agent into the above example. I get a bunch of these "packet corrupt" sayings while downloading, but the final video turns out perfect. Also, many Afreecatv VODs are split up into multiple .m3u8 files. So make sure you are getting each one, then stitch them all together with a program like LosslessCut.

**Comment by jouven** [comment]
> > Hi I also tried the workaround provided, it is working somewhat but the download speed is VERY slow
> 
> Until this gets fixed, I found a method that works with good download speed. Download the latest version of ffmpeg, then use the command:
> 
> ffmpeg -headers "Referer: https://vod.afreecatv.com/player/XXXXXXXX" -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" -i example.m3u8 -c copy output.mp4
> 
> Copy and paste your own User-agent into the above example. I get a bunch of these "packet corrupt" sayings while downloading, but the final video turns out perfect. Also, many Afreecatv VODs are split up into multiple .m3u8 files. So make sure you are getting each one, then stitch them all together with a program like LosslessCut.

It's possible to use yt-dlp with the m3u8 urls, no need to use --force-generic even, and it works like before, the speed is better, alas there is some missing funcionality like proper video filename. While we wait for a fix this works fine, it's just the extra step-issue of getting the m3u8 urls.

**Comment by dmfp** [comment]
It seems AfreecaTV modified the http://afbbs.afreecatv.com:8080/api/video/get_video_info.php API which the extractor relies on to no longer include the m3u8 url.

**Comment by 63427083** [comment]
[http://afbbs.afreecatv.com:8080/api/video/get_video_info.php](http://afbbs.afreecatv.com:8080/api/video/get_video_info.php) still works if you crawl bbs and station ID from other points like vod overview. 
This proves only as a manual workaround though, but at least allows login/restricted content options.

**Comment by dmfp** [comment]
> http://afbbs.afreecatv.com:8080/api/video/get_video_info.php still works if you crawl bbs and station ID from other points like vod overview.
> This proves only as a manual workaround though, but at least allows login/restricted content options.

The API still works, even if you supply dummy values for station/bbs IDs. But it no longer contains video segments/playlist url as it used to - are you seeing different some how?

**Comment by Cyborgeagle** [comment]
Hmm is it broken maybe or someone help me what I do wrong? It is restricted content because the stream was flagged 19+ for some segments.

``
yt-dlp --cookies cookies2.txt https://vod.afreecatv.com/player/98054524 --concat-playlist never --no-check-certificate -vU --force-generic                                                                                 1 ✘  8s  
[debug] Command-line config: ['--cookies', 'cookies2.txt', 'https://vod.afreecatv.com/player/98054524', '--concat-playlist', 'never', '--no-check-certificate', '-vU', '--force-generic']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25]
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-6.1.9-1-MANJARO-x86_64-with-glibc2.36 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Crypto-3.17, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://vod.afreecatv.com/player/98054524
[generic] 98054524: Downloading webpage
WARNING: [generic] Forcing generic information extractor
[generic] 98054524: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://vod.afreecatv.com/player/98054524
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2523, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vod.afreecatv.com/player/98054524
``

**Comment by pukkandan** [comment]
#4514

**Comment by Shandoolie** [comment]
#4514 is not related to this at all

**Comment by bashonly** [comment]
Right, #4514 is specifically tracking age-restricted videos not extracting properly, and this issue is tracking the extractor being completely broken. Reopened

**Comment by Cyborgeagle** [comment]
It doesn't work for me at all now even for videos with no age restricted content. 

```
yt-dlp --cookies cookies2.txt https://vod.afreecatv.com/player/98469676 --concat-playlist never --no-check-certificate -vU --force-generic
[debug] Command-line config: ['--cookies', 'cookies2.txt', 'https://vod.afreecatv.com/player/98469676', '--concat-playlist', 'never', '--no-check-certificate', '-vU', '--force-generic']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25]
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-6.1.11-1-MANJARO-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Crypto-3.17, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://vod.afreecatv.com/player/98469676
[generic] 98469676: Downloading webpage
WARNING: [generic] Forcing generic information extractor
[generic] 98469676: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://vod.afreecatv.com/player/98469676
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2523, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vod.afreecatv.com/player/98469676
```

**Comment by msikma** [comment]
Same here. Seems something else might have changed, as I was able to download vods with `--force-generic` until just now.

**Comment by RiverChu0** [comment]
As of today, it has not been repaired
