### ISSUE TITLE
Subtitle file is not deleted after being embedded

### ISSUE THREAD

**Issue by 35609902357** [yt-dlp/yt-dlp#630]
Embedding subtitles in the video and also keeping the file is pointless and it results in 2 identical tracks for the same video.

The default behavior of youtube-dl is to keep the file if not embedded and delete it if embedded, this is smarter because the `-k` flag can be used if someone wants to embed and also keep the file, but there is no flag to automatically remove the file once embedded.

Maybe adding a flag like `--keep-subs-file` would solve the problem for those few users who might want both, but the default should be what youtube-dl does, keep the file if external subs or embed and delete.

**Comment by pukkandan** [comment]
> Embedding subtitles in the video and also keeping the file is pointless and it results in 2 identical tracks for the same video.

Just because you don't have a use-case for it doesn't mean it is pointless

> but the default should be what youtube-dl does, keep the file if external subs or embed and delete.

If you are using `--write-sub --embed-sub`, it means you want to both keep the subs in disk and embed it. You may also seperately use `--embed-subs` to embed the subs or `--write-subs` to keep the file. This is consistent with how `--write/embed-thumbnails` work

> The default behavior of youtube-dl is to keep the file if not embedded and delete it if embedded

While this is not the "right" behaviour imo, you are right that this is how upstream works. So I will make a `comapt-option` to go back to this. But the default will be kept as the current behaviour


> this is smarter because the -k flag can be used if someone wants to embed and also keep the file, but there is no flag to automatically remove the file once embedded.

It is not the same. `-k` also keeps around many other files like the thumbnail, unmerged streams etc

**Comment by pukkandan** [comment]
For reference, there's the differences:

#### youtube-dl

Option|Behaviour
:---|:---
--write-subs|Write normal sub to disk
--write-subs --write-auto-subs|Write a normal/auto sub to disk
--embed-subs|Do nothing
--write-subs --embed-subs|Embed normal sub and delete
--write-auto-subs --embed-subs|Embed auto sub and delete
--write-subs --write-auto-subs --embed-subs|Embed a normal/auto sub and delete

#### yt-dlp

Option|Behaviour
:---|:---
--write-subs|Write normal sub to disk
--write-subs --write-auto-subs|Write a normal/auto sub to disk
--embed-subs|Embed normal sub and delete
--write-subs --embed-subs|Embed normal sub and keep it in disk
--write-auto-subs --embed-subs|Embed auto sub and delete
--write-subs --write-auto-subs --embed-subs|Embed a normal/auto sub and keep it in disk

**Comment by 35609902357** [comment]
@pukkandan

> Just because you don't have a use-case for it doesn't mean it is pointless

You arbitrarily decided to change a long standing default behavior because [one user asked for this in an unrelated issue](https://github.com/yt-dlp/yt-dlp/issues/57#issuecomment-775240126), no proper issue was ever open about this.

Changing that default behavior makes the transition from youtube-dl to yt-dlp and viceversa a pain because it breaks years old config files and requires to pay extra unneeded attention when using one project or the other.

Not only that, but those who embed `--all-subs` will have a hard time having left hundreds of files around.

Not only that, but it's also lacking. For example, I want to automatically embed subs if they are present, if there is no subtitles track I want to embed automatically generated subs. In youtube-dl I would go with `--write-subs --write-auto-subs --embed-subs`, yt-dlp leaves around files, even if there are only auto generated subs. Since the only option to differentiate between subs types are '--write-subs` and `--write-auto-subs`, yt-dlp makes it impossible to have the old behavior.

`--embed-subs` being a post-process option should naturally work on the file generated by the previous option, then all files are deleted after the post-process, for those who need one or many files to be kept there's the `-k` flag.

There is no point having internal and  external tracks for the large majority of users. Even if someone might need both for some edge case, there's no point in making it the default instead of creating a `--keep-subs` option to integrate their need.

From the Readme (emphasis mine):

> The main focus of this project is adding new features and patches while also **keeping up to date with the original project**

Changing defaults goes against the purpose of this project.

**Comment by pukkandan** [comment]
> You arbitrarily decided to change a long standing default behavior because one user asked for this in an unrelated issue, no proper issue was ever open about this.

It is youtube-dl's handling of `--embed-subs` that is inconsistent with their own handling of the similar option `--embed-thumb`. When this disparity was pointed out to me, I changed this at my discretion because I consider this a bug in youtube-dl since this inconsistent behaviour is never documented anywhere and is therefore counter-intuitive and most probably unintentional.

> Not only that, but those who embed --all-subs will have a hard time having left hundreds of files around.

`--all-subs` is deprecated. You should be using `--sub-lang all`. [see this](https://github.com/yt-dlp/yt-dlp#not-recommended). While I keep most deprecated options still working, they will obviously be more limited in their capability than their recommended counterparts

> Changing that default behavior makes the transition from youtube-dl to yt-dlp and viceversa a pain because it breaks years old config files and requires to pay extra unneeded attention when using one project or the other.

I have no intention of maintaining perfect compatibility with years old youtube-dl config files **out of the box** - especially if they are using such undocumented "features". If you really want yt-dlp to work as close to youtube-dl as possible, you should use `--compat-options youtube-dl`. There are also many other changes that have been made to the default behavior as documented [here](https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior)

It is true that I had failed to document how `--embed-subs` behaved differently than youtube-dl. But since https://github.com/yt-dlp/yt-dlp/commit/b51d2ae3cae121de084460f1260d5d644a566338, it is documented and I have also added the option `--compat-options no-keep-subs` to go back how youtube-dl handled it.

> For example, I want to automatically embed subs if they are present, if there is no subtitles track I want to embed automatically generated subs. In youtube-dl I would go with --write-subs --write-auto-subs --embed-subs, yt-dlp leaves around files, even if there are only auto generated subs. Since the only option to differentiate between subs types are '--write-subsand--write-auto-subs`, yt-dlp makes it impossible to have the old behavior.

This is a fair point. Currently the only way to achive this is by using the compat-option. I will see what can be done to improve this

> --embed-subs being a post-process option should naturally work on the file generated by the previous option, then all files are deleted after the post-process, for those who need one or many files to be kept there's the -k flag.

This is clearly not the intended use of `-k`

```
     -k, --keep-video                Keep the intermediate video file on disk after post-processing
```

Instead of changing how `--embed-subs` work, I could have instead changed how `-k` works with `--embed-thumb`, but that only serves to further limit the functionality

> The main focus of this project is adding new features and patches while also keeping up to date with the original project
> Changing defaults goes against the purpose of this project.

Keeping up-to-date means that upstream changes will be pulled to yt-dlp in a timely manner, not that I won't make any changes

**Comment by 35609902357** [comment]
> I have also added the option --compat-options no-keep-subs to go back how youtube-dl handled it.

Thanks for the fix @pukkandan. For simplicity you should allow compatibility options as standalone flags too (for example allow both `--compat-options no-keep-subs` and `--no-keep-subs` to do the same thing, same with the other options).

> This should be considered this a bug in youtube-dl

If you really think so you should open an issue in youtube-dl project to express your reasons.

**Comment by database64128** [comment]
> Not only that, but it's also lacking. For example, I want to automatically embed subs if they are present, if there is no subtitles track I want to embed automatically generated subs. In youtube-dl I would go with `--write-subs --write-auto-subs --embed-subs`, yt-dlp leaves around files, even if there are only auto generated subs. Since the only option to differentiate between subs types are `--write-subs` and `--write-auto-subs`, yt-dlp makes it impossible to have the old behavior.

I think this issue should be kept open until this is resolved.

**Comment by pukkandan** [comment]
It is now possible using the compat option. But I do agree that it should be possible without it. Please open a new issue

**Comment by database64128** [comment]
Opened #826 to track it.

**Comment by chapmanjacobd** [comment]
What about `--embed-any-subs` and `--write-any-subs` as a shortcut for the most verbose configuration

**Comment by pukkandan** [comment]
You can create your own "shortcuts" with `--alias`

**Comment by chapmanjacobd** [comment]
ack. sorry I meant to post this on #2262. Having subs and autosub configuration completely separate but "shortcuts" like `--embed-any-subs`, `--write-any-subs` at the very outside of the code to combine some of the configuration

**Comment by AtomicNess123** [comment]
The point of the option: 
```
--write-subs --write-auto-subs --embed-subs
--compat-options no-keep-subs
```

is to give priority to the subs, not the auto-subs, is this corrrect?

**Comment by pukkandan** [comment]
Yes. It will download normal subs if found, and auto-subs otherwise

**Comment by github-account1111** [comment]
> The point of the option:
> ```
> --write-subs --write-auto-subs --embed-subs
> --compat-options no-keep-subs
> ```
> is to give priority to the subs, not the auto-subs, is this corrrect?

> Yes. It will download normal subs if found, and auto-subs otherwise

And `--embed-subs --write-auto-subs` will download auto-subs if found and normal subs otherwise?

That'd be weird lol
