### ISSUE TITLE
[extractor/youtube] Download speed slow

### ISSUE THREAD

**Issue by joaquinito2070** [yt-dlp/yt-dlp#6381]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As from today, yt-dlp downloads from YouTube slow speed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', '399+251', '-vU', 'ytsearch:Shakira: BZRP Music Sessions, Vol. 53']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-109688-gc8ea824b49-gac37b2c2b1 (setts), ffprobe N-109688-gc8ea824b49-gac37b2c2b1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Extractor Plugins: AGB+NSIG (YoutubeIE)
[debug] Post-Processor Plugins: ReturnYoutubeDislikePP
[debug] Plugin directories: ['C:\\Users\\joaqu\\AppData\\Roaming\\Python\\Python311\\site-packages\\yt_dlp_plugins']
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[youtube:search] Extracting URL: ytsearch:Shakira: BZRP Music Sessions, Vol. 53
[download] Downloading playlist: Shakira: BZRP Music Sessions, Vol. 53
[youtube:search] query "Shakira: BZRP Music Sessions, Vol. 53": Downloading web client config
[youtube:search] query "Shakira: BZRP Music Sessions, Vol. 53" page 1: Downloading API JSON
[youtube:search] Playlist Shakira: BZRP Music Sessions, Vol. 53: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube+AGB+NSIG] Extracting URL: https://www.youtube.com/watch?v=CocEMWdc7Ck
[youtube+AGB+NSIG] CocEMWdc7Ck: Downloading webpage
[youtube+AGB+NSIG] CocEMWdc7Ck: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] CocEMWdc7Ck: Downloading 1 format(s): 399+251
[debug] Invoking http downloader on "https://rr2---sn-gqn-h5qs.googlevideo.com/videoplayback?expire=1677633934&ei=LlX-Y7HqEJfh1gbhxIzoCQ&ip=2a0c%3A5a84%3A710c%3A8e00%3A5910%3Acda7%3Aa9f1%3A4ffc&id=o-AKVGqymVLw_t7aPUvL60mV8pFUMy4vPkOOOFsOFMSYR5&itag=399&source=youtube&requiressl=yes&mh=0y&mm=31%2C29&mn=sn-gqn-h5qs%2Csn-h5qzen76&ms=au%2Crdu&mv=m&mvi=2&pl=36&initcwndbps=1276250&spc=H3gIhh7p2LbU4DkOznBOKCrOs9MdKkI&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=39627829&dur=217.850&lmt=1673614469913683&mt=1677611837&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&txp=4537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgIVCPz7NpJSBp-W0H_PlH1X4vJRDAiicKjUqnnZU2JVACIE_sDsOH5OvO6GG5ljxLV3giDmpQpmrnicAuBGIUZD7d&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgewbfgRB6r-yjEhtVtlchT2zzn4x2Jl-uo6lGlpmTFhkCIBypVlmViTFSkHTnrdF0Z6SLw1EdGPrzDcU7P-S_OpOh"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: SHAKIRA ｜｜ BZRP Music Sessions #53 [CocEMWdc7Ck].f399.mp4
[download] 100% of   37.79MiB in 00:01:49 at 354.20KiB/s
[debug] Invoking http downloader on "https://rr2---sn-gqn-h5qs.googlevideo.com/videoplayback?expire=1677633934&ei=LlX-Y7HqEJfh1gbhxIzoCQ&ip=2a0c%3A5a84%3A710c%3A8e00%3A5910%3Acda7%3Aa9f1%3A4ffc&id=o-AKVGqymVLw_t7aPUvL60mV8pFUMy4vPkOOOFsOFMSYR5&itag=251&source=youtube&requiressl=yes&mh=0y&mm=31%2C29&mn=sn-gqn-h5qs%2Csn-h5qzen76&ms=au%2Crdu&mv=m&mvi=2&pl=36&initcwndbps=1276250&spc=H3gIhh7p2LbU4DkOznBOKCrOs9MdKkI&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3781855&dur=217.881&lmt=1673613108363391&mt=1677611837&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgaq_f1lAIGrIFVfOidE3PDqFVFY1vo5JbNfqXpI6NNP4CIQCPYxIfn98cHN9MJ1suQL_RnvRZe2723ZJSAO8fhXRtMA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgewbfgRB6r-yjEhtVtlchT2zzn4x2Jl-uo6lGlpmTFhkCIBypVlmViTFSkHTnrdF0Z6SLw1EdGPrzDcU7P-S_OpOh"

[download] Destination: SHAKIRA ｜｜ BZRP Music Sessions #53 [CocEMWdc7Ck].f251.webm
[download] 100% of    3.61MiB in 00:01:49 at 33.81KiB/s
[Merger] Merging formats into "SHAKIRA ｜｜ BZRP Music Sessions #53 [CocEMWdc7Ck].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:SHAKIRA ｜｜ BZRP Music Sessions #53 [CocEMWdc7Ck].f399.mp4" -i "file:SHAKIRA ｜｜ BZRP Music Sessions #53 [CocEMWdc7Ck].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:SHAKIRA ｜｜ BZRP Music Sessions #53 [CocEMWdc7Ck].temp.webm"
Deleting original file SHAKIRA ｜｜ BZRP Music Sessions #53 [CocEMWdc7Ck].f399.mp4 (pass -k to keep)
Deleting original file SHAKIRA ｜｜ BZRP Music Sessions #53 [CocEMWdc7Ck].f251.webm (pass -k to keep)
[download] Finished downloading playlist: Shakira: BZRP Music Sessions, Vol. 53
```

**Comment by Raichard** [comment]
The same here, since yesterday it is downloading with low speed if one composes more than one format:
Two different formats:

> [debug] Command-line config: ['-vU', '-f', '140+299', 'https://youtu.be/z8dqgmRM3yQ']
[debug] User config "C:\Users\L03516048\AppData\Roaming\yt-dlp\config": ['-o', 'C:\\Users\\L03516048\\Videos\\youtube\\%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-11-21-git-459527108a-essentials_build-www.gyan.dev (setts), ffprobe 2022-11-21-git-459527108a-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[youtube] Extracting URL: https://youtu.be/z8dqgmRM3yQ
[youtube] z8dqgmRM3yQ: Downloading webpage
[youtube] z8dqgmRM3yQ: Downloading android player API JSON
[debug] Loading youtube-nsig.a897053d from cache
[debug] [youtube] Decrypted nsig k6MEBRhcaLs2wTU2tsN => V5qM7lWhI10CNw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] z8dqgmRM3yQ: Downloading 1 format(s): 140+299
[debug] Invoking http downloader on "https://rr3---sn-uvu5a2a5t-huts.googlevideo.com/videoplayback?expire=1677634607&ei=z1f-Y8W9JNSM2_gP9pG54AY&ip=189.203.91.162&id=o-ACAtdcIQcbvarspn5Up1lhYsxs8AEmNhFc7uLqo4B8Q7&itag=140&source=youtube&requiressl=yes&mh=KA&mm=31%2C29&mn=sn-uvu5a2a5t-huts%2Csn-9gv7lns7&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1338750&spc=H3gIhljFGwwTWZPbx2ERNtcSYdOjK0k&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=30538850&dur=1886.923&lmt=1628697276276430&mt=1677612558&fvip=3&keepalive=yes&fexp=24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAObs77ja37-qX1n4FkdudMoAtmqkJ4z4hfhWdKYjMFQeAiEAwIRoSe4LlNK_bfTkn_LDi7HSboef1ht5TaFHBK8DkXo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgH8A-Va3gwXKcgpI5yrdNX1aT9y-DrEEbyegu03Ek5QQCIBlyhYLibqm34mwJMeFl_Pj1JUaiu604aCxmXDT9p79Z"
[download] Resuming download at byte 12594251
[debug] File locking is not supported. Proceeding without locking
[download] Destination: C:\Users\L03516048\Videos\youtube\23 CONSEJOS para PRINCIPIANTES en RAINBOW SIX SIEGE.f140.m4a
[download] 100% of   29.12MiB in 00:09:15 at 53.65KiB/s
[debug] Invoking http downloader on "https://rr3---sn-uvu5a2a5t-huts.googlevideo.com/videoplayback?expire=1677634607&ei=z1f-Y8W9JNSM2_gP9pG54AY&ip=189.203.91.162&id=o-ACAtdcIQcbvarspn5Up1lhYsxs8AEmNhFc7uLqo4B8Q7&itag=299&source=youtube&requiressl=yes&mh=KA&mm=31%2C29&mn=sn-uvu5a2a5t-huts%2Csn-9gv7lns7&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1338750&spc=H3gIhljFGwwTWZPbx2ERNtcSYdOjK0k&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=898576980&dur=1886.833&lmt=1628698227917720&mt=1677612558&fvip=3&keepalive=yes&fexp=24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgbJ0z8yLWYriBhYCjff3hBqxAxukDqCe1I3LVswW9MFgCIB2PDc1JRG5xo15BincZVvp_smxptXrv01IQuhkFno9f&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgH8A-Va3gwXKcgpI5yrdNX1aT9y-DrEEbyegu03Ek5QQCIBlyhYLibqm34mwJMeFl_Pj1JUaiu604aCxmXDT9p79Z"
[download] Destination: C:\Users\L03516048\Videos\youtube\23 CONSEJOS para PRINCIPIANTES en RAINBOW SIX SIEGE.f299.mp4
[download] 100% of  856.95MiB in 00:15:49 at 924.49KiB/s
[Merger] Merging formats into "C:\Users\L03516048\Videos\youtube\23 CONSEJOS para PRINCIPIANTES en RAINBOW SIX SIEGE.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\L03516048\Videos\youtube\23 CONSEJOS para PRINCIPIANTES en RAINBOW SIX SIEGE.f140.m4a" -i "file:C:\Users\L03516048\Videos\youtube\23 CONSEJOS para PRINCIPIANTES en RAINBOW SIX SIEGE.f299.mp4" -c copy -map "0:a:0" -map "1:v:0" -movflags "+faststart" "file:C:\Users\L03516048\Videos\youtube\23 CONSEJOS para PRINCIPIANTES en RAINBOW SIX SIEGE.temp.mp4"
Deleting original file C:\Users\L03516048\Videos\youtube\23 CONSEJOS para PRINCIPIANTES en RAINBOW SIX SIEGE.f299.mp4 (pass -k to keep)
Deleting original file C:\Users\L03516048\Videos\youtube\23 CONSEJOS para PRINCIPIANTES en RAINBOW SIX SIEGE.f140.m4a (pass -k to keep)


A single format:

>[debug] Command-line config: ['-vU', '-f', '22', 'https://youtu.be/z8dqgmRM3yQ']
[debug] User config "C:\Users\L03516048\AppData\Roaming\yt-dlp\config": ['-o', 'C:\\Users\\L03516048\\Videos\\youtube\\%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-11-21-git-459527108a-essentials_build-www.gyan.dev (setts), ffprobe 2022-11-21-git-459527108a-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[youtube] Extracting URL: https://youtu.be/z8dqgmRM3yQ
[youtube] z8dqgmRM3yQ: Downloading webpage
[youtube] z8dqgmRM3yQ: Downloading android player API JSON
[debug] Loading youtube-nsig.a897053d from cache
[debug] [youtube] Decrypted nsig XrR7rj2gOEqgx0dv8Gm => CJ7lBemcp4JVEw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] z8dqgmRM3yQ: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr3---sn-uvu5a2a5t-huts.googlevideo.com/videoplayback?expire=1677636713&ei=CWD-Y_vMHZiMiwSt96bQCA&ip=189.203.91.162&id=o-ADHms7lDmld2vTAXEvK2dVE1HpRCNkylrIxJYC1eJkay&itag=22&source=youtube&requiressl=yes&mh=KA&mm=31%2C29&mn=sn-uvu5a2a5t-huts%2Csn-9gv7lns7&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1390000&spc=H3gIhmshFJ3d7aeHUTJYmtCZdsCA114&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1886.923&lmt=1628698123139166&mt=1677614952&fvip=3&fexp=24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJybgyuoeYYTq_mBlFGhMVzlvsV5p03Yn6Y75NF86yPYCIQDI5jt92jvqkz3hywRV4jVplqxCZvb8Z_zGVYQUHzL34A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPatHqF_jKMqGDigbe99dVUKZY0VdF6ATeHMMcH1scBLAiA1Uj_E6ib9wueUwuOlBpegzsUFiDM1mTX7rpN1xRHMqQ%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: C:\Users\L03516048\Videos\youtube\23 CONSEJOS para PRINCIPIANTES en RAINBOW SIX SIEGE.mp4
[download] 100% of  304.41MiB in 00:00:12 at 23.87MiB/s

**Comment by bashonly** [comment]
See pinned issues

Youtube began a new throttling campaign against downloaders. The issue has been solved in master branch.

If you don't want to wait for the next release, [install master with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip) or see this comment https://github.com/yt-dlp/yt-dlp/issues/6369#issuecomment-1448019166

**Comment by zoobab** [comment]
I made a workaround yesterday using aria2c as alternative downloader with 10 connections -N10, I went from 32kb/s to 500kb/s.

**Comment by Kavolc** [comment]
Even after installing master the download speed still 190kbps
