### ISSUE TITLE
Efficiently getting consequtive search results

### ISSUE THREAD

**Issue by forthrin** [yt-dlp/yt-dlp#6563]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

YouTube search uses `continuation` tokens. To read page `n`, page `1` through `n-1` must be read first.

1. Is there a way to somehow make `yt-dlp` remember its continuation state, so that `yt-dlp` can be called consequtively from the command line without re-fetching `1` to `n-1` for each iteration?

2. For maximum performance, is there a way to ask for videos from precisely one search page, rather than from search hit number `x` to `y`? Number of search hits for a given page seems somewhat arbitrary.

`$ yt-dlp -v --playlist-start 121 --playlist-end 122 --flat-playlist -J https://www.youtube.com/results?search_query=fly+fishing`
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Git HEAD: 607510b9f
[youtube:search_url] Extracting URL: https://www.youtube.com/results?search_query=fly+fishing
[youtube:search_url] query "fly fishing" page 1: Downloading API JSON
[youtube:search_url] query "fly fishing" page 2: Downloading API JSON
[youtube:search_url] query "fly fishing" page 3: Downloading API JSON

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

[yt-dlp.log](https://github.com/yt-dlp/yt-dlp/files/11010460/yt-dlp.log)

**Comment by pukkandan** [comment]
On the surface, the answer to both is no. But both of them look like weird requirements anyway. If you elaborate what you are actually trying to do, I may be able to help better

**Comment by pukkandan** [comment]
> 1. Is there a way to somehow make `yt-dlp` remember its continuation state, so that `yt-dlp` can be called consequtively from the command line without re-fetching `1` to `n-1` for each iteration?

Actually, this is kinda possible using `--write-pages`/`--load-pages`, but that is not it's intended usecase

**Comment by forthrin** [comment]
A front end that shows search results, one page at a time (ie. press a key for next page). Thus the code needs to call the search as some sort of stateful iterator. I did actually write one myself (not much code is needed), but wondered if one could rely on an established library instead, since it's well maintained and supports many search engines to boot.

**Comment by dirkf** [comment]
The search results can be different each time you ask, so the concept of the "n-th" page of search results is not well defined.

Maybe write your search results to a playlist JSON and use a tool like _jq_, or an equivalent library for the use case above, to select subset playlists to be loaded subsequently?

**Comment by pukkandan** [comment]
I see. yt-dlp does not keep states between runs. You will be able to achieve what you want with the API, but not through CLI.

**Comment by forthrin** [comment]
I know `yt-dlp` is stateless (except arguably cookies), and a switch to stateful capabilities shouldn't be done on a whim.

Is there a `yt-dlp` API? I can't find any mention in the man pages (or elsewhere), except external ones. I found [this](https://github.com/yt-dlp/yt-dlp/discussions/1292), but it would require Python, whereas I've switched to Ruby. Anyway, could the API be more prominently promoted?

Fetching "all" (ie. a fixed "large" number of) search results in advance is obviously not an option, as it would create a long initial delay, and prevent further searches once exhausted.

Though the command line is sort of a front end in itself, enabling the making of various convenience front ends (primarily text based, but maybe even GUI) is desirable. What is possible here, and what are the most successful front ends so far?

As a general comment, I would like to see `yt-dlp` facilitate relevant "heavy lifting", of which two areas stand out:

1. Extraction in general. Anyone can extract a single site, but 1000+ sites takes a village.
2. Advanced bypassing (decryption and JS emulation). It would be nice to have all such code modularized, so the efforts and capabilities can be piggybacked/shared with other projects.

**Comment by pukkandan** [comment]
Yes, the API is only for Python https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp. Providing cross-language cross-platform API not a viable task for us. It is however relatively easy for users to write wrappers around yt_dlp in python, compile it and call that from their program in other language.

---

As for your actual requirement, here are some problems roughly from hardest to easiest:

1. There is currently no framework to skip to the middle of an extraction process[^2].
1. Even once a framework is built, the actual implementation is not generalizable and would have to be implemented individually for each site[^3].
1. Just the continuation token is insufficient to extract a page reliably. Other data like the ytcfg, visitor_data etc which are obtained from the original webpage are also needed[^4]. All of these would have to be saved in some "state file" and loaded back.

Considering all these, `--write-pages`/`--load-pages`[^1], appear to be a much better solution. If you have difficulty using these options for your need, let me know and I'll see what can be done.

[^1]: while not originally intended for such a use
[^2]: I have no idea how this can be implemented, but I'm sure there is some way
[^3]: It is a daunting task even just for youtube due to the complexity of the [pagination function](https://github.com/yt-dlp/yt-dlp/blob/9a06b7b1891b48cebbe275652ae8025a36d97d97/yt_dlp/extractor/youtube.py#L4745)
[^4]: Most of these have hardcoded fallbacks, but they aren't reliable

**Comment by forthrin** [comment]
OK to close this for now. Though I'd like a comment on:

1. Can you give a specific example of how the continuation token not sufficient?
2. Could site decryption be modularized, so efforts and capabilities can be shared with other projects.
3. Same question for bypassing that requires JS emulation.

**Comment by pukkandan** [comment]
> 1. Can you give a specific example of how the continuation token not sufficient?

Wdym "specific example"? It just isn't enough for youtube... Idk how to explain that better other than ask you to look at the source code.

> 2. Could site decryption be modularized, so efforts and capabilities can be shared with other projects.

I don't understand. On the surface, what you are asking is what the API is for. Or if you can only use CLI, use `-j` like many other programs already do, but that will ofc have some limitations over API. Can you elaborate exactly what you'd like to do? If this is about https://github.com/yt-dlp/yt-dlp/issues/6563#issuecomment-1475277695 again, pls read my comments on `--write-pages`. 

> 3. Same question for bypassing that requires JS emulation.

Better to use any JS emulator/interpreter library. We have our on terrible interpreter only because we don't want hard dependencies. But if you insist, you can use it from the API as `yt_dlp.jsinterp.JSInterpreter`

**Comment by forthrin** [comment]
1. Yes, I saw the code does a lot more than the continuation token, but running other code with only the continuation token has never seemed to produce any erroneous or suspicious search results. So, just wondering what the difference is.
2. Decryption is the only part of site extraction that's difficult. The rest is just HTML scraping and JSON parsing, which anyone with half a brain can do. So it would make sense to separate out the advanced stuff so other projects can use this specific functionality to do the heavy lifting that requires crypto knowledge that few have. Also the endless, uphill (and meaningless) cat-and-mouse battle against breaking changes could be shared with other projects like `svtplay-dl`.
3. Not the JS emulation in itself, but getting the tokens, etc. Haven't looked at the code, but if it's just about picking out the piece of the site code that generates the token and throw it at the emulation code, then this is a non-issue.

If this sort of philantropy falls out of scope for the project, I understand.

Footnote: To be honest, I don't get why site maintainers bother fighting CLI tool devs and users since they make out 0.01% of the total user mass, and are impervious to all sorts of schemes and obstacles in the first place.
