### ISSUE TITLE
[Feature Request] Quiet mode combined with progress/current job state

### ISSUE THREAD

**Issue by undaunt** [yt-dlp/yt-dlp#66]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.02.04**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I'm wondering if a 'current status' kind of output, similar to rsync's info=progress2 flag, of what is happening could be output to the console while combined with quiet mode. Essentially, instead of having a big block of text of log output, only show and refresh in-place what is currently happening, using maybe 5-10 lines of space.

I found this - https://stackoverflow.com/questions/63025605/how-to-show-only-progress-information-with-youtube-dl

Additionally, there are several different requests for vaguely related things on the parent, but this one is new and seems very similar https://github.com/ytdl-org/youtube-dl/issues/27333

**Comment by pukkandan** [comment]
The printing functions of youtube-dl are all over the place (and needs refactoring). I wouldn't know where to even start to implement this.

Maybe someone else will be interested in implementing this. If not, I will get back to this once I am done with all the other projects

**Comment by pukkandan** [comment]
I forgot to link this issue with #1125. But since that PR, you can use `--quiet --progress` to show progress bar in quiet mode

**Comment by TowardMyth** [comment]
Hi @pukkandan thanks for implementing this fix. Now, when I call on [yt-dlp in a Python script](https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp), and set `quiet=True` in the `ydl_opts` dictionary, a progress bar will _still_ show up despite `quiet=True`. Could you make it so that:

1. If `quiet=True` and `progress=True`, then a progress bar is shown
2. Else if `quiet=True` and `progress=False` or `progress` is not specified, then a progress bar is not shown?

**Comment by pukkandan** [comment]
The default of `progress` is True. Set `progress=False` to not show progress bar
