### ISSUE TITLE
keep fields available if and as long as possible

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6920]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

2 ideas/requests (put into the same issue as they are probably related):

   1. From the log below, it seems that during the course of the different stages, some fields seem to become available, then disappear, then become available again. Maybe this serves a specific purpose or is difficult to manage differently in the code. If neither is the case, I'll suggest keeping the fields available from the moment they become first known until yt-dlp exits (in other words: **train yt-dlp not to forget fields it already knows**).

   2. In my tests `filepath` and `filename` have the same content (see log below). Why? Can we have a field which contains only the path to the download directory in which filename is located ? I thought this would be the purpose of `filepath` anyway ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
--print pre_process:"-------------------------pre_process-------------------------"
--print pre_process:" filepath: %(filepath)s"
--print pre_process:" filename: %(filename)s"
--print pre_process:"_filename: %(_filename)s"
--print after_filter:"-------------------------after_filter-------------------------"
--print after_filter:" filepath: %(filepath)s"
--print after_filter:" filename: %(filename)s"
--print after_filter:"_filename: %(_filename)s"
--print video:"-------------------------video-------------------------"
--print video:" filepath: %(filepath)s"
--print video:" filename: %(filename)s"
--print video:"_filename: %(_filename)s"
--print before_dl:"-------------------------before_dl-------------------------"
--print before_dl:" filepath: %(filepath)s"
--print before_dl:" filename: %(filename)s"
--print before_dl:"_filename: %(_filename)s"
--print post_process:"-------------------------post_process-------------------------"
--print post_process:" filepath: %(filepath)s"
--print post_process:" filename: %(filename)s"
--print post_process:"_filename: %(_filename)s"
--print after_move:"-------------------------after_move-------------------------"
--print after_move:" filepath: %(filepath)s"
--print after_move:" filename: %(filename)s"
--print after_move:"_filename: %(_filename)s"
--print after_video:"-------------------------after_video-------------------------"
--print after_video:" filepath: %(filepath)s"
--print after_video:" filename: %(filename)s"
--print after_video:"_filename: %(_filename)s"
--print playlist:"-------------------------playlist-------------------------"
--print playlist:" filepath: %(filepath)s"
--print playlist:" filename: %(filename)s"
--print playlist:"_filename: %(_filename)s"
```

### output

```
-------------------------pre_process-------------------------
 filepath: ~~
 filename: ~~
_filename: ~~
-------------------------after_filter-------------------------
 filepath: ~~
 filename: ~~
_filename: ~~
-------------------------video-------------------------
 filepath: ~~
 filename: .\downloads\#YT\2023-04-20 SpaceX Starship explodes on first launch attempt\SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.mkv
_filename: .\downloads\#YT\2023-04-20 SpaceX Starship explodes on first launch attempt\SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.mkv
-------------------------before_dl-------------------------
 filepath: ~~
 filename: ~~
_filename: .\downloads\#YT\2023-04-20 SpaceX Starship explodes on first launch attempt\SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.mkv
-------------------------post_process-------------------------
 filepath: .\downloads\#YT\2023-04-20 SpaceX Starship explodes on first launch attempt\SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.mkv
 filename: ~~
_filename: .\downloads\#YT\2023-04-20 SpaceX Starship explodes on first launch attempt\SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.mkv
-------------------------after_move-------------------------
 filepath: .\downloads\#YT\2023-04-20 SpaceX Starship explodes on first launch attempt\SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.mkv
 filename: ~~
_filename: .\downloads\#YT\2023-04-20 SpaceX Starship explodes on first launch attempt\SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.mkv
-------------------------after_video-------------------------
 filepath: ~~
 filename: ~~
_filename: ~~
``` 

### related
* https://github.com/yt-dlp/yt-dlp/issues/6730#issuecomment-1520795409
* #5846

**Comment by pukkandan** [comment]
* `_filename` is only meant for backward compat - don't use it.
* `filename` is the path guessed from output template. This may not be the actual file path due to extension changes during processing. This is intentionally kept equivalent to `--get-filename` of youtube-dl.
* `filepath` is the canonical current path of the file, hence why it starts existing only after download.
* These may be either relative or absolute path based on the output template
* "Can we have a field which contains only the path to the download directory" - I don't see the point. Process it with --parse-metadata, or better in your external script.
* These fields make no sense in `after_video` and `playlist` stages. They have different infodict structures since they represent more than a single download. Use `-O after_video:%()#j` etc to study them.
* The disappearance of `filename` in other stages is not intentional and I'll fix it.
* Are these the only fields you are asking about? Your question seem to imply more fields disappear. If so, please say which.

**Comment by pukkandan** [comment]
> > Use `-O after_video:%()#j` etc to study them.
> 
> I looked at the output. What should I look out for?

Whatever you want to look for? This shows all the fields so you can find where the data you want is.


> * It might also help in simplifying the different `-o` templates (because the download path would not have to be repeated for each `-o` type).

No, it wouldn't help since output templates must be evaluated before any such field is populated.

> but don't understand why 3 are needed)

You need to escape for any shell parsing as well as for regex parsing. When the verbose log shows `filepath:(?P<download_dir>.+\\\\)`, you are good.



> but the parameter is still wrong because:

A mentioned above, `filepath` doesn't exist till **after** download. Parse it at a `WHEN:` where it's available.

```
❯ yt-dlp test:youtube -P D:\TRASH\Downloads --no-sim --parse-meta "post_process:filepath:(?P<download_dir>.+\\)" -O "after_move:%(download_dir|.)s"
D:\TRASH\Downloads\
```

**Comment by Grub4K** [comment]
> You said "They have different infodict structures". I don't see that. Where do the structures differ ?

The info dict gets mutated wildly in the different stages. To see exactly where their structure differs, examine the different stages in code or just print it at those stages. It might have similarities but should not be exactly the same.

> Why do I need to escape for shell parsing if I am **not** in the shell but inside the yt-dlp config file ?

> Config files are parsed like a POSIX shell.

https://github.com/yt-dlp/yt-dlp/issues/6808#issuecomment-1509326678

**Comment by pukkandan** [comment]
> Does that mean now we can use `filename` at all stages for print, but not for `--exec` and `--parse-metadata` ?

Yes, these are not fields that actually exist in the infodict, but something made up for `--print`

https://github.com/yt-dlp/yt-dlp/blob/b5f61b69d4561b81fc98c226b176f0c15493e688/README.md#L1362-L1365



> I can print `filename` at every stage. However the earliest stage in which I can parse `filename` to get the download directory seems to be `before_dl`. Do you know a trick to get the download dir earlier?

Is this related to your other open issue? I have to ask the same question here. Why are you trying to use `--parse-metadata` like a scripting language instead of saving the template in an actual script/shell variable?
