### ISSUE TITLE
--geo-verification-proxy showing error

### ISSUE THREAD

**Issue by other-half** [yt-dlp/yt-dlp#697]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', '--geo-verification-proxy', 'socks4://67.213.111.124:5678', 'https://www.cbc.ca/player/play/1922081347533']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.11.0-25-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: keyring, sqlite
[debug] Proxy map: {}
[debug] [cbc.ca:player] Extracting URL: https://www.cbc.ca/player/play/1922081347533
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/ExhSPC/media/guid/2655402169/1922081347533?mbr=true&formats=MPEG4,FLV,MP3#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 1922081347533: Downloading SMIL data
[ThePlatform] 1922081347533: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 1922081347533: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1922081347533: Downloading 1 format(s): hls-3440
[debug] Invoking downloader on "https://cbcrcolympic-cbc.akamaized.net/hls/live/2025682/geo_allow_ca/yv8y7e53v/hdntl=exp=1629028754~acl=%2f*~id=c97cac3a-b427-4acd-b260-24037c2d6653~data=hdntl~hmac=0099c40aeff722f9a1e1ffb2d4e6f22bfab1a5afb22f24b734dc459d6e9147f9/master_3000-archive.m3u8?aka_me_session_id=AAAAAAAAAACSARlhAAAAAPfbD8bVQLqKPUPqSg%2f8IbbOx9WAx1+aTSqx8DDl62OhA7n40AUgWN0deuMuZlm0z2Mqvy+FEdNE&aka_media_format_type=hls&startTime=1628330097&endTime=1628339816"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2774, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2438, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 386, in download
    return self.real_download(filename, info_dict), True
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/hls.py", line 70, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3190, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

## Description

I am using Ubuntu 20.04 machine. I was trying to download a video from cbc.ca using a proxy (socks4://67.213.111.124:5678), I was able to play the video using that proxy in a browser. I was could see all the available resolution using `yt-dlp -F --geo-verification-proxy socks4://67.213.111.124:5678 https://www.cbc.ca/player/play/1922081347533`. But when I tried to download it using `yt-dlp -v --geo-verification-proxy socks4://67.213.111.124:5678 https://www.cbc.ca/player/play/1922081347533` it showed an error message "ERROR: unable to download video data: HTTP Error 403: Forbidden".

Someone please help me resolve it.
Thanks

**Comment by pukkandan** [comment]
I haven't tested this, but seems to be duplicate of #681

**Comment by pukkandan** [comment]
`--geov-erification-proxy` only applies to the extraction process. Try using it as a `--proxy` instead

**Comment by Vangelis66** [comment]
The OP (@other-half) comes from a "related" `yt-dl` issue, 
https://github.com/ytdl-org/youtube-dl/issues/29756
in which I have posted a very verbose explanation as to what his "issues" are - and how they should be dealt with - in [this](https://github.com/ytdl-org/youtube-dl/issues/29756#issuecomment-898975064) comment ... :wink:
One might say I was indirectly responsible for the creation of this issue **here**, as I was the one to first suggest the use of the `--geo-verification-proxy` option... 
But, as I explained, this is limited to only **short** `www.cbc.ca` videoclips, whose streams aren't geo-sensitive...

Troubleshooting that very `yt-dl` issue, I discovered that `youtube-dl` may have a bug, in that when the `--proxy` option is used with a **SOCKS** proxy as value,  `yt-dl` invokes `ffmpeg` as the default HLS downloader - this leads to failure, because `ffmpeg` doesn't support SOCKS proxies 😭 ; the user has to re-issue the download command adding `--hls-prefer-native`, as advised by the app itself; so, why **not invoke hlsnative in the first place**? 
OTOH, when a HTTP[S] proxy is the value of `--proxy`, hlsnative is auto-invoked...

I was very relieved and glad to ascertain that `yt-dlp` itself **doesn't suffer from this "bug"**; even when a SOCKS proxy is specified, the app invokes **hlsnative**, which leads to download success (provided, of course, the proxy is a live/reliable one - as the OP has been using "free" SOCKS proxies of dubious qualitiy...) ; so, @pukkandan and Team, many thanks indeed for maintaining `yt-dlp` ! ❤️

**Comment by other-half** [comment]
Understood. Thank you.
