### ISSUE TITLE
DeArrow Title and Thumbnail Support for YouTube

### ISSUE THREAD

**Issue by sturmen** [yt-dlp/yt-dlp#7289]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

https://youtu.be/2fKIaalk4_w
https://youtu.be/XSkRGMeqh2o

### Provide a description that is worded well enough to be understood

`yt-dlp` already supports using @ajayyy's SponsorBlock service to perform postprocessing on a download YouTube video in order to improve the downloaded files, but recently Mr. Ramachandran also launched a new project: [DeArrow](https://github.com/ajayyy/DeArrow).

I would love to see the DeArrow API integrated into `yt-dlp` so we could easily, in one step, name the downloaded file to the crowdsourced title as well as have it inserted into the metadata.

Setting the crowdsourced thumbnail as the metadata thumbnail would be a nice bonus too!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A
```

**Comment by pukkandan** [comment]
Similar to https://github.com/yt-dlp/yt-dlp/issues/2770, I would recommend someone make this as a https://github.com/yt-dlp/yt-dlp#plugin. When we implemented SponsorBlock, we did not yet have a plugin architecture. I don't want to support third party APIs in the core project since we now have the plugin system.

Also, Sponsorblock required advanced processing and options that cannot be easily replicated by a plugin in a user-friendly way. This is not the case here - like RYD, the plugin only needs to modify some info-dict fields. You can use https://github.com/pukkandan/yt-dlp-returnyoutubedislike for reference.

**Comment by QuantumWarpCode** [comment]
Made a plug-in that does this. https://github.com/QuantumWarpCode/yt-dlp-dearrow
