### ISSUE TITLE
 DouyuTV live - HTTP error 403 Forbidden

### ISSUE THREAD

**Issue by Lonely233233** [yt-dlp/yt-dlp#7295]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Douyu's live link is invalid

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Administrator>yt-dlp -vU http://www.douyu.com/5168755
[debug] Command-line config: ['-vU', 'http://www.douyu.com/5168755']
[debug] Portable config "E:\Tencent\Mplayer\yt-dlp.conf": ['--output', 'E:\\Tencent\\N_m3u8DL-CLI\\Downloads\\%(title)s-%(section_number)s-%(section_title)s.%(ext)s', '--console-title', '--progress-template', 'download-title:%(info.id)s-%(progress.eta)s', '--merge-output-format', 'mp4', '--no-write-subs', '--external-downloader', 'aria2c', '--cookies-from-browser', 'edge', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Profile 1\Network\Cookies"
[debug] Found local state file at "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Local State"
[Cookies] Extracted 544 cookies from edge
[debug] cookie version breakdown: {'v10': 544, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[DouyuTV] Extracting URL: http://www.douyu.com/5168755
[DouyuTV] 5168755: Downloading room info
[DouyuTV] 5168755: Downloading m3u8 information
ERROR: [DouyuTV] 5168755: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\douyutv.py", line 115, in _real_extract
  File "yt_dlp\extractor\common.py", line 1941, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
I can't reproduce the issue. Have you modified the source code? I don't see how this error could occur otherwise.
These have been lines 107-108 of `douyutv.py` since the last stable release:
```py
            f'http://www.douyutv.com/api/v1/room/{room_id}', video_id,
            note='Downloading room info', query=params)['data']
```
Has yours been modified from `['data']` to `[data]`?

**Comment by suger520HT** [comment]
f'http://www.douyutv.com/api/v1/room/{room_id}', video_id,
            note='Downloading room info', query=params)['data'] 这里没有改动过

**Comment by suger520HT** [comment]
C:\Users\Administrator>yt-dlp https://www.douyu.com/5168755
[Cookies] Extracting cookies from edge
[Cookies] Extracted 543 cookies from edge
[DouyuTV] Extracting URL: https://www.douyu.com/5168755
[DouyuTV] 5168755: Downloading room info
[DouyuTV] 5168755: Downloading m3u8 information
[info] 5168755: Downloading 1 format(s): 2560
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: E:\Tencent\N_m3u8DL-CLI\Downloads\来了 今天无敌开始了！！！ 2023-06-12 21_18-NA-NA.jpg
[download] Destination: E:\Tencent\N_m3u8DL-CLI\Downloads\来了 今天无敌开始了！！！ 2023-06-12 21_18-NA-NA.mp4
[https @ 00000137fa614800] HTTP error 403 Forbidden
https://b7dd8e8de6b47fde4e0d3b48c274d8a4.v.smtcdns.net/openhls-tct.douyucdn2.cn/live/5168755rYvNEHQvI.m3u8?wsSecret=572186bcac9bdc292924ec79c1de82dc&wsTime=1686575888&TxLiveCode=cold_stream_overload&svr_type=live_oc&tencent_test_client_ip=223.73.216.212&dispatch_from=OC_MGR120.233.115.103&utime=1686575899918: Server returned 403 Forbidden (access denied)

**Comment by suger520HT** [comment]
C:\Users\Administrator>yt-dlp https://www.douyu.com/5168755
[Cookies] Extracting cookies from edge
[Cookies] Extracted 542 cookies from edge
[DouyuTV] Extracting URL: https://www.douyu.com/5168755
[DouyuTV] 5168755: Downloading room info
[DouyuTV] 5168755: Downloading m3u8 information
ERROR: [DouyuTV] 5168755: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U 


this is the original

**Comment by suger520HT** [comment]
C:\Users\Administrator>yt-dlp -vU http://www.douyu.com/5168755
[debug] Command-line config: ['-vU', 'http://www.douyu.com/5168755']
[debug] Portable config "E:\Tencent\Mplayer\yt-dlp.conf": ['--output', 'E:\\Tencent\\N_m3u8DL-CLI\\Downloads\\%(title)s-%(section_number)s-%(section_title)s.%(ext)s', '--console-title', '--progress-template', 'download-title:%(info.id)s-%(progress.eta)s', '--merge-output-format', 'mp4', '--no-write-subs', '--external-downloader', 'aria2c', '--cookies-from-browser', 'edge', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Profile 1\Network\Cookies"
[debug] Found local state file at "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Local State"
[Cookies] Extracted 544 cookies from edge
[debug] cookie version breakdown: {'v10': 544, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[DouyuTV] Extracting URL: http://www.douyu.com/5168755
[DouyuTV] 5168755: Downloading room info
[DouyuTV] 5168755: Downloading m3u8 information
ERROR: [DouyuTV] 5168755: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\douyutv.py", line 115, in _real_extract
  File "yt_dlp\extractor\common.py", line 1941, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by suger520HT** [comment]
> can you show a verbose log with this error? add `-v`

Douyu now extracts the live source link and cannot directly use "http://openhls-tct.douyucdn2.cn/dyliveflv1/252140rz7aIq14cx_1024p.flv" must bring txSecret=fea7f993f949de8fae88a25f6a31ca55&txTime=6489e855

Because Douyu now has all the short link formats invalid

**Comment by c-basalt** [comment]
I've ported a solution from https://github.com/WhiteMinds/DouYuRecorder/, and added PhantomJs to the extractor to get authenticated on the new API:
https://github.com/c-basalt/yt-dlp/tree/douyu

---

https://github.com/yt-dlp/yt-dlp/blob/613dbce177d34ffc31053e8e01acf4bb107bcd1e/yt_dlp/extractor/douyutv.py#L113-L116
This `video_url` in the current master branch appears to be no longer working. Do we know if this might work in some cases or should we just get rid of these?

---

Also, when I was testing the patch using `https://www.douyu.com/998`, I noticed that ffmpeg missed a lot of ts fragments from m3u8 link, because the single-threaded download speed of ffmpeg couldn't catch up and playlist reloading was too slow.

One way I figured out is to use `streamlink` with `--stream-segment-threads`. A command like this worked for me: `streamlink $(py.exe -m yt_dlp -v "https://www.douyu.com/998" --get-url) best --loglevel trace -o "$(date +%s)-test.ts" --logfile "$(date +%s)-streamlink.log" --stream-segment-threads 10`

Streamlink without `--stream-segment-threads` will result in an ever-growing download queue, until all queued items start to receive HTTP 404 and streamlink terminates itself.

Is there any plan that future yt-dlp will have some concurrency for m3u8 livestream (perhaps a native m3u8 downloader for live stream, since I don't feel ffmpeg was designed for live stream)? This can be important in a situation like this.

**Comment by bashonly** [comment]
> This video_url in the current master branch appears to be no longer working. Do we know if this might work in some cases or should we just get rid of these?

@c-basalt See the patch here: https://github.com/yt-dlp/yt-dlp/pull/6074#issuecomment-1544809230

**Comment by c-basalt** [comment]
> @c-basalt See the patch here: [#6074 (comment)](https://github.com/yt-dlp/yt-dlp/pull/6074#issuecomment-1544809230)

The patch from May 11th gives new m3u8 links like this: `https://openhls-tct.douyucdn2.cn/live/288016rlols5.m3u8?wsSecret=3a17750d0910ce6f0b73cd888255eeef&wsTime=1689724357`

However, it seems those openhls-tct.douyucdn2.cn links are also giving me HTTP 403. I wonder if something has changed on the server side after that.
