### ISSUE TITLE
Can I check data integrity by downloading video twice and hashing both files ?

### ISSUE THREAD

**Issue by SiddharthManthan** [yt-dlp/yt-dlp#7348]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I wish to check if during batch download file is corrupt. Can I just download the file twices in different folders and compare their hashes. I am downloading from youtube and dailymotion. I do not have enough knowledge about downloader or ffmpeg to know if this would work properly or not.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

**Comment by bashonly** [comment]
If you download with the native downloader (not ffmpeg) and you don't do any postprocessing to the video (including merging video+audio), then I think you should be able to match the hash

**Comment by pukkandan** [comment]
> I am downloading from youtube and dailymotion.

No. The services will be re-encoding the video differently. You'd have to measure the PSNR or a similar metric. The question is really unrelated to yt-dlp

**Comment by shimiaoyerin** [comment]
By default, yt-dlp discards video fragments with excessive retry attempts in DASH format, leading to damaged video fragments. Enabling the options "--abort-on-unavailable-fragment" and "--no-continue" would prevent such damage from occurring.

If you want to search for damaged sections in a video, you need to use ffmpeg. The complete code is as follows:

"ffmpeg -v 16 -stats -hwaccel none -i "1.mp4" -map v -fps_mode cfr -stats_period 0.04 -f null -"

Pay attention to the value "-fps_mode cfr". If you encounter a video with missing fragments, the "dup" value will increase. If there is no damage, it won't be displayed. Unfortunately, even with the above measures, I still couldn't prevent the occurrence of damaged videos. It only reduced the occurrence. I still don't know why damaged videos are produced. Some videos are damaged due to issues with the source server, but in some cases, the source server is not the problem, and I don't know why damage occurs.
