### ISSUE TITLE
Recursive function defintion in traversal_obj

### ISSUE THREAD

**Issue by meliber** [yt-dlp/yt-dlp#7534]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi. I have a question about `yt_dlp/utils/traversal/traverse_obj`. 
In this function, function `apply_key` calls `apply_path` (line 114) within its definition. However, `apply_path` calls `apply_key` (line 215). 
Is this OK? Can this cause a RecursionError?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
cc @Grub4K

**Comment by dirkf** [comment]
This is how you can apply a recursively nested `key` to a recursively nested `path`, where neither can contain circular references.

I suppose OP's point is that in principle, a `RecursionError` (`RuntimeError` in Py 2) could be raised if the call depth exceeds a certain limit, typically 1000, but this would only happen if the data structures being processed had that depth of nesting, whereas they are typically 10 or 100 times smaller. Should a context be found where a higher limit is needed, there is `sys.setrecursionlimit()`.

**Comment by Grub4K** [comment]
This is only relevant for traversal paths that are long and contain a lot of nesting. For example, each flat traversal will have ~5 functions in depth. When using branching (`...`, `(a, b)`) or a dictionary path it will add another layer of these in depth. While supported, you tend to not have more than 4 layers of nesting
```py
traverse_obj(obj, [(a, b), c, {
    0: [(d, e), f],
}])
```
Since we have at most 4 levels of depth in the traversal realistically (4*5 = 20), you would really have to try to reach a recursion problem with this. We are constructing them lazily however, so these calls are not evaluated immediately in the 5 function depth and linger more in ~3 per call. I don't think you will ever encounter a problem in regular use.

**Comment by meliber** [comment]
Thank you.
