### ISSUE TITLE
REGRESSION: Downloads being marked as successful and useless .mhtml files downloading

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/yt-dlp#7715]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt-dlp gives that warning, and then proceeds to download the images formats automatically, which feels unexpected. I should note that I don't mind this behaviour, but I wanted to report it since I don't think it's expected. I also don't think it was the case in previous versions of yt-dlp, but I don't have time to check which specific version right now

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['2W4zi4r0p6o', '--verbose', '--simulate']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.07.15.211025 [613dbce17] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.4.4-surface-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube] Extracting URL: 2W4zi4r0p6o
[youtube] 2W4zi4r0p6o: Downloading webpage
[youtube] 2W4zi4r0p6o: Downloading ios player API JSON
[youtube] 2W4zi4r0p6o: Downloading android player API JSON
[debug] Loading youtube-nsig.0e6aaa83 from cache
[debug] [youtube] Decrypted nsig ygODdwGQbcu3AiuViQ => B80SACy-Ob7MQQ
[youtube] 2W4zi4r0p6o: Downloading m3u8 information
[youtube] 2W4zi4r0p6o: Downloading MPD manifest
WARNING: This video is drm protected and only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2W4zi4r0p6o: Downloading 1 format(s): sb0
```

**Comment by gamer191** [comment]
Regression (or possibly intended behaviour) in https://github.com/yt-dlp/yt-dlp/commit/906c0bdcd8974340d619e99ccd613c163eb0d0c2

**Comment by SiXOTshRuTEr** [comment]
I've got a couple verbose log segments and dumps of the .mhtml issue, if that's helpful in confirming the issue from #8613.  It's not the working .mp4 thing though, I'll try to get logs/dumps if that happens again.  I'm using  yt-dlp 2023.11.16.

[ytdlp git issue dumps #7715.zip](https://github.com/yt-dlp/yt-dlp/files/13422251/ytdlp.git.issue.dumps.7715.zip)

Also here's my actual ytdlp command from my windows bat script if that helps:

yt-dlp -v --write-pages -S "res:720,ext:webm:webm,fps:60"^
 -P "L:/ytdlp" -P "temp:temp" --output-na-placeholder ""^
 -o "video/%%(webpage_url_domain.:-4)s/%%(uploader)s/%%(playlist)s/%%(uploader)s - %%(upload_date>%%Y-%%m-%%d)s - %%(title)s - [%%(height)sp%%(fps)#.0D].%%(ext)s"^
 -o "subtitle:meta/%%(webpage_url_domain.:-4)s/%%(uploader)s/subs/%%(uploader)s - %%(upload_date>%%Y-%%m-%%d)s - %%(title)s.%%(ext)s"^
 -o "thumbnail:meta/%%(webpage_url_domain.:-4)s/%%(uploader)s/thumb/%%(uploader)s - %%(upload_date>%%Y-%%m-%%d)s - %%(title)s.%%(ext)s"^
 -o "description:meta/%%(webpage_url_domain.:-4)s/%%(uploader)s/desc/%%(uploader)s - %%(upload_date>%%Y-%%m-%%d)s - %%(title)s.%%(ext)s"^
 -o "infojson:meta/%%(webpage_url_domain.:-4)s/%%(uploader)s/json/%%(uploader)s - %%(upload_date>%%Y-%%m-%%d)s - %%(title)s.%%(ext)s"^
 --print-to-file after_move:"%%(webpage_url_domain.:-4)s %%(id)s     %%(epoch-14400>%%x-%%I:%%M:%%S %%p)s     %%(uploader)s - %%(upload_date>%%Y-%%m-%%d)s - %%(title)s"^
 "L:/ytdlp/download_log/%%(uploader)s [%%(webpage_url_domain.:-4)s].txt"^
 --extractor-args "youtube:skip=hls,dash"^
 --limit-rate 5M --max-downloads %MAX_DL%^
 --downloader aria2c --downloader-args aria2c:"-c -j 16 -x 16 -s 8 -k 4M"^
 --fragment-retries 3 --abort-on-unavailable-fragments --retries 5 --retry-sleep 60^
 --sleep-subtitles 5 --sleep-requests 1 --min-sleep-interval 7 --max-sleep-interval 14^
 --cookies-from-browser firefox --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"^
 --no-mtime --no-colors --merge-output-format mp4^
 --compat-options no-live-chat --no-get-comments --break-on-reject --break-per-input^
 --write-info-json --write-description --write-thumbnail --write-subs --write-auto-subs --no-write-playlist-metafiles^
 --embed-metadata --embed-chapters --embed-subs --embed-thumbnail^
 --dateafter today-10000day --match-filter "!is_live"^
 --lazy-playlist --playlist-end 10000^
 --download-archive "archiveYT.txt"^
 "%URL%"




[download] Downloading item 40 of N/A
[youtube] Extracting URL: https://www.youtube.com/watch?v=4zzuSy1mJ2I
[youtube] Sleeping 1.0 seconds ...
[youtube] 4zzuSy1mJ2I: Downloading webpage
[youtube] Saving request to 4zzuSy1mJ2I_https_-_www.youtube.com_watchv=4zzuSy1mJ2I_bpctr=9999999999_has_verified=1.dump
[youtube] Sleeping 1.0 seconds ...
[youtube] 4zzuSy1mJ2I: Downloading ios player API JSON
[youtube] Saving request to 4zzuSy1mJ2I_https_-_www.youtube.com_youtubei_v1_playerkey=AIzaSyB-63vPrdThhKuerbB2N_l7Kwwcxj6yUAc_prettyPrint=false.dump
WARNING: [youtube] Skipping player response from ios client (got player response for video "aQvGIIdgFDM" instead of "4zzuSy1mJ2I"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] Sleeping 1.0 seconds ...
[youtube] 4zzuSy1mJ2I: Downloading android player API JSON
[youtube] Saving request to 4zzuSy1mJ2I_https_-_www.youtube.com_youtubei_v1_playerkey=AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w_prettyPrint=false.dump
WARNING: [youtube] Skipping player response from android client (got player response for video "aQvGIIdgFDM" instead of "4zzuSy1mJ2I"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "aQvGIIdgFDM" instead of "4zzuSy1mJ2I"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by user: res:720, ext:webm:webm, fps:60
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:720(720.0), vext:webm(4), aext:webm(3), fps:60(60.0), quality, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4zzuSy1mJ2I: Downloading 1 format(s): sb0
[info] Writing video description to: L:\ytdlp\meta\youtube\Deep Dive Gaming\desc\Deep Dive Gaming - 2022-08-29 - Video Not Available.description
[info] There are no subtitles for the requested languages
Deleting existing file L:\ytdlp\meta\youtube\Deep Dive Gaming\thumb\Deep Dive Gaming - 2022-08-29 - Video Not Available.webp
[info] Downloading video thumbnail 42 ...
[info] Writing video thumbnail 42 to: L:\ytdlp\temp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-08-29 - Video Not Available - [90p1].webp
[info] Writing video metadata as JSON to: L:\ytdlp\meta\youtube\Deep Dive Gaming\json\Deep Dive Gaming - 2022-08-29 - Video Not Available.info.json
[debug] Invoking mhtml downloader on "https://i.ytimg.com/sb/aQvGIIdgFDM/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiJycaTBg==&sigh=rs$AOn4CLA2u97YB314rQ3kWQRttMLzaGjCpw"
[download] Sleeping 10.55 seconds ...
[mhtml] Total fragments: 7
[download] Destination: L:\ytdlp\temp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-08-29 - Video Not Available - [90p1].mhtml
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   98.62KiB in 00:00:06 at 14.92KiB/s
[EmbedSubtitle] Skipping images
[Metadata] Skipping images
[EmbedThumbnail] Skipping images
[MoveFiles] Moving file "L:\ytdlp\temp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-08-29 - Video Not Available - [90p1].webp" to "L:\ytdlp\meta\youtube\Deep Dive Gaming\thumb\Deep Dive Gaming - 2022-08-29 - Video Not Available.webp"
[MoveFiles] Moving file "L:\ytdlp\temp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-08-29 - Video Not Available - [90p1].mhtml" to "L:\ytdlp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-08-29 - Video Not Available - [90p1].mhtml"
[info] Writing '%(webpage_url_domain.:-4)s %(id)s     %(epoch-14400>%x-%I:%M:%S %p)s     %(uploader)s - %(upload_date>%Y-%m-%d)s - %(title)s' to: L:\ytdlp\download_log\Deep Dive Gaming [youtube].txt
[debug] Adding to archive: youtube 4zzuSy1mJ2I
[download] EBD5-uPbtE8: Diving into Sim Settlements 2 Chs 1 & 2 - 36 Lazy Day Checking on Settlements has already been recorded in the archive
[download] ky7hXrhC3II: Diving into Sim Settlements 2 Chs 1 & 2 - 37 Preparing Abernathy has already been recorded in the archive
[download] DDTMx6cpk4Q: Diving into Sim Settlements 2 Chs 1 & 2 - 38 Preparing Starlight Drive-In has already been recorded in the archive
[download] QRBhwv1_pK8: Diving into Sim Settlements 2 Chs 1 & 2 - 39 Preparing Sunshine Tidings   um   OOPS! has already been recorded in the archive
'

[download] Downloading item 45 of N/A
[youtube] Extracting URL: https://www.youtube.com/watch?v=VYaUnjHUXcQ
[youtube] Sleeping 1.0 seconds ...
[youtube] VYaUnjHUXcQ: Downloading webpage
[youtube] Saving request to VYaUnjHUXcQ_https_-_www.youtube.com_watchv=VYaUnjHUXcQ_bpctr=9999999999_has_verified=1.dump
[youtube] Sleeping 1.0 seconds ...
[youtube] VYaUnjHUXcQ: Downloading ios player API JSON
[youtube] Saving request to VYaUnjHUXcQ_https_-_www.youtube.com_youtubei_v1_playerkey=AIzaSyB-63vPrdThhKuerbB2N_l7Kwwcxj6yUAc_prettyPrint=false.dump
WARNING: [youtube] Skipping player response from ios client (got player response for video "aQvGIIdgFDM" instead of "VYaUnjHUXcQ"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] Sleeping 1.0 seconds ...
[youtube] VYaUnjHUXcQ: Downloading android player API JSON
[youtube] Saving request to VYaUnjHUXcQ_https_-_www.youtube.com_youtubei_v1_playerkey=AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w_prettyPrint=false.dump
WARNING: [youtube] Skipping player response from android client (got player response for video "aQvGIIdgFDM" instead of "VYaUnjHUXcQ"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "aQvGIIdgFDM" instead of "VYaUnjHUXcQ"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Invalid start time (315.0 > 300) for chapter "Ten Pines Bluff"
WARNING: [youtube] Invalid start time (370.0 > 300) for chapter "Police Station"
WARNING: [youtube] Invalid start time (420.0 > 300) for chapter "Ten Pines"
WARNING: [youtube] Invalid start time (470.0 > 300) for chapter "Opposite"
WARNING: [youtube] Invalid start time (535.0 > 300) for chapter "Boathouse"
WARNING: [youtube] Invalid start time (605.0 > 300) for chapter "Rubber and Aluminum"
WARNING: [youtube] Invalid start time (680.0 > 300) for chapter "Outro"
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by user: res:720, ext:webm:webm, fps:60
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:720(720.0), vext:webm(4), aext:webm(3), fps:60(60.0), quality, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] VYaUnjHUXcQ: Downloading 1 format(s): sb0
[info] Writing video description to: L:\ytdlp\meta\youtube\Deep Dive Gaming\desc\Deep Dive Gaming - 2022-09-23 - Video Not Available.description
[info] There are no subtitles for the requested languages
Deleting existing file L:\ytdlp\meta\youtube\Deep Dive Gaming\thumb\Deep Dive Gaming - 2022-09-23 - Video Not Available.webp
[info] Downloading video thumbnail 42 ...
[info] Writing video thumbnail 42 to: L:\ytdlp\temp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-09-23 - Video Not Available - [90p1].webp
[info] Writing video metadata as JSON to: L:\ytdlp\meta\youtube\Deep Dive Gaming\json\Deep Dive Gaming - 2022-09-23 - Video Not Available.info.json
[debug] Invoking mhtml downloader on "https://i.ytimg.com/sb/aQvGIIdgFDM/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiJycaTBg==&sigh=rs$AOn4CLA2u97YB314rQ3kWQRttMLzaGjCpw"
[download] Sleeping 13.85 seconds ...
[mhtml] Total fragments: 7
[download] Destination: L:\ytdlp\temp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-09-23 - Video Not Available - [90p1].mhtml
[download] 100% of   98.62KiB in 00:00:05 at 18.38KiB/s
[EmbedSubtitle] Skipping images
[Metadata] Skipping images
[EmbedThumbnail] Skipping images
[MoveFiles] Moving file "L:\ytdlp\temp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-09-23 - Video Not Available - [90p1].webp" to "L:\ytdlp\meta\youtube\Deep Dive Gaming\thumb\Deep Dive Gaming - 2022-09-23 - Video Not Available.webp"
[MoveFiles] Moving file "L:\ytdlp\temp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-09-23 - Video Not Available - [90p1].mhtml" to "L:\ytdlp\video\youtube\Deep Dive Gaming\Sim Settlements 2 by Kinggath and co#\Deep Dive Gaming - 2022-09-23 - Video Not Available - [90p1].mhtml"
[info] Writing '%(webpage_url_domain.:-4)s %(id)s     %(epoch-14400>%x-%I:%M:%S %p)s     %(uploader)s - %(upload_date>%Y-%m-%d)s - %(title)s' to: L:\ytdlp\download_log\Deep Dive Gaming [youtube].txt
[debug] Adding to archive: youtube VYaUnjHUXcQ
[info] Maximum number of downloads reached, stopping due to --max-downloads

**Comment by gamer191** [comment]
> It's not the working .mp4 thing though, I'll try to get logs/dumps if that happens again

post those in #8613, by the way

**Comment by SiXOTshRuTEr** [comment]
I thought that was closed so I posted here lol.  I do now have an example of a playable .mp4 with the "video not available".  I post those logs/dumps tonight after I get home from work.

**Comment by Trigger444** [comment]
### To anyone having this issue with getting a video or .mhtml file titled "Video Not Available"

**Use `--break-match-filters "title!*=Video Not Available"`
_This will stop YTDLP from downloading the garbage storyboard (sb0) format, and more importantly, prevent the actual video id from being erroneously added to your download archive_.**  

Otherwise, even though your video fails to download (you get the garbage file instead), it still gets added to the archive as if it were successful, and thus will be skipped when trying to download again.  This works best with a looping script, because it breaks the loop when it encounters a "Video Not Available", and restarts so it can re-extract the vids.

I had to use chatgpt to cobble together a powershell script to go through my archive file, and my custom download logs (that contain the video ID, uploader, title, etc.) and delete all the archive IDs that were actually failed downloads.  There were over 500 instances from my downloads over the past week or so.  If I didn't print my own download log file for each channel, it would be extremely difficult to manually identify all the affected vids and remove them from the archive.  I'd potentially just be missing hundreds of vids from channels I'm archiving.

Hopefully this info can help someone avoid some of the headaches I've had trying to figure this out haha.

**Comment by gamer191** [comment]
> **Use `--break-match-filters "title!*=Video Not Available"`**

I'd recommend using `-f "[ext!=mhtml]"` because "Video Not Available" just happens to be the name of youtube's current anti-downloader video (https://www.youtube.com/watch?v=aQvGIIdgFDM) and that could easily change in future

You could use both `-f "[ext!=mhtml]"` and `--break-match-filters "title!*=Video Not Available"` to be extra safe

**Comment by bashonly** [comment]
would this work? or side effects?
```diff
diff --git a/yt_dlp/YoutubeDL.py b/yt_dlp/YoutubeDL.py
index 8d96498a6..3292f242c 100644
--- a/yt_dlp/YoutubeDL.py
+++ b/yt_dlp/YoutubeDL.py
@@ -2452,7 +2452,7 @@ def selector_function(ctx):
                                 # for extractors with incomplete formats (audio only (soundcloud)
                                 # or video only (imgur)) best/worst will fallback to
                                 # best/worst {video,audio}-only format
-                                matches = formats
+                                matches = list(filter(lambda x: x.get('vcodec') != 'none' or x.get('acodec') != 'none', formats))
                             elif seperate_fallback and not ctx['has_merged_format']:
                                 # for compatibility with youtube-dl when there is no pre-merged format
                                 matches = list(filter(seperate_fallback, formats))
```

**Comment by Trigger444** [comment]
> _You could use both `-f "[ext!=mhtml]"` and `--break-match-filters "title!*=Video Not Available"` to be extra safe_

Reading through the documentation again I realized it says `!=` is for numeric fields, `!*=` for strings; so I think it should be 
`-f "[ext!*=mhtml]`, but neither way works for me.

The problem:  `-f "[ext!*=mhtml]` causes my `-S "res:720,ext:webm:webm,fps:60"` to be ignored, or breaks the sorting.  It downloads format 22, when my -S sorting should download 247+251 when available (and it is on the vids I'm testing).  The only thing the `-f` should be doing is EXCLUDING that one extension right?  I even tried `--format-sort-force`.  The `-f` option breaks it though, I'm probably missing something simple, but I don't know what.

**Comment by pukkandan** [comment]
@bashonly That works. You can merge
