### ISSUE TITLE
yt-dlp ignores my %HOME% variable and insist .netrc to be in my %USERPROFILE% folder

### ISSUE THREAD

**Issue by letmeindude** [yt-dlp/yt-dlp#792]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

Today I've switched from youtube-dl to yt-dlp and some of my videos stopped working. After inspection I've realized that yt-dlp ignores my %HOME% variable and insist .netrc to be in my %USERPROFILE% folder. Please fix this.

**Comment by glenn-slayden** [comment]
To be clear, the historical bug in Python, which they "fixed" in 3.8, is that `%HOME%` never should have been resolved on Windows in the first place (unless the user established it on their own, of course). I don't recall it ever being a sanctioned thing, at least since I went all-in with Windows 1.0, and even as a DOS/x86 (er, Commodore64?) dev way before that (Yikes).

refs:<br>https://superuser.com/a/607110/459921<br>https://referencesource.microsoft.com/#mscorlib/microsoft/win32/registrykey.cs,1290<br>https://referencesource.microsoft.com/#mscorlib/system/environment.cs,476<br>

**Comment by pukkandan** [comment]
I am aware. However, as some have pointed out in https://bugs.python.org/issue36264, windows users (including youtube-dl users) are used to setting %HOME% to change how `~` is treated. This is especially an issue since there was no other way to set the netrc path. Now that there is, it is not a big deal, but still better to have a consistent way to deal with this. We support python 3.6+ and the change was only made in 3.8. Without this patch, the netrc location will work inconsistently b/w python versions
