### ISSUE TITLE
Pyodide Websocket Issue

### ISSUE THREAD

**Issue by agieocean** [yt-dlp/yt-dlp#7940]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm trying to get yt-dlp working with [Pyodide](https://github.com/pyodide/pyodide). I'm able to import it after creating some custom wheels but when I actually try to run the following from the readme:

```
import json
import yt_dlp
    
URL = 'https://www.youtube.com/watch?v=BaW_jenozKc'
    
ydl_opts = {}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(URL, download=False)
    print(json.dumps(ydl.sanitize_info(info)))
```
I get this in the console in Firefox:
```
Firefox can’t establish a connection to the server at ws://www.youtube.com:443/.
```
Does anyone know how I can fix this? Should I bring this to the Pyodide devs instead?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
https://github.com/pyodide/pyodide/issues/375#issuecomment-481364649

> Networking in Python does not work, since it relies on low-level networking primitives (socket) that aren't allowed in the browser sandbox.

**Comment by agieocean** [comment]
Multiple libraries now enable networking including urllib3: [https://github.com/urllib3/urllib3/releases/tag/2.2.0](https://github.com/urllib3/urllib3/releases/tag/2.2.0), what libraries/protocols does yt-dlp use for networking? I'm willing to modify the source myself to enable pyodide functionality but need some guidance

**Comment by seproDev** [comment]
requests or urllib. However, due to CORS just about none of the websites/extractors will work. So this isn't something that could be used on a website.

For example, this happens if you make a request to YouTube in the Pyodide Repl:
![image](https://github.com/yt-dlp/yt-dlp/assets/4618135/e6cbaa95-4486-4391-acb4-aed7f1158fa4)

**Comment by ThatGuySam** [comment]
@seproDev What about Pyodide on a server? 

Cloudflare recently announced Python support for Workers via Pyodide: 
https://blog.cloudflare.com/python-workers

**Comment by seproDev** [comment]
You could probably make it work, I just don't really see a reason for why you would want to do that.

Due to the 50 subrequests limit, you can forget downloading fragmented media, which is used on most streaming sites nowadays.
You will also need to make ffmpeg work, which can run in wasm, but will probably be a pain to get running with yt-dlp in a cloudflare worker.
Another limiting factor will be the 10 ms cpu time, which I don't expect to be remotely enough.

In addition to that, you have the regular disadvantages of running yt-dlp on a server, namely that sites can and will easily block access based on the datacenter IP address.

If you want to run yt-dlp on a server why not just use a regular server with cpython instead of some severely limited maybe compatible python runtime.

**Comment by ThatGuySam** [comment]
That's totally valid that you can't do video processing on Workers without some crazy workarounds. 

I was more thinking of the value of things like `YoutubeDL.extract_info` and `--flat-playlist` so that you can easily hand off data and resource urls to other remote processes that will do the heavy lifting but aren't restricted to Python or a full server, an iOS app for example. 

Having a consistent API across most video platforms is a super awesome tool and there's still a lot of value even when it doesn't process any Video content. 

For me, I just like the ease, consistency, and security of the isolated serverless environments on each request.

**Comment by seproDev** [comment]
That could maybe work. I would still be worried about the 10 ms compute time as that is really not a whole lot.

Also keep in mind that some sites limit the actual media URLs to the IP adress that initially requested them, so just forwarding the URL/headers to a client might not work.

**Comment by seproDev** [comment]
In case anyone discovers this thread: I managed to get yt-dlp working in Pyodide, but as expected, it is not very useful: https://github.com/yt-dlp/yt-dlp/issues/9820#issuecomment-2166712378

**Comment by ThatGuySam** [comment]
@seproDev This is awesome! 

I feel this would still be useful for extracting urls on a cheap edge worker like Cloudflare
