### ISSUE TITLE
Option to include YouTube video ads in downloaded videos

### ISSUE THREAD

**Issue by 49studebaker** [yt-dlp/yt-dlp#7999]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is there a usage option that would allow the user to include YouTube video ads with the downloaded YouTube video?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
No

**Comment by 49studebaker** [comment]
Would it be difficult to add an option?

**Comment by gamer191** [comment]
May I ask why you'd want this?

**Comment by pesaventofilippo** [comment]
Youtube ads are not part of the video, they are dynamically served by youtube to you. Even if it would be possible to download ads (which you can technically do, as some ads are just unlisted youtube videos themselves), you can't know which ad youtube will serve to you.

Ads are not linked to a video, so with this feature downloading the same video two times could possibly result in two different files, which I don't think it's a good idea.
I don't even think it's possible to get an ad from youtube without actually loading the page using a browser, which yt-dlp doesn't do.

**Comment by gamer191** [comment]
> I don't even think it's possible to get an ad from youtube without actually loading the page using a browser, which yt-dlp doesn't do.

yt-dlp is meant to impersonate a browser, so that's not necessarily a problem. That sid, impersonating a browser to download ads could potentially be considered [click fraud](https://en.wikipedia.org/wiki/Click_fraud), which is illegal

I agree with the rest of your message though, and currently it's looking quite unlikely that this feature will be implemented



> downloading the same video two times could possibly result in two different files

Is that not already the case? I'd assume that yt-dlp's post-processing would make most output files unique anyway

**Comment by 49studebaker** [comment]
1) Advertising is how I find out about new products, services, etc. Public
service advertisements make people aware of critical issues.

2) YouTube has to make money. If people don’t watch the ads, advertisers
won’t advertise, YouTube could put their content behind a paywall.

**Comment by gamer191** [comment]
> 2) YouTube has to make money. If people don’t watch the ads, advertisers won’t advertise, YouTube could put their content behind a paywall.

If yt-dlp adds support for downloading ads, I imagine that a significant portion of the user base will download ads in order to support their favourite creators, and then not watch the ads. That would result in advertisers paying for views when no one's actually watching their ads, which would decrease the likelyhood of advertisers advertising on youtube. It would also likely get yt-dlp in trouble for [click fraud](https://en.wikipedia.org/wiki/Click_fraud).



> 1) Advertising is how I find out about new products, services, etc. Public service advertisements make people aware of critical issues.

This usecase could possibly be supported, because I'm sure it's possible to download ads without giving them views. I doubt it would be considered within the scope of this project though. Would you still want it if it's not gonna make youtube or creators any money

**Comment by 49studebaker** [comment]
Thanks for replying. You all make some good points.

I'll just watch the ads in the YouTube app before the video plays and then switch to the downloaded video. Ads load quickly on a slow mobile connection. I can avoid click fraud and support creators/YouTube.

**Comment by pukkandan** [comment]
> If yt-dlp adds support for downloading ads, I imagine that a significant portion of the user base will download ads in order to support their favourite creators, and then not watch the ads.

yt-dlp's downloads probably won't count as having watched ads. Similar to how downloading video doesn't mark it as watched.

> That would result in advertisers paying for views when no one's actually watching their ads

[Google themselves do that though](https://www.searchenginejournal.com/google-youtube-ads-invalid-placements/490301/)

---

Anyway, the whole premise of having yt-dlp "watch ads" on your behalf is flawed and won' be implemented

**Comment by gamer191** [comment]
> yt-dlp's downloads probably won't count as having watched ads. Similar to how downloading video doesn't mark it as watched.

I wasn't very clear. Downloading ads regularly would be OP's first use-case. Downloading ads, and spoofing a few API requests to mark the ads as "watched", would be OP's 2nd use-case. I was explaining why imo the 2nd use-case should never be implemented

On a side note, how are you going @pukkandan?
