### ISSUE TITLE
More a notification of possible future incompatibility.

### ISSUE THREAD

**Issue by jimlynnjulian** [yt-dlp/yt-dlp#8121]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Lately, I wonder if YouTube has engineered the video formats available. I tried downloading a 1947 movie and most versions had no audio, even webm. Those that did diffeered in that the files with audio, usually small resolution, had a constant bit rate and those with no audio, usually larger in resolution, had a variable bit rate. When I tried to import the audio from the smaller file into the larger file, the audio was lagging  by about a second by the end of the movie. 
i've always had problems matching video and audio between constant and variable bitrate files.
I wonder if this is the future and how YouTube plays the files without audio lag problems.

example:
https://www.youtube.com/watch?v=BiVj9wzL-7k

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
If you are having problems, share a log

> - [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> - [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

Without seeing a log, it sounds like you may not have ffmpeg installed. You can [get it here](https://github.com/yt-dlp/FFmpeg-Builds/releases/latest). This could potentially solve most/all of your problems

And also:

> most versions had no audio, even webm. Those that did diffeered in that the files with audio, usually small resolution, had a constant bit rate and those with no audio, usually larger in resolution

Youtube serves formats that are combined video+audio, but these max out at 720p.

Youtube also serves formats that are only video and formats that are only audio, that need to be merged afterwards. The video-only formats are the only way to get resolutions 1080p and above.

If you do not have ffmpeg installed, yt-dlp will automatically select the best pre-merged format (720p), since it knows it will not be able to merge separate video and audio formats.

If you want to specify a video-only format and an audio-only format to download, use the `-f` option with an argument format of `VIDEO+AUDIO`, e.g. `-f 137+140`

> When I tried to import the audio from the smaller file into the larger file, the audio was lagging

yt-dlp should merge video+audio **by default**, as long it detects your installation of ffmpeg

**Comment by jimlynnjulian** [comment]
Totally useless. Didn't pay attention. Canned response.

**Comment by bashonly** [comment]
If that's what you think, then you need to explain your issue more thoroughly. Sharing logs always helps.

**Comment by bashonly** [comment]
Nobody else has reported these issues, so produce evidence and useful information for the person trying to help you!

**Comment by jimlynnjulian** [comment]
If you had examined the given link in detail, vis a vi, the '-F' option you would discover not only does YouTube and yt-dlp download 1080p but that the example epitomizes the issue. 
In fact another point is where previously mp4 files were automatically dowloaded, now webm is usually downloaded. I think major changes are occurring.
The point is YouTube/Google may be taking a more aggressive approach to available downloads as well as converting to webm/VP9/Opus entirely. 
Logs do nothing in this instance as is obvious.
 If I get the time, I'll do a larger random sampling of YouTube videos as a check. 
 This not about me. This about yt-dlp and Google/YouTube. This not a request for help but a notification of possible upcoming difficulties and  changes. A warning of possible upcoming changes. You should take this more seriously. We're done.
