### ISSUE TITLE
Why not replacing voot.com by jiocinema.com yet ?

### ISSUE THREAD

**Issue by ETapk** [yt-dlp/yt-dlp#8154]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Sir, voot.com website no longer exists. All content of voot.com is now available on jiocinema.com so voot.com yt-dlp doesn't work either. How many more days can it take to fix it? Can you please give any hint on this matter?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
There is already an issue tracking voot's removal, #7759, and an issue tracking support for jio, #5563

Please do not open new issues to inquire on the status

Since you asked though, here is the status: 
The Jio site has A LOT of problems, and since they recently started switching their non-DRM formats to AES-128 encrypted HLS streams ***without*** uploading keys, it's looking like support may never be added
