### ISSUE TITLE
[Broken] Unable to download any videos from ITV 

### ISSUE THREAD

**Issue by Nick-Payne** [yt-dlp/yt-dlp#861]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running yt-dlp version **2021.09.02**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ yt-dlp -v https://www.itv.com/hub/snooker-british-open-championship/10a1758a0013
[debug] Command-line config: ['-v', 'https://www.itv.com/hub/snooker-british-open-championship/10a1758a0013']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.9.2 (CPython 32bit) - Linux-5.10.60-v7l+-armv7l-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] Using fake IP 25.198.42.13 (GB) as X-Forwarded-For
[debug] [ITV] Extracting URL: https://www.itv.com/hub/snooker-british-open-championship/10a1758a0013
[ITV] 10a1758a0013: Downloading webpage
[ITV] 10a1758a0013: Downloading JSON metadata
ERROR: [ITV] 10a1758a0013: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 693, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3218, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Attempting to use yt-dlp to download any video from ITV give the error log above. Tried three different programs with the same error on each of them. They all play OK when accessing the ITV hub website in a web browser.

**Comment by coletdjnz** [comment]
Related with details: https://github.com/ytdl-org/youtube-dl/issues/28906
Pending upstream PR, supposedly fixes the above and this: https://github.com/ytdl-org/youtube-dl/pull/28955

Also related: https://github.com/ytdl-org/youtube-dl/issues/29620, https://github.com/ytdl-org/youtube-dl/issues/29337, https://github.com/ytdl-org/youtube-dl/issues/29190, https://github.com/ytdl-org/youtube-dl/issues/29034, ... https://github.com/ytdl-org/youtube-dl/issues?q=ITV :sweat_smile:

**Comment by pukkandan** [comment]
I see you are not passing cookies. But when I try to open the link in browser, it asks me for login details. Is an account needed to access this?

**Comment by Nick-Payne** [comment]
Yes, you need an account to access the ITV hub in a web browser. But you don't need one when passing the video URL to yt-dlp.

**Comment by Vangelis66** [comment]
@coletdjnz wrote: 

> Upstream issue: [ytdl-org/youtube-dl#28906](https://github.com/ytdl-org/youtube-dl/issues/28906)

FWIW, **I** was the one that dissected the `itv.py` breakage and figured out why it broke and what had to be done to get it working again, read [this comment](https://github.com/ytdl-org/youtube-dl/issues/28906#issuecomment-831008270)...
As you know already, I can't code myself 😊 , but an actual coder (the author of that [PR](https://github.com/ytdl-org/youtube-dl/pull/28955)) did what had to be done... 👍 
Actually, a fixed `itv.py` was in urgent need in the context of [another app](https://github.com/Ascoware/get-iplayer-automator) (on MacOS) using it for ITVHub fetches... 😉 

> Pending upstream PR, **supposedly** fixes the above

... Not "supposedly", it **definitely** fixes `itv.py` 🥇 
Since some months ago (this is actually PR#28955 take **2**, take **1** being [this](https://github.com/ytdl-org/youtube-dl/commit/5019b2e)), I am locally compiling `yt-dlp_x86.exe` with that patched `itv.py` extractor, and I can verify it WORKS! 🎉 

Thing to watch when using `itv.py`: 
The ITVHub service is **fully geo-fenced** (i.e. both the HLSe playlist generating API as well as the stream CDNs), so you need a **whitelisted** UK VPN/HTTPS proxy/SSH tunnel/SmartDNS etc. to successfully test/fetch from overseas...

@pukkandan wrote: 

> But when I try to open the link in browser, it asks me for login details. 
> Is an account needed to access this? 

... Unfortunately, **desktop browsers** are being served **cenc** (DRM'd) MPEG-DASH streams (IE11/Win10 gets PlayReady DRM), so these "browser" streams are no good for `yt-dlp` purposes...
In reality, the only exploitable ITVHub endpoint is **HLSe** (AES-128) streams targeting old iOS devices, this endpoint might get removed at any future time and, sadly, that would signal the death of `itv.py` ... 😭 

Best greetings, thanks for your efforts! 😃

**Comment by coletdjnz** [comment]
I've copied over the PR into #913. If someone can confirm that it is working, that would be great. On my VPN I am getting 403s when using it so I am assuming it is blocked :/

**Comment by Vangelis66** [comment]
> If someone can confirm that it is working, that would be great.

See [my comment](https://github.com/yt-dlp/yt-dlp/pull/913#issuecomment-914589364) inside your PR... 😃
