### ISSUE TITLE
Feature request: throw an error when receiving a player response for a different YouTube video ID

### ISSUE THREAD

**Issue by Flopblopper** [yt-dlp/yt-dlp#8613]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Example URLs

https://www.youtube.com/watch?v=vnSYKl78PXQ

### Provide a description that is worded well enough to be understood

In certain, rare situations, Google may block an IP address from accessing video information, and send the player response for an alternative video ID (usually "M5t4UHllkUM".
The way Yt-dlp currently handles this is to display a warning, but continue to download the incorrect video.
I believe that this should be treated as an error, so that the --abort-on-error flag would bring the problem to our attention. I wouldn't have noticed the problem if I hadn't glanced over at my screen where the downloads were running.

I apologize for not being able to provide verbose output. I am unable to reproduce what happened, because Google is no longer blocking my IP address. I will provide the warning that YT-dlp displays when this happens.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "vnSYKl78PXQ")
```

**Comment by gamer191** [comment]
> The way Yt-dlp currently handles this is to display a warning, but continue to download the incorrect video.

Did yt-dlp actually download an incorrect video? I could be wrong, but I'm pretty sure yt-dlp's current behaviour is to discard the inaccurate player response, and proceed to try the next player

**Comment by Flopblopper** [comment]
I'd gathered from the output that skipping the bad response was the intended behavior, but Yt-dlp did in fact download the incorrect video. The file name listed the title as "Video Not Available", which is the title of the bad response. The video ID listed in the file name was the correct one.

**Comment by dirkf** [comment]
You could trap the bad video in some `--exec-... ...` option but I can see that automatically catching the issue could be better. Are there any cases when YT would correctly send a response for a video with a different ID from the originally requested video?

**Comment by SiXOTshRuTEr** [comment]
I've been having this problem a lot over the past week or so.  I may be able to get some verbose log output later.

One night last week I had many ytdlp instances running overnight, maybe too many lol.  Checked the channel folders in the morning to find a bunch of "video not available" files.  First time I ever saw this happen.  I use a vpn also, maybe some IPs are banned?  If I was IP banned though, **_nothing_** should download correctly at all though right?  Maybe YT is changing things on the backend again?

There were random failed videos in between many successful ones though.  Most of the failed ones were "video not available.mhtml" in some storyboard format apparently, but a few were actually working .mp4 (of the correct video), just incorrectly named as "video not available".  Something is up though because trying to run a simple ytdlp command, that only prints the video title, will fail with that same "skipping player response" and wrong id.  Yet I can actually download the video itself, or if it messes up with the "video not available" issue, it seems to work properly if I try again.

Another issue though is that the wrong named files count as successful in the archive; even the failed .mhtml files count as successful downloads.  I print-to-file my own download log per channel, so I can quickly identify the incorrect downloads and their id, date, title etc.  This is still very annoying, to have to manually delete those from the archive file.

**Comment by pukkandan** [comment]
> Most of the failed ones were "video not available.mhtml" in some storyboard format apparently,

This is due to https://github.com/yt-dlp/yt-dlp/issues/7715. I'll try to get this one fixed asap



> but a few were actually working .mp4 (of the correct video), just incorrectly named as "video not available".

We would need to see verbose log and maybe even `--write-pages` dumps to see what's going on

**Comment by dirkf** [comment]
But https://github.com/yt-dlp/yt-dlp/issues/8613#issuecomment-1817655832 ?

**Comment by gamer191** [comment]
> But [#8613 (comment)](https://github.com/yt-dlp/yt-dlp/issues/8613#issuecomment-1817655832) ?

**Comment by gamer191** [comment]
Apologies for closing and re-opening this issue, Github mobile sucks
Anyway @Flopblopper most likely also downloaded a .mhtml file, in which case this is a duplicate of https://github.com/yt-dlp/yt-dlp/issues/7715. But we'd need confirmation from them

**Comment by Flopblopper** [comment]
Unfortunately, I deleted the files after I noticed the problem, so I'm really not sure. In any case, it's probably safe to assume that this is a duplicate, at least until I can make it happen again and capture a verbose log.

**Comment by Trigger444** [comment]
### To anyone having this issue with getting a video or .mhtml file titled "Video Not Available"

**Use `--break-match-filters "title!*=Video Not Available"`
_This will stop YTDLP from downloading the garbage storyboard (sb0) format, and more importantly, prevent the actual video id from being erroneously added to your download archive_.** 

I posted a little more info here:
https://github.com/yt-dlp/yt-dlp/issues/7715#issuecomment-1828967853
