### ISSUE TITLE
mkv/vp09 playing audio only on TV

### ISSUE THREAD

**Issue by jimlynnjulian** [yt-dlp/yt-dlp#8652]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm not sure whether this is a mkvmerge (mkvtoolnix suite) issue or a yt-dlp issue, 
but when I download in mp4 format and get a vp09 codec, and convert to mkv with the following commandline, my tv will play audio only.
According to the manufacturer, the TV will play VP09 when in an mkv container.

convert from mp4/VP09 to mkv
find . -name "*.mp4" -exec bash -c 'for f; do mkvmerge --output "${f%.*}.mkv" "$f";done' -- {} +

Initial download commandline:
yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" https://www.youtube.com/playlist?list=PLU0HyYmOgH8Xn06fDThwLDh95igfZpurQ

Work around:
yt-dlp  -S vcodec:h264,res,acodec:m4a -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" https://www.youtube.com/playlist?list=PLU0HyYmOgH8Xn06fDThwLDh95igfZpurQ

The above is a playlist. A single file from the playlist that returns an mp4 with a VP09 codec:
https://www.youtube.com/watch?v=U6JsfDIo4TA

Any ideas?

Thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
It seems more like a TV issue than anything else: vp9-in-mkv is not playing on your TV despite what the manufacturer says. You've already found a workaround (preferring h264 in mp4); I don't know what else we could help with based on the information you've provided

**Comment by jimlynnjulian** [comment]
1. The originator of the mkv format has stated several times, a lot of software does not implement mkv correctly. 
2. I trust the manufacturer, LG, more than I trust yt-dlp, if that's the issue. 
3. Hiding one's head in the sand is no help.
4. Rots o' Ruck.

**Comment by seproDev** [comment]
I am not sure what you want right now.
yt-dlp does not implement anything related to mkv. The only thing yt-dlp does is extract the download URL from the website, download the file, and (if requested to do so) instruct FFmpeg to merge them.

You then used mkvmerge to mux this in to a single mkv file, which is the de-facto reference implementation of a Matroska multiplexer.
I think it is far more likely that LG implemented something related to MKV or VP9 incorrectly, than this being a mkvmerge issue.
It could also be that Google is serving weird files, but since other players can play them back fine, this would also be an LG issue. Historically, TVs have been quite bad at support for different containers and codecs.

We neither know the model of TV you have, nor do we have access to it.
If you want to debug this on your own, here are some suggestions for things to try:
 - Do VP9 files not downloaded from YouTube play fine? 
 - Do the files play fine if you use a different multiplexer?
 - Does VP9 in WebM work? (WebM is a subset of MKV)

**Comment by jimlynnjulian** [comment]
The original is an mp4 with VP9. Since the LG TV does not state mp4/VP9 will play, there's not much else to do.
As you mentioned, I have a solution, so that's where things will have to stand, but the unresolved problem leaves  me piqued. I do not know of a different multiplexer and since the one I use is the standard, others are not likely to be of any help. Webm and Opus are not on LG's list of supported formats.
I have a solution and I'm just going to go with that.
Thanks for your efforts.
Happy holidays.
Jim Julian

**Comment by bashonly** [comment]
`--merge-output-format mkv`
