### ISSUE TITLE
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by  HTTPError 403: Forbidden ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### ISSUE THREAD

**Issue by Gittu2raj11** [yt-dlp/yt-dlp#8785]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by  HTTPError 403: Forbidden ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by  HTTPError 403: Forbidden ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by dirkf** [comment]
>[x] Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>)

Posting that output is the minimum needed for anyone to help you.

**Comment by special3543** [comment]
bash: yt-dlp "https://www.youtube.com/watch?v=Grk70fc1FHs" -f bestaudio --audio-quality 1 -o "test.mp3"


Same issue, logs like this:


[youtube] Extracting URL: https://www.youtube.com/watch?v=Grk70fc1FHs
[youtube] Grk70fc1FHs: Downloading webpage
[youtube] Grk70fc1FHs: Downloading ios player API JSON
[youtube] Grk70fc1FHs: Downloading android player API JSON
[youtube] Grk70fc1FHs: Downloading m3u8 information
[info] Grk70fc1FHs: Downloading 1 format(s): 251
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by barsnick** [comment]
> bash: yt-dlp "https://www.youtube.com/watch?v=Grk70fc1FHs" -f bestaudio --audio-quality 1 -o "test.mp3"

This command line is not sufficient:

> > [x] Run your yt-dlp command with -vU flag added (yt-dlp -vU )
> 
> Posting that output is the minimum needed for anyone to help you.

Please add "-vU". and post the complete output.

BTW, works for me. (And note that, with your command line, the output file will not be an MP3 file.)
```
$ yt-dlp -Uv https://www.youtube.com/watch?v=Grk70fc1FHs -f bestaudio --audio-quality 1 -o "test.mp3"
[debug] Command-line config: ['-Uv', 'https://www.youtube.com/watch?v=Grk70fc1FHs', '-f', 'bestaudio', '--audio-quality', '1', '-o', 'test.mp3']
[debug] User config "/home/barsnick/.config/yt-dlp/config": ['-o', '%(title).200B [%(extractor)s %(id)s].%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.0 (CPython x86_64 64bit) - Linux-6.6.6-200.fc39.x86_64-x86_64-with-glibc2.38 (OpenSSL 3.1.1 30 May 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1, phantomjs 1.9.8
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.46.0, requests-2.31.0, sqlite3-3.42.0, urllib3-1.26.18, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Plugin directories: ['/home/barsnick/.config/yt-dlp/plugins/barsnick/yt_dlp_plugins']
[debug] Loaded 1908 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=Grk70fc1FHs
[youtube] Grk70fc1FHs: Downloading webpage
[youtube] Grk70fc1FHs: Downloading ios player API JSON
[youtube] Grk70fc1FHs: Downloading android player API JSON
[youtube] Grk70fc1FHs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Grk70fc1FHs: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr1---sn-iu2-i5we.googlevideo.com/videoplayback?expire=1702910096&ei=MASAZaCAJPKg6dsPj4Sq-AM&ip=2a02%3A560%3A52ec%3A5100%3Aecd8%3A6b88%3A60be%3Acc25&id=o-AGoPpu4-xMuiptQq8IEkd6h2GeTTHdrtx5fVPbbI7Fla&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=es&mm=31%2C29&mn=sn-iu2-i5we%2Csn-4g5edndy&ms=au%2Crdu&mv=m&mvi=1&pl=32&initcwndbps=2108750&spc=UWF9f6vGboXAA_aJMzTp1UwKrT9X6oE&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=250814&dur=22.301&lmt=1609591394724259&mt=1702888166&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAIU_9nAdceyx5A32daCLzObOJDR2lJveSGtHZKt9MOOuAiASmKuTurmke-PhtdXkd85x6q3um2sCGfuUDQm09ZsO_g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRAIgeI_674VWIaucVPN7IiO6t0q0Iu8ngf7_OxbkJTIDim0CIEqUA0Pipv4DBbmSsbD-eos1pINM-XECdnYAU57jT8iI"
[download] Destination: test.mp3
[download] 100% of  244.94KiB in 00:00:00 at 1.18MiB/s
```

**Comment by special3543** [comment]
ubuntu@xxx~$ yt-dlp -Uv https://www.youtube.com/watch?v=Grk70fc1FHs -f bestaudio --audio-quality 1 -o "test.mp3"
[debug] Command-line config: ['-Uv', 'https://www.youtube.com/watch?v=Grk70fc1FHs', '-f', 'bestaudio', '--audio-quality', '1', '-o', 'test.mp3']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-1017-aws-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=Grk70fc1FHs
[youtube] Grk70fc1FHs: Downloading webpage
[youtube] Grk70fc1FHs: Downloading ios player API JSON
[youtube] Grk70fc1FHs: Downloading android player API JSON
[youtube] Grk70fc1FHs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Grk70fc1FHs: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr4---sn-5hne6ns6.googlevideo.com/videoplayback?expire=1702912620&ei=DA6AZdWeNM2p1gLrprbwCQ&ip=3.126.111.181&id=o-AIHbBFqbyfZHTlKTHkmf7V7BaM2SDq7vWnj8ed6kP9e6&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=es&mm=31%2C26&mn=sn-5hne6ns6%2Csn-4g5edndy&ms=au%2Conr&mv=u&mvi=4&pl=23&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=250814&dur=22.301&lmt=1609591394724259&mt=1702890804&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAKWJ-nIEqNv8oRQpY28JArsyFIdwNy4blN-apjS2jYZsAiEAtWsx8LWcYBTAc9MytzTZyHNzUvOuk212H5a57ErPNr4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AAO5W4owRQIgMGP-d6QN8_WdtwnP0ym2NjjpPgm6MX6IrjLgvQ53ZMUCIQCI9yygGSP62HhdpB9BEjJ6yxZRq_3iObgomPnxoXNXgw%3D%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4052, in urlopen
    return self._request_director.send(req)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_requests.py", line 341, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3388, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3109, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 364, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4074, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

Thank you for the return. The logs are like this. I decided to write my own extract tool, but I still shared it in case it might be useful. Because it was working like this before without any problems.

**Comment by bashonly** [comment]
@special3543 your issue is #7860

**Comment by nankepan** [comment]
> Update on this, i changed my server's ip then i've been able to download. I believe api banned me. I dont know why this happened but i believe there is limitation for download rate.
> 
> Edit: I created tool which i told u with pytube. Same thing happened then i figured it out.

Hi, could you tell me how to change my server's ip? Thank you very much!
