### ISSUE TITLE
[Feature Request] playlist_uploader fallback to video uploader

### ISSUE THREAD

**Issue by shakeyourbunny** [yt-dlp/yt-dlp#899]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Would it be possible to add to the output template a fallback to the %(playlist_uploader)s variable that contains the uploader / channel name if yt-dlp yields "NA"? Maybe with a switch --playlist-uploader-fallback-to-uploader or something similiar?

**Comment by pukkandan** [comment]
I don't understand the question. Can you elaborate a bit more? possibly with example

**Comment by pukkandan** [comment]
Closed due to inactivity

**Comment by 1sixth** [comment]
> I don't understand the question. Can you elaborate a bit more? possibly with example

I think I run into the same issue and can elaborate more.

What the OP wants is probably the ability to use a differenet field when the original field is `NA`. Currently, we can specify a default value when the field is empty, e.g. `%(uploader|Unknown)s`, where `Unknown` is just a fixed string, not another field.

For example, If I do
```
yt-dlp -o '%(playlist_uploader)s %(title)s.%(ext)s' 'https://www.youtube.com/playlist?list=PLi9drqWffJ9FWBo7ZVOiaVy0UQQEm4IbP`
```

Then everything is fine. There isn't any `NA` in the output files. However, if I do
```
yt-dlp -o '%(playlist_uploader)s %(title)s.%(ext)s' 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
```
The output would be like `NA Rick Astley - Never Gonna Give You Up (Official Music Video).mkv`, which is kind of annoying because of the `NA`.

It's possible to use different `--output` settings for playlists and videos and call it a day, but I run into a case where I can't tell from the URL if I'm downloading a playlist or a video (before actually doing it), so it would be convenient to have this feature in yt-dlp.

**Comment by pukkandan** [comment]
Thanks for the explaination. Now I understand what you guys mean.

When I created the `|` operator, I thought about allowing field names in it. But I could not figure out a syntax to allow both field names and constants at the same time (`%(field1|%(field2)s const)s` is both extremely difficult to implement and to use). So I decided to go with constants for the time being. I would like to hear if anyone had ideas for a syntax that can do this (it should not use `)`)

Right now, what you can do is to use `--parse-metadata` to replace `uploader` with `playlist_uploader` if it is a playlist and then just use `uploader` in the output template
```
--parse-metadata '%(playlist_uploader|)s:%(uploader)s'
-o '%(uploader)s %(title)s.%(ext)s'
```

**Comment by Ashish0804** [comment]
> I would like to hear if anyone had ideas for a syntax that can do this (it should not use `)`)

How about comma separated values?
`%(field1,field2|const)s`

**Comment by pukkandan** [comment]
that could work. Let me see if it can be done

**Comment by pukkandan** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/7c37ff97d3b95444ece7e7da2da6f03293003df3, `%(playlist_uploader,uploader)s` will work
