### ISSUE TITLE
[suggestion] fallback to pycryptodomex

### ISSUE THREAD

**Issue by pirate486743186** [yt-dlp/yt-dlp#935]
There was a packaging error in debian.
the package pycryptodome, actually installs pycryptodomex
and pycryptodome doesn't exist in the repo.

I suggest switching to pycryptodomex

- if i understand correctly, pycryptodome is there for backwards compatibility.
- it will allow yt-dlp fully functioning in debian/ubuntu
- it will reduce the confusion

**Comment by sulyi** [comment]
If I understand correctly only difference is:
case of pycryptodome all modules are installed under the `Crypto` package, (therefore conflicts with PyCrypto),
case of pycryptodomex  all modules are installed under the `Cryptodome` package.

As immediate change this'd requires:
https://github.com/yt-dlp/yt-dlp/blob/bc78ff8becc70c36ee47a6bbafe7873b3335f0d9/requirements.txt#L2
https://github.com/yt-dlp/yt-dlp/blob/691d5823d6ff72b813eb34ede8009b70bebd73da/yt_dlp/downloader/external.py#L9-L13
https://github.com/yt-dlp/yt-dlp/blob/25a3f4f5d6de2bd5fb60cd11a46f0ac232882a56/yt_dlp/downloader/fragment.py#L7-L11
https://github.com/yt-dlp/yt-dlp/blob/bc78ff8becc70c36ee47a6bbafe7873b3335f0d9/yt_dlp/cookies.py#L35-L39

probably, +clarification in messages/doc, etc...

**Comment by nyuszika7h** [comment]
To minimize breakage it could also try to import both and just alias it. But I would think Debian would treat such a bug as important enough to fix it.

**Comment by sulyi** [comment]
I'd suggest using `aes` module instead, and dropping pycryprodome dependency, since no other primitive provided by it is used.

**Comment by pirate486743186** [comment]
aes module is part of the standard install?
it isn't better to use the aes module to reduce the dependence on pycryptodome?
gcm is used only for cookies?

@nyuszika7h
You'll wait a long time, 3 Jan 2018
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886291

**Comment by nyuszika7h** [comment]
You mean it was reported 3 years ago and it still wasn't fixed for Debian 11? I thought this was something recent that they could push a fix for to the debian-updates repo, but if they ignored it even for the next stable release that's unfortunate.

**Comment by sulyi** [comment]
> reported 3 years ago and it still wasn't fixed for Debian 11

That's not uncommon sadly.
> aes module is part of the standard install?

No it is part of `youtube-dl` and `yt-dlp` as of now. It can be argued that it is unnecessary to avoid dependencies, but in any case it should  be consistent.
> gcm is used only for cookies?

Yes, `external` and `fragment` needs cbc, witch are already available in `aes`.

**Comment by pukkandan** [comment]
Replacing `pycryptodome` with `pycryptodomex` is out of the question. This could break the setups of anyone who is already using the old PyCrypto or more importantly, the recommended pycrptodome module. We could try to import both, but honestly, the issue is with debian and not us. That said, since this is trivial to implement, I'll do it anyway. But note that I do not want to encourage requests for this kind of patches

`cookies.py` needs pycryptodome since we don't have a native implementation of gcm. But as for `fragment.py`, it seems to use Crypto only because the native cbc was implemented much later (Ref: https://github.com/yt-dlp/yt-dlp/commit/c9619f0a17927086c49e4b443202be296d734a76, https://github.com/yt-dlp/yt-dlp/commit/e154c65128305fcaf6c6b2d5fd41ecd83e4ec154). I am not sure if there would be any caveat to using the native decrypter over Crypto, but seems unlikely. What do u think, @shirt-dev?

**Comment by sulyi** [comment]
> `cookies.py` needs pycryptodome since we don't have a native implementation of gcm
Yet, #938 .

**Comment by shirt-dev** [comment]
Should be fine to switch it, they're literally the same module but with a different name for importing.

**Comment by pukkandan** [comment]
> But as for fragment.py, it seems to use Crypto only because the native cbc was implemented much later (Ref: c9619f0, e154c65). I am not sure if there would be any caveat to using the native decrypter over Crypto, but seems unlikely

I was asking about this part @shirt-dev

**Comment by pirate486743186** [comment]
debian is a big ass distribution in the linux world, with a lot of influence. I think you should bend over backwards to accommodate their bugs.
I understood that pycryptodome was for backwards compatibility while pycryptodomex was the future. So moving to x is not extravagant.

**Comment by sulyi** [comment]
> should bend over backwards to accommodate their bugs
No, I'll will do so to be able to drop their dependency, thou.

**Comment by pukkandan** [comment]
> debian is a big ass distribution in the linux world, with a lot of influence. I think you should bend over backwards to accommodate their bugs.

It is the packager's responsibility to "bend over backwards" for any issues in the packaging system. You can always just install the necessary packages with pip

**Comment by nao20010128nao** [comment]
`compat_Crypto_Cipher_AES` `compat_CRYPTO_AVAILABLE`

**Comment by shirt-dev** [comment]
> > But as for fragment.py, it seems to use Crypto only because the native cbc was implemented much later (Ref: [c9619f0](https://github.com/yt-dlp/yt-dlp/commit/c9619f0a17927086c49e4b443202be296d734a76), [e154c65](https://github.com/yt-dlp/yt-dlp/commit/e154c65128305fcaf6c6b2d5fd41ecd83e4ec154)). I am not sure if there would be any caveat to using the native decrypter over Crypto, but seems unlikely
> 
> I was asking about this part @shirt-dev

Oh, I would recommend using cryptodome due to hardware accelaration

**Comment by pirate486743186** [comment]
even without the hardware acceleration, the core functionality is in C, not raw python.
@sulyi 
And so, it"s a bad idea to drop the dependency.

pycryptodomex is not an invention of debian. It seams the original intention was to be able to install pycrypto and pycryptodomex at the same time. I would say then that it's indeed a bug in yt-dlp that it doesn't recognize  pycryptodomex.

also the native cbc was implemented in 2017, it might be an outdated workaround.

**Comment by sulyi** [comment]
> even without the hardware acceleration, the core functionality is in C, not raw python.

I don't think this will be an issue. I haven't profiled it, but I guess call count to be low.
> might be an outdated workaround

 Please, prove it first, and if so show how to fix it.

**Comment by pirate486743186** [comment]
i side tracked my self...
i don't understand the code, so i can't say what's the best solution.
the native implementation is suspiciously old and redundant, so you guys should investigate if it's still relevant.

If you use pycryptodome, then also add pycryptodomex as a fallback since they are exactly the same. pycryptodomex was created by the pycryptodome project, so both are valid.

**Comment by sulyi** [comment]
Working on [`aes.py`](https://github.com/yt-dlp/yt-dlp/blob/c3094017b0da54eaab46bf2e869f20d426be35f4/yt_dlp/aes.py) my only complain about it is that it uses `list` of `int`s instead of `bytes`. This  is probably due to PEP 358 and `youtube-dl` supporting python 2.6 formerly.

For now I'll keep with the convention of existing code, but I do agree, that it would benefit from an overhaul, using OOP design.

I'm entirely sure about every part of the code, but `aes_cbc_decrypt` seems to be popular. It has way better ratio of code usage than pycryptodome, that I'm sure of. Another reason to drop it after #938 is done.

**Comment by sulyi** [comment]
It turned out to be more like a fallthrough: pycryptodome > pycryptodomex > native, but still will fix issue.
