### ISSUE TITLE
Release tarball yt-dlp.tar.gz does not contain that release's Changelog.md entries

### ISSUE THREAD

**Issue by ryandesign** [yt-dlp/yt-dlp#9417]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am the maintainer of yt-dlp in MacPorts and while working on updating to 2024.03.10 I noticed that the file [yt-dlp.tar.gz](https://github.com/yt-dlp/yt-dlp/releases/download/2024.03.10/yt-dlp.tar.gz) attached to the 2024.03.10 release does not contain entries in Changelog.md for the 2024.03.10 release, yet they are in the repository. The newest entries in that file are for the previous 2023.12.30 release. The correct Changelog.md entries are available in the automatically-generated [2024.03.10.tar.gz](https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2024.03.10.tar.gz) file but of course I want to use your manually-prepared tarballs instead.

Similarly, the [yt-dlp.tar.gz](https://github.com/yt-dlp/yt-dlp/releases/download/2023.12.30/yt-dlp.tar.gz) attached to the 2023.12.30 release does not have Changelog.md entries for the 2023.12.30 release; the newest entries there are for the 2023.11.16 release.

This makes me wonder what other changes that were intended for each release are missing from its tarball.

Is there perhaps a bug in the process that generates each release's tarball such that it is not being made from the intended commit?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A
```

**Comment by bashonly** [comment]
Oops. Thanks for reporting this, since this problem has apparently gone unnoticed for [over a year](https://github.com/yt-dlp/yt-dlp/releases/download/2023.03.03/yt-dlp.tar.gz).

> Is there perhaps a bug in the process that generates each release's tarball such that it is not being made from the intended commit?

The changelog is updated in the master branch in the ["release commit"](https://github.com/yt-dlp/yt-dlp/commit/8463fb510a58050ec118b3ae17bf00d08ea7b881), which is actually pushed during the [release workflow](https://github.com/yt-dlp/yt-dlp/blob/master/.github/workflows/release.yml). The [build workflow](https://github.com/yt-dlp/yt-dlp/blob/master/.github/workflows/build.yml), however, operates on the commit that it was triggered for, which is the commit preceding the "release commit" (since that is made during the workflow itself). So it has been packing the previous release's changelog into the tarball.

We will either need to somehow correct which commit the build workflow operates on, or separately update the changelog during the tarball build job.

> This makes me wonder what other changes that were intended for each release are missing from its tarball.

As far as I can tell it is only the changelog. The only other potential missing changes would be found in the [release commit](https://github.com/yt-dlp/yt-dlp/commit/8463fb510a58050ec118b3ae17bf00d08ea7b881), but `CONTRIBUTORS.md` and `supportedsites.md` are updated separately by the Makefile during the tarball build job, and `version.py` is updated during every build job.

**Comment by Emmo00** [comment]
Hi,

I'd like to work on this, but I'd like to hear your thoughts on how you might like to implement a fix.

And are we going to do anything about the previously generated `changelog.md` files?

**Comment by bashonly** [comment]
> I'd like to work on this, but I'd like to hear your thoughts on how you might like to implement a fix.

Started working on this last night and I have a draft up now, #9425

> And are we going to do anything about the previously generated `changelog.md` files?

IMO no, since uploading new release assets would break downstream packagers' integrity checks

**Comment by Emmo00** [comment]
Ok 👍🏻

**Comment by bashonly** [comment]
The next stable release's tarball and source distribution will have properly updated changelogs.

Already fixed in tonight's nightly/dev release:
- https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.03.14.232657/yt-dlp.tar.gz
- https://files.pythonhosted.org/packages/4e/9f/02e491740c4e2922ecf13f4a3002e66899708b655d754d1c4dccdc6b09a6/yt_dlp-2024.3.14.232657.dev0.tar.gz
