### ISSUE TITLE
Afreecatv Failed to parse XML

### ISSUE THREAD

**Issue by syazyz** [yt-dlp/yt-dlp#9544]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

The afreecatv website has just stopped working since six hours ago. There is the prompt:

yt-dlp https://vod.afreecatv.com/player/117026071
[afreecatv] Extracting URL: https://vod.afreecatv.com/player/117026071
[afreecatv] 117026071: Downloading JSON metadata
Extracting cookies from firefox
Extracted 1509 cookies from firefox
[afreecatv] 117026071: Downloading video info XML
ERROR: [afreecatv] 117026071: 117026071: Failed to parse XML (caused by ParseError('no element found: line 1, column 0')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vod.afreecatv.com/player/117026071']
[debug] Portable config "C:\Users\syazyz\scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Home config "yt-dlp.conf": ['--proxy', 'socks5://127.0.0.1:7888', '--merge-output-format', 'mkv', '--continue', '-o', '%(uploader)s\\%(upload_date)s - %(title)s.%(ext)s', '--no-check-certificate', '--prefer-insecure', '--user-agent', 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', '--concurrent-fragments', '3', '--cookies-from-browser', 'firefox:C:/GreenSoft/System/Profiles/FFP', '--downloader-args', 'ffmpeg_i:-hwaccel cuda -c:v vp9_cuvid']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.22.222728 from yt-dlp/yt-dlp-master-builds [e5d4f1110] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-03-20-git-e04c638f5f-full_build-www.gyan.dev (setts), ffprobe 2024-03-20-git-e04c638f5f-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {'all': 'socks5://127.0.0.1:7888'}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\GreenSoft\System\Profiles\FFP\cookies.sqlite"
Extracted 1514 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.22.222728 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.22.222728 from yt-dlp/yt-dlp-master-builds)
[afreecatv] Extracting URL: https://vod.afreecatv.com/player/117026071
[afreecatv] 117026071: Downloading JSON metadata
[afreecatv] 117026071: Downloading video info XML
ERROR: [afreecatv] 117026071: 117026071: Failed to parse XML (caused by ParseError('no element found: line 1, column 0')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\afreecatv.py", line 202, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1056, in download_handle
  File "yt_dlp\extractor\common.py", line 1046, in parse
  File "yt_dlp\extractor\common.py", line 1026, in _parse_xml
  File "yt_dlp\extractor\common.py", line 1016, in __print_error

  File "yt_dlp\extractor\common.py", line 1024, in _parse_xml
  File "yt_dlp\compat\__init__.py", line 24, in compat_etree_fromstring
  File "xml\etree\ElementTree.py", line 1321, in XML
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

**Comment by capillarys** [comment]
i'm having the same issue as well, region: europe

`(base) x@Xs-MacBook-Pro ~ % yt-dlp "https://vod.afreecatv.com/player/120332459" --verbose
[debug] Command-line config: ['https://vod.afreecatv.com/player/120332459', '--verbose']
[debug] User config "/Users/x/.config/yt-dlp/config": ['-P', '~/Downloads', '-o', '%(title)s.%(ext)s', '-f', 'bv*+ba/b', '--merge-output-format', 'mp4', '--alias', '--insta', '-o "Instagram %(title)s %(upload_date)s %(id)s.%(ext)s"', '--alias', '--ori', '-o "%(title)s %(upload_date)s.%(ext)s"', '--live-from-start', '--write-subs', '--sub-langs', 'en']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (pip)
[debug] Python 3.8.12 (CPython x86_64 64bit) - macOS-10.16-x86_64-i386-64bit (OpenSSL 1.1.1w  11 Sep 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2023.11.17, mutagen-1.45.1, requests-2.31.0, sqlite3-3.37.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[afreecatv] Extracting URL: https://vod.afreecatv.com/player/120332459
[afreecatv] 120332459: Downloading JSON metadata
[afreecatv] 120332459: Downloading video info XML
ERROR: [afreecatv] 120332459: 120332459: Failed to parse XML (caused by ParseError('no element found: line 1, column 0')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/Users/x/opt/miniconda3/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
  File "/Users/x/opt/miniconda3/lib/python3.8/site-packages/yt_dlp/extractor/afreecatv.py", line 202, in _real_extract
    video_xml = self._download_xml(
  File "/Users/x/opt/miniconda3/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1086, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/Users/x/opt/miniconda3/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1056, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
  File "/Users/x/opt/miniconda3/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1046, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/Users/x/opt/miniconda3/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1026, in _parse_xml
    self.__print_error('Failed to parse XML' if errnote is None else errnote, fatal, video_id, ve)
  File "/Users/x/opt/miniconda3/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1016, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/Users/x/opt/miniconda3/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1024, in _parse_xml
    return compat_etree_fromstring(xml_string.encode('utf-8'))
  File "/Users/x/opt/miniconda3/lib/python3.8/site-packages/yt_dlp/compat/__init__.py", line 24, in compat_etree_fromstring
    return etree.XML(text, parser=etree.XMLParser(target=_TreeBuilder()))
  File "/Users/x/opt/miniconda3/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0`
