### ISSUE TITLE
Version number on PyPI is different from version number on Github

### ISSUE THREAD

**Issue by countermeasure** [yt-dlp/yt-dlp#9678]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The current yt-dlp version number in Github is 2024.04.09: https://github.com/yt-dlp/yt-dlp/releases

But the current yt-dlp version number in PyPI is 2024.4.9: https://pypi.org/project/yt-dlp/

To my mind, this difference might qualify as a bug in the build/release process.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
-
```

**Comment by Grub4K** [comment]
The correct version number is `2024.04.09` in conformance with datever, however PyPI normalizes those leading zeros away in conformance with the [version specifier spec](<https://packaging.python.org/en/latest/specifications/version-specifiers/#integer-normalization>). Since we want to keep `XXXX.XX.XX` as the format there is not much we can do, and this shouldnt be considered a bug.

FYI, `python -m pip install "yt-dlp==2024.04.09"` for example works bc those versions are the same, but pypi normalizes it for display

**Comment by countermeasure** [comment]
Thanks for explaining, @Grub4K.
