### ISSUE TITLE
Compiling yt-dlp to WebAssembly ¿Any attempts?

### ISSUE THREAD

**Issue by envemos** [yt-dlp/yt-dlp#9820]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Learning about cross-platform development frameworks like Flet (so you can develop in Python) allows you to easily import Python libraries into your development processes. But there are several problems when trying to export to the web and mobile environment. In this case I will focus on the web format just so as not to cover too much.

In the case of wanting to publish a static website developed in Flet (https://flet.dev/docs/publish/web/static-website), the framework publishes a website that uses Pyodide, which is in charge of translating the Python libraries to WASM.

In this specific case it would be necessary to be able to convert yt-dlp to be able to be used from the web browser.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
No point in compiling to wasm due to CORS.

**Comment by TheColorman** [comment]
What about use in Electron applications? Or does it just make more sense to wrap the binary at that point?

**Comment by seproDev** [comment]
Imo. just use the standalone binary at that point. Why use an experimental python runtime that may or may not work as desired compared to just standard cpython.

If someone does try it, I'd be interested to hear back on what works and what doesn't.

**Comment by seproDev** [comment]
With a bit of monkey patching, I was able to get yt-dlp running in Pyodide and download some videos.
Not that it is very useful, as I needed to disable all CORS security features. I also didn't bother adding ffmpeg support. This would probably require translating the CLI arguments yt-dlp uses to the ffmpeg.wasm api. Threading also doesn't seem to work.

The main advantage to running yt-dlp on a user's device, compared to on a server, is that no one needs to pay for the servers' bandwidth and the traffic is coming from the user's IP and not some datacenter IP. Using a CORS proxy would negate that.
If you have the user install some browser extension to bypass the CORS limitations, you might as well ask them to install a program. And if you have them install an Electron App, why not ship the yt-dlp executable instead of trying to get yt-dlp running in wasm.

**Comment by ThatGuySam** [comment]
This a win for yt-dlpon edge via WebAssembly. 

Both Vercel and Cloudflare support WebAssembly at the edge: 
https://vercel.com/docs/functions/wasm
https://developers.cloudflare.com/workers/languages/python/

**Comment by CypherpunkSamurai** [comment]
> With a bit of monkey patching, I was able to get yt-dlp running in Pyodide and download some videos.

Can you post a link to your repository, or possibly what files you have patched?

**Comment by pirate** [comment]
I would also love to build yt-dlp into the ArchiveBox Browser Extension so we can download video straight from client devices without having to ship URLs to a separate server for archival. WASM yt-dlp would be perfect as extensions don't face the same CORS limitations, and we'd love to have a cross-platform solution that could work from React Native/Electron/Extensions.

**Comment by MartinBarker** [comment]
commenting to track

**Comment by pzhlkj6612** [comment]
> commenting to track 

 _Originally posted by @MartinBarker_

<br>

To future people: try clicking the "**Subscribe**" button in the sidebar to track activities in this thread. See also: [Default subscriptions § About notifications - GitHub Docs](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications#default-subscriptions).

**Comment by maifeeulasad** [comment]
what if I integrate wasm for ytdlp, then create an extension? That resolves that cors issues right?!

**Comment by seproDev** [comment]
Someone did that here https://github.com/machineonamission/dlpro

**Comment by philiprhoades** [comment]
I also had the idea that WASM / WASI might be useful and asked DeepSeek about the viability which responded with interesting info plus the link here.

Any more progress from anybody?

**Comment by weskerty** [comment]
The problem isn't yt-dlp or ffmpeg... It's browsers and their CORS security... They prohibit external links... It's too complicated.

If we want yt-dlp on websites for everyone, the first step is to create a browser without these security systems, or at least with different security measures, or one that allows sites at will.

**Comment by ThatGuySam** [comment]
The CORS argument has merits but also there are WASM runtimes for servers: 
https://github.com/appcypher/awesome-wasm-runtimes

It's a bit more work but you can also get it working on browser if you setup an accompanying proxy endpoint on the same domain.

**Comment by weskerty** [comment]
Doesn't that break the purpose of Web Offline PWA? In the end it's still the same...

**Comment by ThatGuySam** [comment]
Well yeah, but I'm not sure anyone is expecting a downloader to work in an offline app

**Comment by weskerty** [comment]
hahahaha you are right. I had my image search engine and local conversion project in mind (cors broke my image search engine and ffmpeg weighed more than 25mb of cloudflare pages and was a headache. I came to this issue by accident by jumping from ffmpeg)

**Comment by OvercookedBeef** [comment]
I don't understand. Do you guys really think that just because it's called WASM that it can only be used on the web? You all know that WEBP images and WEBM videos can be played outside the web right? It's just a name.

To answer "Why not just ship the binary", WASM has a lot of potential in the area of sandboxed plugins/scripting. It means you don't have to restrict your addons to a dedicated language like Lua (which wouldn't work sandboxed with yt-dlp anyway) and gives the ability to use any language and pre-existing library, while ALSO having the ability to sandbox it (e.g. prevent direct file system access). For a program integrating yt-dlp directly it wouldn't be an issue but if you have a generic video playing software and want to allow plugins to add more capabilities, this is relevant.
